force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the application that sourced this account</description>
    <inlineHelpText>A link to the application that sourced this account</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteCustomersController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class is responsible for cleaning of Customer records 
 *  @author : A5E Consulting
 *  @date : 02/24/2016
 *
 *  Change History:
 *
 *  Developer       Date          Description
 *  ------------------------------------------------------------------------------------------------
 *
 *  A5E Consulting 02/24/2016     Initial Development
 
 *************************************************************************************************/
public class DeleteCustomersController {
	
    // Get Set methods for message Flag 
    public Boolean messageFlag{ get; set ; }

    public DeleteCustomersController (){
    	messageFlag = false;
    }
	
	// Delete the Customers which don't have APPLICATION & PRODUCT                                     
    public void deleteCustomers(){
    	
    	List<Account> CustomersList= new List<Account>();    
        
        try{
            //Step for Retriving the Customers List usinfg SOQL &
          delete  [Select Id from Account where Id NOT In (Select Customer__c from Application__C) and id not in ( Select Customer__c from Product__c)];           
          messageFlag = true;          
        }
        catch(Exception e){
            messageFlag=false;
        } 
    }
}