force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Adjudication_Decision_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Adjudication_Decision_Last_Changed_Date__c</fullName>
    <description>Adjudication Decision Last Changed Date</description>
    <inlineHelpText>Adjudication Decision Last Changed Date</inlineHelpText>
    <label>Adjudication Decision Last Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Adjudication_Response__c.field-meta.xml
<CustomField>
    <fullName>Adjudication_Response__c</fullName>
    <label>Adjudication Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/AML_Decision_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>AML_Decision_Last_Changed_Date__c</fullName>
    <description>AML Decision Last Changed Date</description>
    <inlineHelpText>AML Decision Last Changed Date</inlineHelpText>
    <label>AML Decision Last Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/AML_Decision_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>AML_Decision_Timestamp__c</fullName>
    <description>AML Decision Timestamp</description>
    <inlineHelpText>AML Decision Timestamp</inlineHelpText>
    <label>AML Decision Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/AML_Response__c.field-meta.xml
<CustomField>
    <fullName>AML_Response__c</fullName>
    <label>AML Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Number_AutoNumber__c.field-meta.xml
<CustomField>
    <fullName>Application_Number_AutoNumber__c</fullName>
    <description>Auto generate the application number</description>
    <displayFormat>APP{00000}</displayFormat>
    <inlineHelpText>Auto generate the application number</inlineHelpText>
    <label>Application Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Approved</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
            <value>
                <fullName>Manually Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Status_Last_Changed_Date__c</fullName>
    <description>Application Status Last Changed Date</description>
    <inlineHelpText>Application Status Last Changed Date</inlineHelpText>
    <label>Application Status Last Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CSR_Manual_Review_Reason__c.field-meta.xml
<CustomField>
    <fullName>CSR_Manual_Review_Reason__c</fullName>
    <label>CSR Manual Review Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Hit – Adjudication</fullName>
            </value>
            <value>
                <fullName>No Hit – AML</fullName>
            </value>
            <value>
                <fullName>System Not Reachable – Adjudication</fullName>
            </value>
            <value>
                <fullName>System Not Reachable - AML</fullName>
            </value>
            <value>
                <fullName>System Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/CurrentBKCP__c.field-meta.xml
<CustomField>
    <fullName>CurrentBKCP__c</fullName>
    <description>CurrentBKCP</description>
    <inlineHelpText>CurrentBKCP</inlineHelpText>
    <label>CurrentBKCP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision_Summary__c.field-meta.xml
<CustomField>
    <fullName>Decision_Summary__c</fullName>
    <description>Decision Summary</description>
    <inlineHelpText>Decision Summary</inlineHelpText>
    <label>Decision Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Decision_Timestamp__c</fullName>
    <label>Decision Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Employment_Months__c</fullName>
    <label>Employment Months</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Employment_Years__c</fullName>
    <label>Employment Years</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Gross_Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Gross_Monthly_Income__c</fullName>
    <label>Gross Monthly Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Owner__c.field-meta.xml
<CustomField>
    <fullName>Home_Owner__c</fullName>
    <label>Home Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Own Property</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Housing_Costs__c.field-meta.xml
<CustomField>
    <fullName>Housing_Costs__c</fullName>
    <label>Housing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Common Law</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Monthly_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expenses__c</fullName>
    <label>Monthly Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Number_of_Dependants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Dependants__c</fullName>
    <label>Number of Dependants</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>More</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_City__c</fullName>
    <label>Permanent Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PostalCode__c</fullName>
    <label>Permanent Address Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Province__c</fullName>
    <label>Permanent Address Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <label>Permanent  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Number__c</fullName>
    <label>Permanent Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Politically_Exposed_Foreign_Person__c.field-meta.xml
<CustomField>
    <fullName>Politically_Exposed_Foreign_Person__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Politically Exposed Foreign Person</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <label>SIN</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Third_Party_Direction__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Direction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Direction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Webservice_Request__c.field-meta.xml
<CustomField>
    <fullName>Webservice_Request__c</fullName>
    <label>Webservice Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Webservice_Response__c.field-meta.xml
<CustomField>
    <fullName>Webservice_Response__c</fullName>
    <label>Webservice Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApplicationReSubmitController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class is to call re-submit method
*  @author : A5E Consulting
*  @date : 07 Sept 2020   
*
*************************************************************************************************/
public with sharing class ApplicationReSubmitController{
    
    public Application__C application{get;set;}
    public Application_Form_Configuration__c afSettings{get;set;}
    public Boolean progressBar{get;set;}
    public string errorMessage{get;set;}
    
    public ApplicationReSubmitController(){
        
    }
    
    public ApplicationReSubmitController(ApexPages.StandardController controller) {
        String appID = ApexPages.currentPage().getParameters().get('id');
        
        system.debug(''+appID);
        
        progressBar = true;
        errorMessage = null;
        
        afSettings = Application_Form_Configuration__c.getOrgDefaults();
        
        application = new Application__C();
        application = [Select id, Name, Last_Name__c, First_Name__c, Birth_Date__c, SIN__C, 
                Permanent_Address_Street_Number__c, Permanent_Address_Street_Name__c, Permanent_Address_City__c, 
                Permanent_Address_PostalCode__c, Permanent_Address_Province__c, 
                       //Primary_Phone_Number__c, 
                Home_Phone__c, Cell_Phone__c, Work_Phone__c,
                Marital_Status__c, Home_Owner__c,
                Third_Party_Direction__c, Politically_Exposed_Foreign_Person__c,
                Employment_Years__c, Employment_Months__c, Gross_Monthly_Income__c, Employment_Status__c,
                CurrentBKCP__c, Number_of_Dependants__c,
                Housing_Costs__c, Monthly_Expenses__c,
                Webservice_Response__c
                From Application__c where id = : appID];
                
        system.debug(''+application);
    }
    
    public pageReference reSubmit(){
        
        DecisionEngineUtil.IntegrationResponse intResponse = new DecisionEngineUtil.IntegrationResponse();
        Boolean flagSIN = false;
        
        try{
            //submit to adjudication engine
            if(null != application.SIN__c && (application.SIN__c).startsWith('9')){
                flagSIN = true;
            }
            if(application.CurrentBKCP__c != 'None' && flagSIN == false){
                //commented on 25.11. Need to check
                //***intResponse = DecisionWS.submit(application, afSettings);
                
                Application.Webservice_Request__c = intResponse.request;
                Application.Webservice_Response__c = intResponse.response;
                Application.Adjudication_Response__c = intResponse.adjudicationResponse;
                Application.AML_Response__c = intResponse.amlResponse;
                
                system.debug('Attachment data' + intResponse.adjudicationFile);
                //Attach the adjudication and AML response to application
                if(String.isNotBlank(intResponse.adjudicationFile)){
                    
                    Attachment adjudicationAttach = new Attachment();
                    adjudicationAttach.Body = Blob.valueOf(intResponse.adjudicationFile);
                    adjudicationAttach.Name = 'Adjudication - Response.txt';
                    adjudicationAttach.ParentId = Application.ID;
                    insert adjudicationAttach;
                }
            }
        }
        catch(Exception e){
            //Application.Name = APP_NAME_INCOMPLETE_POWER_CURVE_ERR;
            Application.Application_Status_Last_Changed_Date__c = system.now();
            Application.Application_Status__c = 'Needs Review';
            system.debug(''+e);
        }        
        
        //Set all time stamps
        Application.Application_Status_Last_Changed_Date__c = system.now();
        Application.Decision_Timestamp__c = system.now();
        Application.Adjudication_Decision_Last_Changed_Date__c = system.now();
        Application.AML_Decision_Last_Changed_Date__c = system.now();
        Application.AML_Decision_Timestamp__c = System.now();
        
        //Fetch auto number field to populate on the records
        String ApplicationAutoNumberValue = [SELECT id, Application_Number_AutoNumber__c from Application__c where id =: application.id].Application_Number_AutoNumber__c;
        Application.Name = ApplicationAutoNumberValue;
        
        System.debug('intResponse  : '+ intResponse );
        //if current BKCP value is selected as None
        if(Application.CurrentBKCP__c == 'None'){
            
            //Application.Application_Status_Last_Changed_Date__c = system.now();
            Application.Application_Status__c = 'System Declined';
            Application.Decision_Summary__c = 'User is not currently or have not been in a bankruptcy or consumer proposal process within the last 7 years';
        }else if(flagSIN == true){
            //Application.Application_Status_Last_Changed_Date__c = system.now();
            Application.Application_Status__c = 'System Declined';
            Application.Decision_Summary__c = 'User is not permanent resident of Canada';
        }else if (null == intResponse || String.isBlank(Application.Webservice_Response__c)) {
            // due to exception returned null
            
            //Application.Application_Status_Last_Changed_Date__c = system.now();
            Application.Application_Status__c = 'Needs Review';
            Application.CSR_Manual_Review_Reason__c = 'System Not Reachable – Adjudication';
            Application.Decision__c = 'Needs Review';
            //Application.Decision_Timestamp__c = system.now();
            //Application.Adjudication_Decision_Last_Changed_Date__c = system.now();
        } 
        else {
            // Set decision-related fields on Application
            //Adjudication
            Application.Decision__c = intResponse.adjudicationStatus;
            //Application.Decision_Timestamp__c = system.now();//DateTime.valueof(intResponse.adjudicationDecisionTimestamp);
            //Application.Adjudication_Decision_Last_Changed_Date__c = system.now();//DateTime.valueof(intResponse.adjudicationDecisionTimestamp);
            Application.Decline_Reason__c = intResponse.declineReason;
            /*Application.Decline_Reason__c = declineReasonValue(intResponse.declineReason);
            if(String.isBlank(Application.Decline_Reason__c)){
                Application.Decline_Reason__c = intResponse.declineReason;
            }*/
            Application.Credit_Score__c = null==intResponse.creditScore?'':(''+intResponse.creditScore);
            Application.Bankruptcies__c = intResponse.totalNumberofBankrupcies;
            Application.Decision_Summary__c = intResponse.decisionSummary;
            Application.Lender_Approved_Amount__c = intResponse.approvedAmount;
            Application.Interest_Rate__c = intResponse.approvedInterestRate;
            
            //AML
            Application.AML_Decision__c = intResponse.amlStatus;
            /*if(String.isNotBlank(Application.AML_Decision__c)){
                Application.AML_Decision_Last_Changed_Date__c = system.now();
            }*/
            Application.Fraud_Flag__c = null;
            if(intResponse.fraudFlag == 'N'){
                Application.Fraud_Flag__c = 'No';
            }else if(intResponse.fraudFlag == 'Y'){
                Application.Fraud_Flag__c = 'Yes';
            }
            Application.AML_Decision_Summary__c = intResponse.amlSummary;
            //Application.AML_Decision_Timestamp__c = intResponse.amlTimestamp;
            Application.AML_Declined_Reason__c = intResponse.amlDeclineReason;
            Application.Unique_ID_AML__c = intResponse.amlUniqueNumber;
            
            Application.CSR_Manual_Review_Reason__c = intResponse.needsReviewReason;
            
            //Calculate application status
            if(Application.Decision__c == 'Approved' && Application.AML_Decision__c == 'Approved'){
                Application.Application_Status__c = 'System Approved';
                
            }
            else if(Application.Decision__c == 'Needs Review' || Application.AML_Decision__c == 'Needs Review'){
                Application.Application_Status__c = 'Needs Review';
                
                /*if(Application.Decision__c == 'Needs Review'){
                    Application.CSR_Manual_Review_Reason__c = 'System Not Reachable – Adjudication';
                    
                }else if(Application.AML_Decision__c == 'Needs Review'){
                    Application.CSR_Manual_Review_Reason__c = 'System Not Reachable - AML';
                    //Application.AML_Decision_Timestamp__c = System.now();
                }*/
            }
            else if(Application.Decision__c == 'Declined' || Application.AML_Decision__c == 'Declined'){
                Application.Application_Status__c = 'System Declined';
                
                /*if(Application.Decline_Reason__c == 'No Hit'){
                    Application.CSR_Manual_Review_Reason__c = 'No Hit – Adjudication';
                }else if(Application.AML_Declined_Reason__c == 'No Hit'){
                    Application.CSR_Manual_Review_Reason__c = 'No Hit – AML';
                }*/
            }else if(Application.Decision__c == 'Approved' && String.isBlank(Application.AML_Decision__c)){
                Application.Application_Status__c = 'Needs Review';
                
            }
            //Application.Application_Status_Last_Changed_Date__c = system.now();
            //Application.DSR_Score__c = (Application.Housing_Costs__c + Application.Monthly_Expenses__c) / Application.Gross_Monthly_Income__c;
            
        }
        //Calculate DSR Score
        Application.DSR_Score__c = ((Application.Housing_Costs__c + Application.Monthly_Expenses__c) / Application.Gross_Monthly_Income__c)*100;
        
        //Application.Application_Completed_Submitted__c = true;    
        
        try{
            update application;
            
        }catch(Exception e){
            system.debug('Exception : ' + e);
            if(e.getTypeName() == 'System.DmlException'){
                
                errorMessage = e.getDmlMessage(0);
            }else{
                errorMessage = e.getMessage();
            }
        }        
        
        progressBar = false;
        
        return null;
    }
    
    //to map decline reasons to readable values
    /*private string declineReasonValue(String reason){
        map<String, Adjudication_Reason_Mapping__c> reasonMappingMap = Adjudication_Reason_Mapping__c.getAll();
        
        Adjudication_Reason_Mapping__c reasonValue = reasonMappingMap.get(reason);
        if(null == reasonValue){
            return null;
        }else{
            return reasonValue.reason__c;
        }
    }*/
}