force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CurrentBKCP__c.field-meta.xml
<CustomField>
    <fullName>CurrentBKCP__c</fullName>
    <description>CurrentBKCP</description>
    <inlineHelpText>CurrentBKCP</inlineHelpText>
    <label>CurrentBKCP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Employment_Months__c</fullName>
    <label>Employment Months</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Employment_Years__c</fullName>
    <label>Employment Years</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Gross_Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Gross_Monthly_Income__c</fullName>
    <label>Gross Monthly Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Owner__c.field-meta.xml
<CustomField>
    <fullName>Home_Owner__c</fullName>
    <label>Home Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Own Property</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Housing_Costs__c.field-meta.xml
<CustomField>
    <fullName>Housing_Costs__c</fullName>
    <label>Housing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Common Law</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Monthly_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expenses__c</fullName>
    <label>Monthly Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Number_of_Dependants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Dependants__c</fullName>
    <label>Number of Dependants</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>More</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_City__c</fullName>
    <label>Permanent Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PostalCode__c</fullName>
    <label>Permanent Address Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Province__c</fullName>
    <label>Permanent Address Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <label>Permanent  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Number__c</fullName>
    <label>Permanent Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Politically_Exposed_Foreign_Person__c.field-meta.xml
<CustomField>
    <fullName>Politically_Exposed_Foreign_Person__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Politically Exposed Foreign Person</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <label>SIN</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Third_Party_Direction__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Direction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Direction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Form_Configuration__c/Application_Form_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Form Configuration</label>
</CustomObject>

force-app/main/default/objects/Application_Form_Configuration__c/fields/AML_Member_Code__c.field-meta.xml
<CustomField>
    <fullName>AML_Member_Code__c</fullName>
    <label>AML Member Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Configuration__c/fields/AML_Password__c.field-meta.xml
<CustomField>
    <fullName>AML_Password__c</fullName>
    <label>AML Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Configuration__c/fields/Member_Code__c.field-meta.xml
<CustomField>
    <fullName>Member_Code__c</fullName>
    <label>Member Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the application that sourced this account</description>
    <inlineHelpText>A link to the application that sourced this account</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DecisionEngine.cls
/**************************************************************************************************
*
*  Class:   DecisionEngine
*
*  @description : Get decision and other related data for an Application
*  @author : A5E Consulting
*  @date : 11/12/2020   
*
*************************************************************************************************/
public with sharing class DecisionEngine {
    
    // Below variable used to track the decison
    public static string decision;
    public static string APPROVE = 'Approve';
    public static string REVIEW = 'Review';
    public static string DECLINE = 'Decline';

    
    public static ResponseWrapper submit( Application__c app){
        string requestJSON = createJSONRequest(app);
        return getDecision(requestJSON);
    }
    public static string createJSONRequest( Application__c app){
        Application_Form_Configuration__c appConfigSetting = Application_Form_Configuration__c.getInstance();

        RequestPayload request = new RequestPayload();
        request.TUCANREL4 = getDecisionRequestXML(app, appConfigSetting);
        request.IFSXMLRq = getAMLRequestXML(app, appConfigSetting);
        request.monthlyRentPaymentAmount = app.Housing_Costs__c;
        request.totalOtherMonthlyExpensesAmount = app.Monthly_Expenses__c;
        request.grossMonthlyIncomeAmount = app.Gross_Monthly_Income__c;
        // request.birthDate = string.valueOf(app.Birth_Date__c);
        // request.employmentTypeCode = app.Employment_Status__c;
        // if(app.CurrentBKCP__c=='BK'){
        //     request.financialConditionCode = 'BK';
        // }else if(app.CurrentBKCP__c=='CP'){
        //     request.financialConditionCode = 'CP';
        // }
        // request.dependentsCount = app.Number_of_Dependants__c;
        // request.maritalStatusCode = app.Marital_Status__c;
        // if(app.Home_Owner__c=='Own Property'){
        //     request.homeOwnerInd = true;
        // }else if(app.Home_Owner__c=='Rent'){
        //     request.homeOwnerInd = false;
        // }
        // request.monthsEmployed = string.valueOf(app.Employment_Years__c * 12 + app.Employment_Months__c);
        // request.politicallyExposedInd = app.Politically_Exposed_Foreign_Person__c;
        // request.otherBeneficiaryInd = app.Third_Party_Direction__c;
        
         String returnJSONString = JSON.serialize(request);
        
        // System.debug('decisionRequestXML :');
        // System.debug(returnJSONString );
        
        return returnJSONString;

    }
    //  Send data over to decision engine API and parse responses Adjudication, AML, and TU
    public static ResponseWrapper getDecision(string requestJSON) {
        RequestPayload reqPayload = (RequestPayload) System.JSON.deserialize(requestJSON, RequestPayload.class);
        
        String adjResponse = AdjudicationWebService.getDecision(reqPayload);
        String creditResportService = CreditReportService.parseXMLStringTruncarel4(reqPayload.TUCANREL4);
        String IFSXMLRqResponse = AMLWebService.parseXMLStringIFSXMLRq(reqPayload.IFSXMLRq);
        ResponseWrapper obj = new ResponseWrapper();
        obj.adjudication = adjResponse;
        obj.creditReport = creditResportService;
        obj.IFSXMLRq = IFSXMLRqResponse;
        obj.request = requestJSON;

        System.debug('$$ adjudication '+adjResponse);
        System.debug('$$ TUResponse ='+creditResportService);
        System.debug('$$ IFSXMLRqResponse ='+IFSXMLRqResponse);
        //return json.serialize(obj);
        return obj;
    }

    public static String getDecisionRequestXML(Application__c app, Application_Form_Configuration__c appConfigSetting){
        
        DecisionEngineUtil.DecisionXMLRequest decisionXMLRequest = new DecisionEngineUtil.DecisionXMLRequest();
        decisionXMLRequest.fieldValues.put('MemberCode', appConfigSetting.Member_Code__c);
        DecisionEngineUtil.DecisionXMLRequest_Subject decisionSubjectXML = new DecisionEngineUtil.DecisionXMLRequest_Subject();
        decisionXMLRequest.fieldValues.put('Subject', decisionSubjectXML);
        DecisionEngineUtil.DecisionXMLRequest_SubjectName subjectNameXML = new DecisionEngineUtil.DecisionXMLRequest_SubjectName();
        decisionSubjectXML.fieldValues.put('Name', subjectNameXML);
        subjectNameXML.fieldValues.put('LastName', app.Last_Name__c);
        subjectNameXML.fieldValues.put('FirstName', app.First_Name__c);
        String BirthMonth = string.valueOf(app.Birth_Date__c.month()).leftPad(2, '0');
        String Birthday = string.valueOf(app.Birth_Date__c.day()).leftPad(2, '0');
        String Birthyear = string.valueOf(app.Birth_Date__c.year()); 
        String FinalBirthdate = Birthyear+BirthMonth+Birthday;
        
        decisionSubjectXML.fieldValues.put('DOB', FinalBirthdate);
        decisionSubjectXML.fieldValues.put('SIN', app.SIN__C);
        
        /*
        decisionXMLRequest.fieldValues.put('Route', 'RouteDest=' + afSettings.RouteDest__c + ':RouteType=' + afSettings.RouteType__c);
        decisionXMLRequest.fieldValues.put('UserReference', afSettings.UserReference__c);
        
        decisionXMLRequest.fieldValues.put('Password', afSettings.Password__c);
        decisionXMLRequest.fieldValues.put('Product', afSettings.Product__c);
        
        DecisionWSUtil.DecisionXMLRequest_TTY decisionTTYXML = new DecisionWSUtil.DecisionXMLRequest_TTY();
        decisionXMLRequest.fieldValues.put('TTY', decisionTTYXML);
        
        decisionTTYXML.fieldValues.put('FFR', afSettings.FFR__c);
        decisionTTYXML.fieldValues.put('Language', afSettings.Language__c);
        
       
        
        DecisionWSUtil.DecisionXMLRequest_SubjectAddress subjectAddressXML = new DecisionWSUtil.DecisionXMLRequest_SubjectAddress();
        decisionSubjectXML.fieldValues.put('Address', subjectAddressXML);
        
        subjectAddressXML.fieldValues.put('Civic', app.Permanent_Address_Street_Number__c);
        subjectAddressXML.fieldValues.put('Street', app.Permanent_Address_Street_Name__c);
        subjectAddressXML.fieldValues.put('City', app.Permanent_Address_City__c);
        subjectAddressXML.fieldValues.put('Postal', app.Permanent_Address_PostalCode__c);
        subjectAddressXML.fieldValues.put('Prov', app.Permanent_Address_Province__c);
        if(app.Primary_Phone_Number__c == 'Home Phone'){
            subjectAddressXML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Home_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Mobile Phone'){
            subjectAddressXML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Cell_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Work Phone'){
            subjectAddressXML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Work_Phone__c));
        }
        
        DecisionWSUtil.DecisionXMLRequest_OptionalRequest decisionOptionRequestXML = new DecisionWSUtil.DecisionXMLRequest_OptionalRequest();
        decisionXMLRequest.fieldValues.put('OptionalRequest', decisionOptionRequestXML);
        
        decisionOptionRequestXML.fieldValues.put('OwningBureau', afSettings.Owning_Bureau__c);
        decisionOptionRequestXML.fieldValues.put('ErrorText', afSettings.Error_Text__c );
        decisionOptionRequestXML.fieldValues.put('TradeMop', afSettings.TradeMop__c);
        decisionOptionRequestXML.fieldValues.put('Summary', afSettings.Summary__c);
        */
        
        XmlStreamWriter w = new XmlStreamWriter();
        decisionXMLRequest.getXMLString(w);

        String decisionRequestXML = w.getXmlString();
        w.close();
        
        decisionRequestXML.replace('\"', '\\"');
        System.debug('decisionRequestXML :');
        System.debug(decisionRequestXML);
        
        return decisionRequestXML; 
    }
    
    private static String getAMLRequestXML(Application__c app, Application_Form_Configuration__c appConfigSetting){
        
        DecisionEngineUtil.AMLXMLRequest amlXMLRequest = new DecisionEngineUtil.AMLXMLRequest ();
        amlXMLRequest.fieldValues.put('MemberCode', appConfigSetting.AML_Member_Code__c   );
        amlXMLRequest.fieldValues.put('Password', appConfigSetting.AML_Password__c);
        DecisionEngineUtil.AMLXMLRequest_AML amlXMLRequest_AML = new DecisionEngineUtil.AMLXMLRequest_AML();
        amlXMLRequest.fieldValues.put('AML', amlXMLRequest_AML);
        amlXMLRequest_AML.fieldValues.put('LastName', app.Last_Name__c);
        amlXMLRequest_AML.fieldValues.put('FirstName', app.First_name__c);
        
        /*
        amlXMLRequest.fieldValues.put('Route', 'RouteType=' + afSettings.AML_Route_Type__c);
        amlXMLRequest.fieldValues.put('UserReference', afSettings.AML_User_Reference__c);
        amlXMLRequest.fieldValues.put('PRODUCTCODE', afSettings.AML_Product_Code__c);
        
        DecisionWSUtil.AMLXMLRequest_Address amlXMLRequest_Address = new DecisionWSUtil.AMLXMLRequest_Address();
        amlXMLRequest_AML.fieldValues.put('Address', amlXMLRequest_Address);
        amlXMLRequest_Address.fieldValues.put('Civic', app.Permanent_Address_Street_Number__c);
        amlXMLRequest_Address.fieldValues.put('Street', app.Permanent_Address_Street_Name__c);
        amlXMLRequest_Address.fieldValues.put('City', app.Permanent_Address_City__c);
        amlXMLRequest_Address.fieldValues.put('Postal', app.Permanent_Address_PostalCode__c);
        amlXMLRequest_Address.fieldValues.put('Prov', app.Permanent_Address_Province__c);
        if(app.Primary_Phone_Number__c == 'Home Phone'){
            amlXMLRequest_Address.fieldValues.put('Telephone', unformattedPhoneNumber(app.Home_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Mobile Phone'){
            amlXMLRequest_Address.fieldValues.put('Telephone', unformattedPhoneNumber(app.Cell_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Work Phone'){
            amlXMLRequest_Address.fieldValues.put('Telephone', unformattedPhoneNumber(app.Work_Phone__c));
        }
        
        if(app.Primary_Phone_Number__c == 'Home Phone'){
            amlXMLRequest_AML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Home_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Mobile Phone'){
            amlXMLRequest_AML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Cell_Phone__c));
        }else if(app.Primary_Phone_Number__c == 'Work Phone'){
            amlXMLRequest_AML.fieldValues.put('Telephone', unformattedPhoneNumber(app.Work_Phone__c));
        }
        
        DecisionWSUtil.AMLXMLRequest_PI amlXMLRequest_PI = new DecisionWSUtil.AMLXMLRequest_PI();
        amlXMLRequest.fieldValues.put('PI', amlXMLRequest_PI);
        
        String BirthMonth = string.valueOf(app.Birth_Date__c.month());
        String Birthday = string.valueOf(app.Birth_Date__c.day());
        String Birthyear = string.valueOf(app.Birth_Date__c.year()); 
        String FinalBirthdate = Birthyear+(BirthMonth.length()==1?('0'+BirthMonth):BirthMonth)+(Birthday.length()==1?('0'+Birthday):Birthday);
        amlXMLRequest_PI.fieldValues.put('DOB', FinalBirthdate);
        */

        XmlStreamWriter w = new XmlStreamWriter();
        amlXMLRequest.getXMLString(w);

        String decisionRequestXML = w.getXmlString();
        w.close();
        System.debug('decisionRequestXML :');
        System.debug(decisionRequestXML);
        
        return decisionRequestXML;   
    }


    public class ResponseWrapper{
        public string request;
        public string adjudication;
        public string creditReport;
        public string IFSXMLRq;
    }
    public class RequestPayload{
        public string TUCANREL4;
        public decimal totalOtherMonthlyExpensesAmount;
        public boolean politicallyExposedInd;
        public boolean otherBeneficiaryInd;
        public string monthsEmployed;
        public decimal monthlyRentPaymentAmount;
        public string maritalStatusCode;
        public string IFSXMLRq;
        public Boolean homeOwnerInd;
        public Decimal grossMonthlyIncomeAmount;
        public String financialConditionCode;
        public String employmentTypeCode;
        public String dependentsCount;
        public String birthDate;
    }
}