force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/AML_Decision__c.field-meta.xml
<CustomField>
    <fullName>AML_Decision__c</fullName>
    <description>AML Decision</description>
    <inlineHelpText>AML Decision</inlineHelpText>
    <label>AML Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Approved</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
            <value>
                <fullName>Manually Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <inlineHelpText>Product that the customer is applying for.</inlineHelpText>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/Application_Form_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Form Settings</label>
</CustomObject>

force-app/main/default/classes/ApplicationDecisionController.cls
/**************************************************************************************************
 *
 *  Class:    
 *
 *  @description : This controller is for the 
 *  @author : A5E Consulting
 *  @date : 11/11/2020
 
 *************************************************************************************************/
public without sharing class ApplicationDecisionController {
    public Application_Form_Settings__c AppFormSettings {get;set;}
    public String adjudicationDecsion{get;set;}
    public String amlDecision{get;set;}
    public String applicationStatus{get;set;}
    public String applicationId {get;set;}
    
    //Decline Page updates
    public String loanType {get;set;}
    
    public Boolean cardNotInBKCP {get;set;}
    public String DECISION_ACCEPTED {get;set;} 
    public String DECISION_DECLINED {get;set;}
    public String DECISION_ERROR {get;set;}
    
    private Application__c application;

    public ApplicationDecisionController() {
        
        AppFormSettings = Application_Form_Settings__c.getOrgDefaults();
        
        DECISION_ACCEPTED = 'System Approved';
        DECISION_DECLINED = 'System Declined';
        DECISION_ERROR = 'Needs Review';
        
        applicationId = ApexPages.currentPage().getParameters().get('id');
        
        application = Utilities.getApplicationById(applicationId);
                     
        //Decline Page updates
        loanType = application.Loan_Type__c;
        adjudicationDecsion = application.Decision__c;
        amlDecision = application.AML_Decision__c;
        if(String.isBlank(amlDecision)){
            amlDecision = '';
        }
        applicationStatus = application.Application_Status__c;
    } 
}