force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <inlineHelpText>Product that the customer is applying for.</inlineHelpText>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>Also known as MICR code</description>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/File_Formats__c.field-meta.xml
<CustomField>
    <fullName>File_Formats__c</fullName>
    <label>File Formats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Product Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the application that sourced this account</description>
    <inlineHelpText>A link to the application that sourced this account</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>The type of credit product this account represents</description>
    <inlineHelpText>The type of credit product this account represents</inlineHelpText>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Information_Accepted__c.field-meta.xml
<CustomField>
    <fullName>PAP_Information_Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the customer agreed to the PAP terms and conditions</description>
    <inlineHelpText>Whether the customer agreed to the PAP terms and conditions</inlineHelpText>
    <label>PAP Information Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Information_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>PAP_Information_Accepted_Date__c</fullName>
    <description>The date on which the customer agreed to the PAP terms and conditions, if applicable</description>
    <inlineHelpText>The date on which the customer agreed to the PAP terms and conditions, if applicable</inlineHelpText>
    <label>PAP Information Accepted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>The specific product this record represents</description>
    <inlineHelpText>The specific product this record represents</inlineHelpText>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PAPInformationProductController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a controller class to input PAP Information for Product record
 *  @author : A5E Consulting
 *  @date : 07/22/2016
 *
 *************************************************************************************************/
 
public with sharing class PAPInformationProductController{
    
    public Product__c productRec{get;set;}
    public Attachment papSupportDocument{get;set;}
    public List<Attachment> attList;
    public Boolean acceptTermsCondition{get;set;}
    
    public Boolean showError{get;set;}
    public String errorMessage{get;set;}
    public boolean showSuccessMessage{get;set;}
    
    public String acceptFormat{get;set;}
    public Integer acceptFileSize{get;set;}
    public Integer fileSize{get;set;}
    public string fileId{get;set;}
    
    public boolean displayPopup {get; set;} 
    
    public List<Attachment> lstAttachment {get;set;}
    
    public PAPInformationProductController(){
        
        //Custom Settings
        Loan_ReEngineering__c loanSettings = Loan_ReEngineering__c.getOrgDefaults();
        
        //To Display Message
        showError = false;
        showSuccessMessage = false;
        
        //Initialize TermsCondition Check bx
        acceptTermsCondition = false;     
        
        //List of PAP attachments
        attList = new List<Attachment>();
        lstAttachment  = new List<Attachment>();
        papSupportDocument = new Attachment();
                
        //File Validation
        acceptFormat = loanSettings.File_Formats__c;
        //fileSize = (Integer)loanSettings.File_Size__c;
        acceptFileSize = (Integer)loanSettings.File_Size__c;
        
        //Get Application ID
        Id prodId = ApexPages.currentPage().getParameters().get('id');
        productRec = [select id, name, Loan_Type__c, PAP_Transit_Code__c, PAP_Bank_Code__c, PAP_Account_Number__c, Application__c, Product_Type__c from Product__c where id =: prodId];
        
        //Attachment List from Product
        attList = [Select id, Name , ParentId , body  from Attachment where ParentId =: prodId and Name like 'PAP_%' ORDER BY CreatedDate DESC ];
        
        //Attachment List from Application
        List<Attachment> attAppList = new List<Attachment>();
        if(productRec.Application__c != null){
            attAppList = [Select id, Name , ParentId , body  from Attachment where ParentId =: productRec.Application__c and Name like 'PAP_%' ORDER BY CreatedDate DESC ];
            for(Attachment att : attAppList){
                attList.add(att);
            }
        }
        
        lstAttachment = attList ;
        if(attList != null && attList.size() > 0){          
            fileId = attList[0].id;            
        }
        
        if(('Affirm Financial Term Loan' != productRec.Loan_Type__c) && (String.isNotBlank(productRec.Product_Type__c) && !productRec.Product_Type__c.contains('Term Loan'))){
            errorMessage='This Application is not for Term Loan, cannot continue with PAP Information.';
            showError=true;
        }
    }
    
    public PageReference navigatePrevious() {
        PageReference pageRef = new PageReference('/' + ProductRec.id);
        return pageref;
    }
    
    public PageReference updatePaymentMethod(){
        
        PageReference pageRef;
        Loan_ReEngineering__c loanSettings = Loan_ReEngineering__c.getOrgDefaults();
        
        if(ProductRec.PAP_Transit_Code__c != null 
            && ProductRec.PAP_Bank_Code__c != null 
            && ProductRec.PAP_Account_Number__c != null 
            //&& papSupportDocument.body != null 
            && acceptTermsCondition == true){
                
                /*//PAP Fields needs to be numeric
                if((!ProductRec.PAP_Transit_Code__c.isNumeric()) || (!ProductRec.PAP_Bank_Code__c.isNumeric()) || (!ProductRec.PAP_Account_Number__c.isNumeric())){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter numbers only for PAP fields');
                    ApexPages.addMessage(myMsg);
                    papSupportDocument = new Attachment();
                    return null;
                }*/
                
                //PAP Transite Code needs to be numeric with exact length = 5
                if((!ProductRec.PAP_Transit_Code__c.isNumeric()) || (ProductRec.PAP_Transit_Code__c).length() < 5){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter 5 numbers only for PAP Transit Code field');
                    ApexPages.addMessage(myMsg);
                    papSupportDocument = new Attachment();
                    return null;
                }
                
                //PAP Account Number needs to be numeric with length between 7 to 12 numbers
                if((!ProductRec.PAP_Account_Number__c.isNumeric()) || ((ProductRec.PAP_Account_Number__c).length() < 7)){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter numbers only for PAP Account Number field and length should be between 7 to 12 numbers');
                    ApexPages.addMessage(myMsg);
                    papSupportDocument = new Attachment();
                    return null;
                }
                
                //PAP Bank Code needs to be numeric with exact length = 3
                if((!ProductRec.PAP_Bank_Code__c.isNumeric()) || (ProductRec.PAP_Bank_Code__c).length() < 3){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter 3 numbers only for PAP Bank Code field');
                    ApexPages.addMessage(myMsg);
                    papSupportDocument = new Attachment();
                    return null;
                }
                
                //PAP Document is required if not available already
                if(attList.size() == 0 && papSupportDocument.body == null){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please upload the PAP Document');
                    ApexPages.addMessage(myMsg);
                    papSupportDocument = new Attachment();
                    return null;
                }
                
                //PAP file validation
                if(papSupportDocument.body != null){
                    
                    //File Extention
                    String extensionVal = papSupportDocument.Name.substringAfterLast('.').toLowerCase();
                    if(!acceptFormat.contains(extensionVal)){
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please attach '+ acceptFormat +' files only');
                        ApexPages.addMessage(myMsg);
                        papSupportDocument = new Attachment();
                        return null;    
                    }   
                    
                    //File Size
                    if(fileSize > acceptFileSize){
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'File size greater than accepted file size');
                        ApexPages.addMessage(myMsg);
                        papSupportDocument = new Attachment();
                        return null;                        
                    }
                }
                
                //Insert PAP DOcument
                if(papSupportDocument.body != null){
                    papSupportDocument.parentid = ProductRec.id;
                    papSupportDocument.name = 'PAP_' + papSupportDocument.name;
                    insert papSupportDocument;
                }               
                
                
                ProductRec.PAP_Information_Accepted__c = acceptTermsCondition;
                ProductRec.PAP_Information_Accepted_Date__c = system.now();
                
                /*loanSettings.Run_Product_Trigger__c = false;
                update loanSettings;
                update ProductRec;
                loanSettings.Run_Product_Trigger__c = true;
                update loanSettings;*/
                
                ProductTriggerHandler.runProductTrigger = false;
                update ProductRec;
                ProductTriggerHandler.runProductTrigger = true;
                
                papSupportDocument = new Attachment();
                showSuccessMessage = true;
                pageRef = ApexPages.currentPage();
        }
        else{
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please fill all the information');
            ApexPages.addMessage(myMsg);
            
            papSupportDocument = new Attachment();
            return null;
        }
        
        acceptTermsCondition = false;
        return pageRef;
    }
    
}