force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Current_BKCP__c.field-meta.xml
<CustomField>
    <fullName>Current_BKCP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current BKCP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name__c</fullName>
    <label>Employer Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Employer_PostalCode__c</fullName>
    <label>Employer PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Province__c.field-meta.xml
<CustomField>
    <fullName>Employer_Province__c</fullName>
    <label>Employer State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Employer_Street_Name__c</fullName>
    <label>Employer Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employer_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Employer_Street_Number__c</fullName>
    <label>Employer Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Employment_Months__c</fullName>
    <label>Employment Months</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Employment_Years__c</fullName>
    <label>Employment Years</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Gross_Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Gross_Monthly_Income__c</fullName>
    <label>Gross Monthly Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Owner__c.field-meta.xml
<CustomField>
    <fullName>Home_Owner__c</fullName>
    <label>Home Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Own Property</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Housing_Costs__c.field-meta.xml
<CustomField>
    <fullName>Housing_Costs__c</fullName>
    <label>Housing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Common Law</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Months_At_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Months_At_Permanent_Address__c</fullName>
    <label>Months At Permanent Address</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Months_At_Previous_Address__c.field-meta.xml
<CustomField>
    <fullName>Months_At_Previous_Address__c</fullName>
    <label>Months At Previous Address</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_City__c</fullName>
    <label>Permanent Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_PostalCode__c</fullName>
    <label>Permanent Address Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Province__c</fullName>
    <label>Permanent Address Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>NB</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>ON</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>YT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <label>Permanent  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Number__c</fullName>
    <label>Permanent Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Previous_Address_City__c</fullName>
    <label>Previous Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Address_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Previous_Address_PostalCode__c</fullName>
    <label>Previous Address PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Address_Province__c.field-meta.xml
<CustomField>
    <fullName>Previous_Address_Province__c</fullName>
    <label>Previous Address Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Previous_Address_Street_Name__c</fullName>
    <label>Previous  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Address_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Address_Street_Number__c</fullName>
    <label>Previous Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employer_City__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employer_City__c</fullName>
    <label>Previous Employer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employer_Name__c</fullName>
    <label>Previous Employer Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employer_Province__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employer_Province__c</fullName>
    <label>Previous Employer State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employer_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employer_Street_Name__c</fullName>
    <label>Previous Employer Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employer_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employer_Street_Number__c</fullName>
    <label>Previous Employer Address 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employment_Months__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Months__c</fullName>
    <label>Previous Employment Months</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Employment_Years__c.field-meta.xml
<CustomField>
    <fullName>Previous_Employment_Years__c</fullName>
    <label>Previous Employment Years</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Gross_Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Previous_Gross_Monthly_Income__c</fullName>
    <label>Previous Gross Monthly Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Requested_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Requested_Credit_Limit__c</fullName>
    <label>Requested Credit Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/SIN__c.field-meta.xml
<CustomField>
    <fullName>SIN__c</fullName>
    <label>SIN</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Years_At_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Years_At_Permanent_Address__c</fullName>
    <label>Years At Permanent Address</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Years_At_Previous_Address__c.field-meta.xml
<CustomField>
    <fullName>Years_At_Previous_Address__c</fullName>
    <label>Years At Previous Address</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/Application_Form_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Form Settings</label>
</CustomObject>

force-app/main/default/objects/Application_Form_Settings__c/fields/Power_Curve_Password__c.field-meta.xml
<CustomField>
    <fullName>Power_Curve_Password__c</fullName>
    <label>Power Curve Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/fields/Power_Curve_Username__c.field-meta.xml
<CustomField>
    <fullName>Power_Curve_Username__c</fullName>
    <label>Power Curve Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/fields/Power_Curve_Web_Service_URL__c.field-meta.xml
<CustomField>
    <fullName>Power_Curve_Web_Service_URL__c</fullName>
    <label>Power Curve Web Service URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/fields/Site_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Profile_Id__c</fullName>
    <label>Site Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUserVerificationErrorController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of trac_UserVerificationErrorController
 *  @author : A5E Consulting
 *  @date : 05/11/2016
 *
 *  Change History:
 *
 *  Developer       Date          Description
 *  ------------------------------------------------------------------------------------------------
 *
 *  A5E Consulting 05/11/2016     Class created
 *  A5E Consulting 05/11/2016     Test Methods added
 
 *************************************************************************************************/
//@isTest this class is private
public class TestUserVerificationErrorController {
    
   /* private static Application_Form_Settings__c afSettings;
    private static Application__c appln;
    
        
    static testMethod void testVerificationErrorController() {
        
        init();
        
        ApexPages.currentPage().getParameters().put('id', appln.Id);
        ApexPages.currentPage().getParameters().put('errorMessage', 'TechnicalIssue');
        
        Test.startTest();
            System.Test.setMock(HttpCalloutMock.class, PowerCurveTestUtilities.getMockAcceptResponse());
            trac_UserVerificationErrorController cntrl = new trac_UserVerificationErrorController();
        Test.stopTest();
        
    }    

    static void init() {
        
        afSettings = new Application_Form_Settings__c(
            Power_Curve_Web_Service_URL__c = PowerCurveTestUtilities.Power_Curve_Web_Service_URL,
            Power_Curve_Username__c = PowerCurveTestUtilities.Power_Curve_Username, 
            Power_Curve_Password__c = PowerCurveTestUtilities.Power_Curve_Password, 
            Site_Profile_Id__c = '00eK0000000MDqzIAG'
        );
        insert afSettings;
        
        insertTestData();
        initPageRef();
    }
    
    static void insertTestData() {
        
        Account p = new Account(
            FirstName = 'Rob',
            LastName = 'Johnson',
            PersonEmail = 'rj@test.com' 
        );
        insert p;
        
        appln = new Application__c(
            Customer__c = p.Id,
            Salutation__c = 'Mr.', 
            First_Name__c = 'Rob', 
            Last_Name__c = 'Johnson', 
            Gender__c = 'Male',
            SIN__c = '123456789',
            Requested_Credit_Limit__c = 4500,
            Birth_Date__c = Date.today().addYears(-25), 
            Current_BKCP__c = false, 
            Marital_Status__c = 'Single', 
            Home_Phone__c = '416-555-1234', 
            Work_Phone__c = '416-555-4567', 
            
            Permanent_Address_Street_Number__c = '123', 
            Permanent_Address_Street_Name__c = 'Current St.', 
            Permanent_Address_City__c = 'Toronto', 
            Permanent_Address_Province__c = 'ON', 
            Permanent_Address_PostalCode__c = 'A1A 1A1', 
            Years_At_Permanent_Address__c = 0, 
            Months_At_Permanent_Address__c = 6, 
            Home_Owner__c = 'Rent', 
            Housing_Costs__c = 1000,
            
            Previous_Address_Street_Number__c = '456', 
            Previous_Address_Street_Name__c = 'Previous St.', 
            Previous_Address_City__c = 'Toronto', 
            Previous_Address_Province__c = 'ON', 
            Previous_Address_PostalCode__c = 'P1P 1P1', 
            Years_At_Previous_Address__c = 5, 
            Months_At_Previous_Address__c = 8, 
            
            Employment_Status__c = 'Full-time', 
            Employer_Name__c = 'ACME Co.', 
            Employment_Years__c = 0, 
            Employment_Months__c = 8, 
            Gross_Monthly_Income__c = 3000, 
            Employer_Street_Number__c = '1212', 
            Employer_Street_Name__c = 'Main St.', 
            Employer_City__c = 'Toronto', 
            Employer_Province__c = 'ON', 
            Employer_PostalCode__c = 'M2M 2M2',
            Employer_Phone__c = '416-555-4567',
            
            Previous_Employer_Name__c = 'ABC Computers', 
            Previous_Employment_Years__c = 4, 
            Previous_Employment_Months__c = 6, 
            Previous_Gross_Monthly_Income__c = 2000, 
            Previous_Employer_Street_Number__c = '4545', 
            Previous_Employer_Street_Name__c = 'Front St.', 
            Previous_Employer_City__c = 'Toronto', 
            Previous_Employer_Province__c = 'ON', 
            Previous_Employer_PostalCode__c = 'F2F 2F2',
            Loan_Type__c = 'Affirm Financial MasterCard',
            Authentication_Result__c = 'Incomplete',
            Authentication_Choice__c = 'Error-TechnicalIssue'
        );
        insert appln;              
    }
    
    static void initPageRef() {
        PageReference pageRef = Page.UserVerificationError;
        Test.setCurrentPage(pageRef);
    }     */
}