force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Approved</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
            <value>
                <fullName>Manually Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <label>Permanent  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Configuration_Settings__c/Application_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Email_Customer_Settings__c/Email_Customer_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email Customer Settings</label>
</CustomObject>

force-app/main/default/objects/Email_Customer_Settings__c/fields/Email_Templates__c.field-meta.xml
<CustomField>
    <fullName>Email_Templates__c</fullName>
    <description>List of email template Ids</description>
    <label>Email Templates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEmailCustomerController.cls
/**************************************************************************************************
 *
 *  Class:   TestEmailCustomerController
 *
 *  @description : This class contains unit tests for send email customer for Application and attachments
 *  @author : A5E Consulting
 *  @date : 11/22/2020
 * 
 *************************************************************************************************/

@isTest(seeAllData = false)
public class TestEmailCustomerController {
    @testSetup 
     static void testData() {
        Application_Configuration_Settings__c appConfig = TestRecordsFactory.createApplicationMetadata();
        
        User adminUSer = TestRecordsFactory.createAdminUser();        
        
        TestRecordsFactory.TestAccountWrapper accntWrapper = new TestRecordsFactory.TestAccountWrapper();
        accntWrapper.firstName = 'first';
        accntWrapper.lastName = 'last';
        accntWrapper.email = 'testuser@testOrg.com';

        // Person Account
        Account accnt = TestRecordsFactory.createAccountRecordAndInsert(accntWrapper, false);
        accnt.Active__c = 'Yes';

        Account accntInvalid = TestRecordsFactory.createAccountRecordAndInsert(accntWrapper, false);
        accntInvalid.Active__c = 'No';
        accntInvalid.LastName = 'Invalid';
        accntInvalid.Communication_Preference__pc = 'Fax';
        accntInvalid.Fax='123-567';
        
        System.runAs(adminUSer){
            insert appConfig;
            insert accnt;
            insert accntInvalid;
        }

        TestRecordsFactory.TestApplicationWrapper applnWrapper = new TestRecordsFactory.TestApplicationWrapper();
        applnWrapper.name = 'Mock App 1';
        applnWrapper.firstName = 'firstName1';
        applnWrapper.lastName = 'lastName1';
        applnWrapper.email = 'testuser1@testOrg.com';                
        Application__c appln1 = TestRecordsFactory.createApplicationRecordAndInsert(applnWrapper, false);
        appln1.decision__c = 'Approved';
        appln1.Application_Status__c  = 'CC Creation';
        appln1.customer__c = accnt.id;
        appln1.Permanent_Address_Street_Name__c = 'Old Street';
        appln1.Customer__c = accnt.Id;
        
        System.runAs(adminUSer){
            insert appln1;
            TestRecordsFactory.attchmentCreate(appln1, 'description');
            EmailTemplate emailTemplate1 = TestRecordsFactory.createEmailTemplateWithoutHeader();
            EmailTemplate emailTemplate2 = TestRecordsFactory.createEmailTemplateWithHeader();
            insert emailTemplate1;
            insert emailTemplate2;

            Email_Customer_Settings__c poc = TestRecordsFactory.createPOCSetting();
            poc.Email_Templates__c = emailTemplate1.Id+','+emailTemplate2.Id;
            insert poc;
        }
     }

     static testMethod void sendEmailTestCheck(){
        Application__c appln = [SELECT Id FROM Application__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('Id', appln.Id);

        EmailCustomerController obj = new EmailCustomerController();
        obj.sendEmail();
     }

     static testMethod void testCheckEligibleCustomer(){
        Account acc = [SELECT Id FROM Account WHERE LastName = 'Invalid'];
        Application__c appln = [SELECT Id, Customer__c FROM Application__c LIMIT 1];
        appln.Customer__c = acc.Id;
        update appln;
        Attachment att = [SELECT Id, Description FROM Attachment WHERE ParentId =: appln.Id];
        ApexPages.currentPage().getParameters().put('Id', appln.Id);

        EmailCustomerController obj = new EmailCustomerController();
        obj.mySelectedAtt.add(att.Id);
        obj.sendEmail();

        att.Description = 'Account Statement';
        update att;
        obj.sendEmail();


     }


     static testMethod void testCheckEligibleCustomerInvalid(){
        Account acc = [SELECT Id FROM Account WHERE LastName = 'Invalid'];
        Application__c appln = [SELECT Id, Customer__c FROM Application__c LIMIT 1];

        Attachment att = [SELECT Id, Description FROM Attachment WHERE ParentId =: appln.Id];
        ApexPages.currentPage().getParameters().put('Id', appln.Id);

        EmailCustomerController obj = new EmailCustomerController();
        
        obj.toEmail = 'test@test.com;';
        obj.attachmentSelected = att.Id;
        obj.attachmentSelected();
        obj.mySelectedAtt.add(att.Id);
        obj.sendEmail();
        obj.attachmentRemoved();
        att.Description='Customer Document';
        update att;
        obj.sendEmail();
     }
     
}