force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the application that sourced this account</description>
    <inlineHelpText>A link to the application that sourced this account</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDeleteCustomersController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of DeleteCustomersController
 *  @author : A5E Consulting
 *  @date : 03/08/2016
 *
 *  Change History:
 *
 *  Developer       Date          Description
 *  ------------------------------------------------------------------------------------------------
 *
 *  A5E Consulting 03/08/2016     Initial Development
 
 *************************************************************************************************/
@isTest
public class TestDeleteCustomersController{
    
    static testmethod void testAuditLogCleaner(){   
        
        //Create Test Records        
        createCustomertWithNoApplicationNoProduct();
        createCustomertWithOneApplication(); 
        createCustomertWithOneProduct();
        createCustomertWithOneApplicationOneProduct();
                       
        //Records before cleanup
        List<Account> customersBefore = [Select id from Account];
        System.assertEquals(4,customersBefore.size());
        
        //Call Controller method
        DeleteCustomersController deleteCustomerCntrl = new DeleteCustomersController();
        deleteCustomerCntrl.deleteCustomers();
        
        //Verify Test results
        List<Account> customersAfter = [Select id from Account];
        System.assertEquals(3,customersAfter.size());        
    }
    
    
    public static void createCustomertWithOneApplication() { 
        Account acc = new Account(FirstName='Mark',LastName='Vanpee');
        insert acc;
        Application__c app = new Application__c(Name='AFITest1',Customer__C=acc.id);        
        insert app;

    }
    
    public static void createCustomertWithOneProduct() { 
        Account acc = new Account(FirstName='Akbar',LastName='Galmani');
        insert acc;        
        Product__c prod = new Product__c(Name='ProductTest1',Customer__C=acc.id);
        insert prod;
    }
    
    public static void createCustomertWithOneApplicationOneProduct() { 
        Account acc = new Account(FirstName='Ameya',LastName='Birje');
        insert acc;
        Application__c app = new Application__c(Name='AFITest2',Customer__C=acc.id);
        insert app;        
        Product__c prod = new Product__c(Name='ProductTest2',Customer__C=acc.id);
        insert prod;		
    }
    
    public static void createCustomertWithNoApplicationNoProduct() { 
        Account acc = new Account(FirstName='John',LastName='Sean');
        insert acc;     

    }   
}