force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DecisionWebService.cls
/**************************************************************************************************
*
*  Class:   DecisionWebService
*
*  @description : This class is integration layer for the Decision web service
*  @author : A5E Consulting
*  @date : 11/12/2020   
*
*************************************************************************************************/
public with sharing class DecisionWebService {
    public static Application__c getDecision(Application__c app){
        string jsonResponse = '{ "approvedAmount": 1456.00 ,'+
                                '"interestRate":1.24}';
            DecisionWrapper decision = (DecisionWrapper) System.JSON.deserialize(jsonResponse, DecisionWrapper.class);
            app.Approved_Amount__c = decision.approvedAmount;
            app.Interest_Rate__c = decision.interestRate;
        
        return app;
    }

    public class DecisionWrapper{
        public Decimal approvedAmount;
        public Decimal interestRate;
    }
}