force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Email_Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Email_Auth_Token__c</fullName>
    <label>Email Auth Token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Email_Authentication_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Authentication_Status__c</fullName>
    <inlineHelpText>Field is blank until email is manually sent to Applicant for Auto Authentication</inlineHelpText>
    <label>Email Authentication Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Form_Settings__c/Application_Form_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Form Settings</label>
</CustomObject>

force-app/main/default/classes/ApplicationAuthenticationController.cls
public with sharing class ApplicationAuthenticationController {

    public Application_Form_Settings__c appFormSettings {get;set;}
    public Application__c application {get;set;}
    public String applicationId {get;set;}
    public Boolean emailAuthPass {get;set;}
    
    public ApplicationAuthenticationController () {
        
        appFormSettings = Application_Form_Settings__c.getOrgDefaults(); 
        
        String emailToken = ApexPages.currentPage().getParameters().get('et');
        
        if (emailToken != null) {
            application = getApplicationByEmailToken(emailToken);
        
            if (application != null) {              
                emailAuthPass = true;               
            } 
            else {
                emailAuthPass = false;
            }
            
        } else {
            emailAuthPass = false;
        }           
    }
    
    //Gets Application with given email token if exists
    public Application__c getApplicationByEmailToken(String et) {
        List<Application__c> applications = [SELECT Id FROM Application__c WHERE Email_Auth_Token__c =: et];
    
        return (applications.size() > 0) ? applications[0] : null;
    }
    
    //Send email to initiate Email Authentication
    public void emailAuthenticateComplete(){
        if(emailAuthPass){
            application.Email_Authentication_Status__c = 'Applicant Authenticated';
            update application;
        }
    }
    
}