force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the application that sourced this account</description>
    <inlineHelpText>A link to the application that sourced this account</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHandler.cls
/**************************************************************************************************
*
*  Trigger:   
*
*  @description : This is a Trigger Handler Class for Attachment object 
*  @author : A5E Consulting
*  @date : 10/06/2016
* 
*************************************************************************************************/

public class AttachmentTriggerHandler{
    
    //Handle Befor Delete
    public static void handleBeforeDelete(List<Attachment> oldList){
        
        Profile profileInfo = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() limit 1];
        if('System Administrator' != profileInfo.Name && 'CFG - Application Admin' != profileInfo.Name ){
            for(Attachment attach : oldList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Application__C.sObjectType || 
                       attach.ParentId.getSObjectType() == Product__c.sObjectType ||
                       attach.ParentId.getSObjectType() == Funding_Batch__c.sObjectType ){
                           attach.ParentId.addError('You can not Delete an Attachment from Application, Product and Funding Batch Records');
                       }
                }
            }
        }
    }
    
    //Handle Befor Update
    public static void handleBeforeEdit(List<Attachment> newList){
        
        Profile profileInfo = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() limit 1];
        if('System Administrator' != profileInfo.Name && 'CFG - Application Admin' != profileInfo.Name ){
            for(Attachment attach : newList){
                if (attach.ParentId != null){
                    if(attach.ParentId.getSObjectType() == Funding_Batch__c.sObjectType ){
                           attach.ParentId.addError('You can not Edit an Attachment from Funding Batch Records');
                       }
                }
            }
        }
    }
}