force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Approved</fullName>
            </value>
            <value>
                <fullName>System Declined</fullName>
            </value>
            <value>
                <fullName>Analyst Approved</fullName>
            </value>
            <value>
                <fullName>Analyst Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Manually Approved</fullName>
            </value>
            <value>
                <fullName>Manually Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Permanent_Address_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address_Street_Name__c</fullName>
    <label>Permanent  Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAttachmentClass.cls
/**************************************************************************************************
 *
 *  Class:   TestAttachmentClass
 *
 *  @description : This is a testclass.
 *  @author : A5E Consulting
 *  @date : 11/23/2020
 *  
 *************************************************************************************************/
@isTest
public class TestAttachmentClass {

    @isTest public static void testFileUploads()
    {
        TestRecordsFactory.TestAccountWrapper accntWrapper = new TestRecordsFactory.TestAccountWrapper();
        accntWrapper.firstName = 'first';
        accntWrapper.lastName = 'last';
        accntWrapper.email = 'testuser@testOrg.com';

        // Person Account
        Account accnt = TestRecordsFactory.createAccountRecordAndInsert(accntWrapper, false);
        accnt.Active__c = 'Yes';
        insert accnt;

        TestRecordsFactory.TestApplicationWrapper applnWrapper = new TestRecordsFactory.TestApplicationWrapper();
        applnWrapper.name = 'Mock App 1';
        applnWrapper.firstName = 'firstName1';
        applnWrapper.lastName = 'lastName1';
        applnWrapper.email = 'testuser1@testOrg.com';  

        Application__c appln1 = TestRecordsFactory.createApplicationRecordAndInsert(applnWrapper, false);
        appln1.decision__c = 'Approved';
        appln1.Application_Status__c  = 'CC Creation';
        appln1.customer__c = accnt.id;
        appln1.Permanent_Address_Street_Name__c = 'Old Street';
        appln1.Customer__c = accnt.Id;
        insert appln1;

        //contenVersion record creation
        String contentBody = 'This is a test string';
        ContentVersion contentVersion = TestRecordsFactory.createContentVersion(contentBody);
        contentVersion.Title = 'TestFile';
        contentVersion.PathOnClient= 'ionicLogo.png';
        insert contentVersion;

        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion.Id].ContentDocumentId;
        ContentDocument contentDoc = new ContentDocument(Id = conDocId, Description = '01-01-2020');
        update contentDoc;
        //ContentDocumentLink record Creation
        ContentDocumentLink cDe = TestRecordsFactory.createContentDocumentLink(conDocId, appln1.Id);
        insert cDe;

        //Calling Apex methods
        AttachmentClass.getAttachment(appln1.id);
        AttachmentClass.getPickListValuesIntoList();
        AttachmentClass.monthList();
        AttachmentClass.yearList();
    }
}