force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Canaccede_API_User__c.field-meta.xml
<CustomField>
    <fullName>Canaccede_API_User__c</fullName>
    <label>Canaccede API User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Load_Customer_Data__c.field-meta.xml
<CustomField>
    <fullName>Load_Customer_Data__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Load Customer Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Before_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Before_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To run or not to run Product Before Trigger</description>
    <inlineHelpText>To run or not to run Product Before Trigger</inlineHelpText>
    <label>Run Product Before Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Product Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Validation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Validation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Product Validation Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Address_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Address_Last_Changed_Date__c</fullName>
    <description>The date the customer&apos;s address last changed in the system of record</description>
    <inlineHelpText>The date the customer&apos;s address last changed in the system of record</inlineHelpText>
    <label>Address Last Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <description>The primary account holder&apos;s address line 1</description>
    <inlineHelpText>The primary account holder&apos;s address line 1</inlineHelpText>
    <label>Address Line1</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The primary account holder&apos;s address city</description>
    <inlineHelpText>The primary account holder&apos;s address city</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The date this account was closed</description>
    <inlineHelpText>The date this account was closed</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>The primary account holder&apos;s date of birth</description>
    <inlineHelpText>The primary account holder&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>FDR:  The Internal Status code of this account
Megasys: The InternalStatus of the loan account</description>
    <inlineHelpText>FDR:  The Internal Status code of this account
Megasys: The InternalStatus of the loan account</inlineHelpText>
    <label>Internal Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>The primary account holder&apos;s last name</description>
    <inlineHelpText>The primary account holder&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <description>The date that the next payment is due</description>
    <inlineHelpText>The date that the next payment is due</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Setup_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Setup_Status__c</fullName>
    <description>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</description>
    <inlineHelpText>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</inlineHelpText>
    <label>Payment Setup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Home__c.field-meta.xml
<CustomField>
    <fullName>Phone_Home__c</fullName>
    <description>The primary account holder&apos;s home phone number</description>
    <inlineHelpText>The primary account holder&apos;s home phone number</inlineHelpText>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Other__c.field-meta.xml
<CustomField>
    <fullName>Phone_Other__c</fullName>
    <description>Customer Phone Other</description>
    <inlineHelpText>Customer Phone Other</inlineHelpText>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Phone_Work__c.field-meta.xml
<CustomField>
    <fullName>Phone_Work__c</fullName>
    <description>Customer Phone Work</description>
    <inlineHelpText>Customer Phone Work</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Requested_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Close_Date__c</fullName>
    <description>The close date on this account as requested by the customer</description>
    <inlineHelpText>The close date on this account as requested by the customer</inlineHelpText>
    <label>Requested Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The primary account holder&apos;s address province</description>
    <inlineHelpText>The primary account holder&apos;s address province</inlineHelpText>
    <label>Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The primary account holder&apos;s address postal code</description>
    <inlineHelpText>The primary account holder&apos;s address postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestProductTriggerHandler.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of ProductTriggerHandler
 *  @author : A5E Consulting
 *  @date : 10/14/2016
 * 
 *************************************************************************************************/
@isTest 
private class TestProductTriggerHandler {
    
    //Initialize Custom Settings
    static {
        
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.Run_Product_Validation_Trigger__c = true;
        loanSettings.Run_Product_Trigger__c = true;
        loanSettings.Run_Product_Before_Trigger__c = true;
        loanSettings.Load_Customer_Data__c = true;
        loanSettings.Canaccede_API_User__c = 'abc@xyz.com';
        insert loanSettings;         
    }
    
    //Test Before Update
    static testMethod void productBeforeUpdateTest(){
        
        Product__c prod = new Product__c();
        
        prod.name = '12345';
        prod.Payment_Setup_Status__c = 'Automated';
        prod.Funding_Status__c = 'Pending';
        prod.Funding_Type__c = 'Automated';
        prod.Disbursement_Amount__c = 2000.00;
        
        insert prod;
        
        Product__c prod1 = new Product__c();
        prod1.Payment_Setup_Status__c = 'Automated';
        prod1.Funding_Status__c = 'Pending';
        prod1.Funding_Type__c = 'Automated';
        prod1.Disbursement_Amount__c = 1000.00;
        
        insert prod1;
        
        List<Product__c> prodList = new List<Product__c>();
        prodList.add(prod);
        
        prod.Disbursement_Amount__c = 1000.00;
        update prod;
        
        Map<ID, Product__c> prodMap = new Map<ID, Product__c>();
        prodMap.put(prod.id, prod);
        
        ProductTriggerHandler.handleBeforeUpdate(prodList, prodMap);
        update prod;        
    }
    
    //Test Before Insert
    static testMethod void productBeforeInsertTest(){
        
        Id recordTypeId = Utilities.getProductRecordType('Megasys');
        
        List<Product__c> prodList = new List<Product__c>();
        Product__c prod = new Product__c();        
        prod.name = 'Prod1';
        prod.recordTypeId = recordTypeId;
        prod.Phone_Home__c = '12345678999';
        prod.Phone_Other__c = '8974563214';
        prod.Phone_Work__c = '27896541236';
        prod.Requested_Close_Date__c = null;
        prod.Closed_Date__c = null;
        prod.Payment_Due_Date__c = System.Today().addDays(-10);
        prod.Internal_Status__c = 'Active';
        prodList.add(prod);
        
        prod = new Product__c();        
        prod.name = 'Prod2';
        prod.recordTypeId = recordTypeId;
        prod.Phone_Home__c = '12345678999';
        prod.Phone_Other__c = '8974563214';
        prod.Phone_Work__c = '27896541236';
        prod.Requested_Close_Date__c = null;
        prod.Closed_Date__c = null;
        prod.Payment_Due_Date__c = System.Today().addDays(-190);
        prod.Internal_Status__c = 'Active';
        prodList.add(prod);
        
        prod = new Product__c();        
        prod.name = 'Prod2';
        prod.recordTypeId = recordTypeId;
        prod.Phone_Home__c = '12345678999';
        prod.Phone_Other__c = '8974563214';
        prod.Phone_Work__c = '27896541236';
        prod.Requested_Close_Date__c = null;
        prod.Closed_Date__c = null;
        prod.Payment_Due_Date__c = System.Today().addDays(20);
        prod.Internal_Status__c = 'Active';
        prodList.add(prod);
        
        prod = new Product__c();        
        prod.name = 'Prod3';
        prod.recordTypeId = recordTypeId;
        prod.Phone_Home__c = '12345678999';
        prod.Phone_Other__c = '8974563214';
        prod.Phone_Work__c = '27896541236';
        prod.Requested_Close_Date__c = null;
        prod.Closed_Date__c = System.Today().addDays(-50);
        prod.Payment_Due_Date__c = System.Today().addDays(-190);
        prod.Internal_Status__c = 'Active';
        prodList.add(prod);
        
        prod = new Product__c();
        prod.recordTypeId = recordTypeId;
        prod.name = 'Prod4';
        prod.Phone_Home__c = '55345678999';
        prod.Phone_Other__c = '8774563214';
        prod.Phone_Work__c = null;
        prod.Requested_Close_Date__c = System.Today();
        prodList.add(prod);

        prod = new Product__c();
        prod.recordTypeId = recordTypeId;
        prod.name = 'Prod5';
        prod.Phone_Home__c = null;
        prod.Phone_Other__c = null;
        prod.Phone_Work__c = null;
        prod.Requested_Close_Date__c = System.Today().addYears(-50);
        prodList.add(prod);
        
        ProductTriggerHandler.handleBeforeInsert(prodList);
    }
    
    //Test After Insert Update
    static testMethod void productAfterInsertUpdateTest(){
        Account customer = new Account(FirstName = 'FirstName', LastName = 'Last Name', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Salesforce').getRecordTypeId());
        insert customer;

        Account customer1 = new Account(FirstName = 'FirstName', LastName = 'Last Name', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Salesforce').getRecordTypeId());
        insert customer1;

        Product__c prod = new Product__c(First_Name__c = 'ProdFirstName', Last_Name__c = 'ProdLastName', Customer__c = customer.Id, Source_System__c ='FDR');

        List<Product__c> prodList = new List<Product__c>();
        prodList.add(prod);
        insert prodList;

        Map<ID, Product__c> prodMap = new Map<ID, Product__c>();
        prodMap.put(prod.id, prod);
        system.debug('calling 1 start'+prodList);
        ProductTriggerHandler.handleAferInsertUpdate(prodList, prodMap, true);
        system.debug('calling 1 end');
        Task tsk = new Task();
        tsk.WhatId = customer.Id;
        tsk.subject = 'Address Changes';
        tsk.OwnerId= UserInfo.getUserId();
        //insert tsk;
        
        Product__c prod1 = new Product__c(First_Name__c = 'ProdFirstName', Last_Name__c = 'ProdLastName', Customer__c = customer1.Id, Source_System__c ='FDR');
        insert prod1;
        prodList.add(prod1);
        prod.First_Name__c = 'changed';
        prod.Address_Last_Changed_Date__c = system.Today().addDays(-1);
        prod.Phone_Other__c = '123456';
        prod.Phone_Work__c = '123456';
        prod.Phone_Home__c = '123456';
        prod.Date_of_Birth__c = system.Today().addDays(-1);
        prod.State__c = 'CA';
        prod.Zip_Code__c = '123456';
        prod.City__c = 'NYC';
        prod.Address_Line1__c = 'Street 1';
        update prod;
        
        system.debug('calling 2 start'+prodList);
        ProductTriggerHandler.handleAferInsertUpdate(prodList, prodMap, true);
        system.debug('calling 2 end');
        prodMap.put(prod1.Id, prod);
        ProductTriggerHandler.handleAferInsertUpdate(prodList, prodMap, false);
    }
}