force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Megasys_Default_Fund_Code__c.field-meta.xml
<CustomField>
    <fullName>Megasys_Default_Fund_Code__c</fullName>
    <defaultValue>&quot;ACH&quot;</defaultValue>
    <label>Megasys Default Fund Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MegaSys_Payments__c/MegaSys_Payments__c.object-meta.xml
<CustomObject>
    <label>MegaSys Payments</label>
    <nameField>
        <displayFormat>MP-{0000}</displayFormat>
        <label>Megasys Payments</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MegaSys Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MegaSys_Payments__c/fields/No_Of_Records_Processed__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Records_Processed__c</fullName>
    <label>No Of Records Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>The unique token that represents the most recent funding transaction for this Product</description>
    <inlineHelpText>The unique token that represents the most recent funding transaction for this Product</inlineHelpText>
    <label>Payment System Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/MegaSys_Export_Date__c.field-meta.xml
<CustomField>
    <fullName>MegaSys_Export_Date__c</fullName>
    <label>MegaSys Export Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Actual Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Posted_To_VersaPay_On__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posted_To_VersaPay_On__c</fullName>
    <label>Payment Posted To VersaPay On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Posted_To_MegaSys__c.field-meta.xml
<CustomField>
    <fullName>Posted_To_MegaSys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Posted To MegaSys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Process_On__c.field-meta.xml
<CustomField>
    <fullName>Process_On__c</fullName>
    <description>Effective Payment Date</description>
    <label>Process On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>VersaPay Transaction current state</description>
    <label>VersaPay State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>VersaPay transaction identifier</description>
    <label>VersaPay Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MegasysPaymentCSVUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description :  MegasysPaymentCSVUtil: Utility class for creating CSV file.   
*  @author : A5E Consulting
*  @date : 14/11/2016   

*************************************************************************************************/
public Class MegasysPaymentCSVUtil{
    
    private static final String VERSAPAY_STATE = 'Completed';
    static List<VersaPay_Product_Payment__c> paymentSetupList;
    
    //Get Loan ReEngineering Custom Setting Record
    private static Loan_ReEngineering__c megaSysCS = Loan_ReEngineering__c.getOrgDefaults();
    
    //fetch All Eligible Versapay Product Payment Records for MegaSys
    public static List<VersaPay_Product_Payment__c> fecthVersaPayProdPayment(){
       
        paymentSetupList = [SELECT Id, Name, Product__r.Name, Product__r.PAP_Account_Number__c, 
        							Process_On__c,Payment_Posted_To_VersaPay_On__c, createdDate, 
                         			VersaPay_Token_Number__c, Payment_Amount__c     
                         			From VersaPay_Product_Payment__c 
                         			WHERE VersaPay_State__c=:VERSAPAY_STATE AND Posted_To_MegaSys__c =false
                         			AND Product__C != null];
        System.debug('paymentSetupList=='+paymentSetupList);
        return paymentSetupList;                                                                   
    }
    
    //fetch All Eligible Versapay Product Payment Records
    public static String createVersaPayCSV(){
        
        String finalversaPayCSV = '';
        String codeValue = '';
        
        
        for(VersaPay_Product_Payment__c verProPay : paymentSetupList){
        	System.debug('verProPay=='+verProPay);
        	
        	String paymentDate='';
	        if (verProPay.Process_On__c != null){
	        	paymentDate = convertDateToString(verProPay.Process_On__c);
	        }
	        else if (verProPay.Payment_Posted_To_VersaPay_On__c != null){
	        	paymentDate = convertDateToString(verProPay.Payment_Posted_To_VersaPay_On__c);
	        }  
	        else{
	        	paymentDate = convertDateToString(verProPay.createdDate);
	        } 
	         
            String versaPayCSV = checkComma(verProPay.Product__r.Name) + ',' //checkComma(verProPay.Product__r.PAP_Account_Number__c) + ',' 
                          + checkComma(String.valueOf(verProPay.Payment_Amount__c)) +','
                          //+ checkComma(convertDateToString(verProPay.Payment_Posted_To_VersaPay_On__c)) +',' 
                          //+ checkComma((verProPay.Process_On__c.format())) +','
                          + checkComma(paymentDate) +','
                          + checkComma(verProPay.VersaPay_Token_Number__c) +',' 
                          + checkComma(megaSysCS.Megasys_Default_Fund_Code__c) +','
                          + '' +''
                          + '\n'; 
            
            if(String.isNotBlank(versaPayCSV)){
                finalversaPayCSV += versaPayCSV;
            }              
        }
        
        return finalversaPayCSV;
    
    }
    
    //Create MegaSys Payment Update Record
    public static void createMegaSysPaymentRecord(String versaPayCSV){
        
        //TCIRecord
        MegaSys_Payments__c megaSysJobRecord = new MegaSys_Payments__c();
        megaSysJobRecord.No_Of_Records_Processed__c = paymentSetupList.Size();
        insert megaSysJobRecord;
        
        //MegaSys CSV Attachment
        Attachment attch = new Attachment();
        attch.Body = Blob.valueOf(versaPayCSV);
        attch.Name = 'MegaSys-Payment-CSV-' + convertDateToString(system.Now()) + '.csv';
        attch.ParentId = megaSysJobRecord.ID ; 
        insert attch;
    }
    
    //update Versapay Payment Setup records and return result
    public static Boolean updateVersaPayListRecords(){
        
        List<VersaPay_Product_Payment__c> paymentSetupUpdateList = New List<VersaPay_Product_Payment__c>();
        for(VersaPay_Product_Payment__c prodPay : paymentSetupList){
            
            prodPay.MegaSys_Export_Date__c = System.Now();
            prodPay.Posted_To_MegaSys__c = true;    
            paymentSetupUpdateList.add(prodPay);
        }
        
        update paymentSetupUpdateList;
        return true;
    }
    
    //Convert Date to String
    @testvisible
    private static String convertDateToString(DateTime dt){
        if(dt != null){
            //Date dte = dt.Date();
            //return String.valueof(dte.month()+'/'+dte.day()+'/'+dte.year());
            return (dt.formatGMT('MM/dd/yyyy'));
        }
        else{
            return '';
        }
    }
    
    //if value contains comma',' , append quote in trailing and heading
    @testvisible
    private static String checkComma(String str){

        if(String.isNotBlank(str) && str.contains(',')){
                return +' \"'+str+'\" ';
        }
        else{
            return str;
        }
    }
}