force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Attachment_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Attachment_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Attachment Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Product Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Validation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Validation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Product Validation Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Setup_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Setup_Status__c</fullName>
    <description>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</description>
    <inlineHelpText>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</inlineHelpText>
    <label>Payment Setup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAttachmentTriggerHandler.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of AttachmentTriggerHandler
 *  @author : A5E Consulting
 *  @date : 10/14/2016
 * 
 *************************************************************************************************/
@isTest 
Private class TestAttachmentTriggerHandler {
    
    static {
        
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.Run_Product_Validation_Trigger__c = true;
        loanSettings.Run_Product_Trigger__c = true;
        loanSettings.Run_Attachment_Trigger__c = true;
        insert loanSettings;         
    }
    
    static testMethod void attachmentTest(){
        
        //Run As CSR User
        User csrUser = TestRecordsFactory.getCSRUser();
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.Payment_Setup_Status__c = 'Automated';
        prod.Funding_Status__c = 'Pending';
        prod.Funding_Type__c = 'Automated';
        prod.Disbursement_Amount__c = 2000.00;
        insert prod;
        
        //Delete Attachment
        Attachment attchDelete = new Attachment();
        attchDelete.body = Blob.valueof('Test Body Delete');
        attchDelete.name = 'AttchDelete.pdf';
        attchDelete.parentId = prod.Id;
        insert attchDelete;
        List<Attachment> deleteList = new List<Attachment>();
        deleteList.add(attchDelete);
        System.runAs(csrUser) {
            AttachmentTriggerHandler.handleBeforeDelete(deleteList);
        }
                
        //Edit Attachment
        Attachment attchEdit = new Attachment();
        attchEdit.body = Blob.valueof('Test Body Edit');
        attchEdit.name = 'AttchEdit.pdf';
        attchEdit.parentId = prod.Id;
        insert attchEdit;
        List<Attachment> editList = new List<Attachment>();
        editList.add(attchEdit);        
        System.runAs(csrUser) {
            AttachmentTriggerHandler.handleBeforeEdit(editList);
        }
        
        delete attchDelete;
        
    } 
}