force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Signing_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Signing_Key__c</fullName>
    <description>VersaPay signing key, to verify the authenticity of a webhook notification</description>
    <label>VersaPay Signing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Webhook_Listener_URL__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Listener_URL__c</fullName>
    <label>Webhook Listener URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>The unique token that represents the most recent funding transaction for this Product</description>
    <inlineHelpText>The unique token that represents the most recent funding transaction for this Product</inlineHelpText>
    <label>Payment System Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>VersaPay transaction identifier</description>
    <label>VersaPay Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestVersaPayListnerUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : TestVersaPayListnerUtil for Versapay
*  @author : A5E Consulting
*  @date : 07/12/2016   

*************************************************************************************************/
@isTest
public class TestVersaPayListnerUtil{
    
     //Loan_ReEngineering__c Custom Settings
   static {
        
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.Webhook_Listener_URL__c = 'https://sb-affirmfinancial.cs22.force.com/services/apexrest/VersaPay';
        loanSettings.VersaPay_Signing_Key__c = 'xJ_hZrx1foK4JaDp8r5y';
        insert loanSettings;         
    }
    
    static testMethod void createPaymentTestMethod(){
        
        VersaPayListnerUtil.mapVersaPayState();
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        //prod.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        prod.Source_System__c = 'Megasys';     
        insert prod;
        
        //VersaPay_Product_Payment__c vpPay = new VersaPay_Product_Payment__c();
        //vpPay.Product__c = prod.id;
        //vpPay.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        //insert vpPay;
                
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'nsfed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_debit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '12345');
        //req.addParameter('unique_reference', '12345');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        
        insert prod;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'completed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_credit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductPaymentTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        
        insert prod;
        
        VersaPay_Product_Payment__c vpPay = new VersaPay_Product_Payment__c();
        vpPay.Product__c = prod.id;
        vpPay.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        insert vpPay;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'nsfed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_debit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductPaymentWithAccountTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';        
        insert prod;
        
        VersaPay_Product_Payment__c vpPay = new VersaPay_Product_Payment__c();
        vpPay.Product__c = prod.id;
        insert vpPay;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'nsfed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_debit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '12345');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductNSFEDTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        
        insert prod;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'nsfed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_credit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductCompletedNSFEDTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        
        insert prod;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'completed_but_nsfed');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_credit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
    
    static testMethod void updateProductErrorTestMethod(){
        
        Product__c prod = new Product__c();
        prod.name = '12345';
        prod.VersaPay_Token_Number__c = '1IXL5IX3D2IM';
        
        insert prod;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('Blob[0]');
        
        req.addParameter('amount_in_cents', '9175');
        req.addParameter('created_by_user','yujpqgPa_vscKNcz8Gkf');
        req.addParameter('email', '');
        req.addParameter('to_account', 'Canaccede');
        req.addParameter('to_fund', 'VersaPay Balance');
        req.addParameter('message', '');
        req.addParameter('process_on', '2016-11-20');
        req.addParameter('signature', 'chLtBK7zl7wBg8QCSceORjAyPydfUSj%2FpMOgaxlLgUI%3D%0A');
        req.addParameter('state', 'error');
        req.addParameter('type', 'transaction');
        req.addParameter('transaction_type', 'direct_credit');
        req.addParameter('token', '1IXL5IX3D2IM');
        req.addParameter('transaction_reference', '');
        req.addParameter('unique_reference', '');
        req.addParameter('link_url ', '');
        req.addParameter('auto_withdraw ', 'false');
        req.addParameter('auto_withdrawal_token', '');
        req.addParameter('from_account', 'KIMBERLY POND');
        req.addParameter('from_fund_token', 'BA9V6XLJD8TP');
                    
        req.requestURI = '/VersaPay';  
        req.httpMethod = 'POST';
        req.resourcePath = '/services/apexrest/VersaPay/*';
        
        RestContext.request = req;
        RestContext.response = res;
        
        VersaPayListner.listenWebHook();
    }
}