force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/File_Formats__c.field-meta.xml
<CustomField>
    <fullName>File_Formats__c</fullName>
    <label>File Formats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>The type of credit product this account represents</description>
    <inlineHelpText>The type of credit product this account represents</inlineHelpText>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPAPInformationProductController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This class contains unit tests for validating behavior of PAPInformationProductController 
*  @author : A5E Consulting
*  @date : 10/10/2016
*
*************************************************************************************************/

@isTest 
public class TestPAPInformationProductController{
    
   
    //Loan_ReEngineering__c Custom Settings
    static {
        
        Loan_ReEngineering__c loanSettings = new Loan_ReEngineering__c();
        loanSettings.File_Formats__c = '.pdf,.jpeg,.jpg';
        loanSettings.File_Size__c = 2097152;
        insert loanSettings;         
    }
    
    //Test Various Scenarios   
    static testMethod void paymentTest(){
        //Dummy Attachment
        Attachment attInvalid = new Attachment();
        attInvalid.body = Blob.valueof('Invalid File');
        attInvalid.name = 'invalid.xyz';
        
        //Dummy Attachment
        Attachment attValid = new Attachment();
        attValid.body = Blob.valueof('Valid File');
        attValid.name = 'valid.pdf';
        
        //Test Application
        Product__c app = new Product__c();
        app.loan_type__c  = 'Affirm Financial MasterCard';
        insert app;
        
        ApexPages.currentPage().getParameters().put('id', app.id);
        
        //Credit Card App
        PAPInformationProductController papInfoCtrl = new PAPInformationProductController();
        
        papInfoCtrl = new PAPInformationProductController();
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.productRec.PAP_Transit_Code__c = 'abc';
        papInfoCtrl.productRec.PAP_Account_Number__c = 'xyz';
        papInfoCtrl.productRec.PAP_Bank_Code__c = 'pqr';
        papInfoCtrl.updatePaymentMethod();
        
        //No File Attachment
        papInfoCtrl = new PAPInformationProductController();
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.productRec.PAP_Transit_Code__c = '123';
        papInfoCtrl.productRec.PAP_Account_Number__c = '456';
        papInfoCtrl.productRec.PAP_Bank_Code__c = '789';
        papInfoCtrl.updatePaymentMethod();
        
        //Invalid File Attachment 
        papInfoCtrl = new PAPInformationProductController();
        papInfoCtrl.papSupportDocument = attInvalid;
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.productRec.PAP_Transit_Code__c = '123';
        papInfoCtrl.productRec.PAP_Bank_Code__c = '456';
        papInfoCtrl.productRec.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        
        //Terms Conditionas not accepted
        papInfoCtrl = new PAPInformationProductController();
        papInfoCtrl.papSupportDocument = attValid;
        papInfoCtrl.acceptTermsCondition = false;
        papInfoCtrl.productRec.PAP_Transit_Code__c = '123';
        papInfoCtrl.productRec.PAP_Bank_Code__c = '456';
        papInfoCtrl.productRec.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        
        //All OK
        papInfoCtrl = new PAPInformationProductController();
        papInfoCtrl.papSupportDocument = attValid;
        papInfoCtrl.acceptTermsCondition = true;
        papInfoCtrl.productRec.PAP_Transit_Code__c = '123';
        papInfoCtrl.productRec.PAP_Bank_Code__c = '456';
        papInfoCtrl.productRec.PAP_Account_Number__c = '789';        
        papInfoCtrl.updatePaymentMethod();
        papInfoCtrl.navigatePrevious();
        
    }    
}