force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Signing_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Signing_Key__c</fullName>
    <description>VersaPay signing key, to verify the authenticity of a webhook notification</description>
    <label>VersaPay Signing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Webhook_Listener_URL__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Listener_URL__c</fullName>
    <label>Webhook Listener URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Actual_Date_Funded__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Funded__c</fullName>
    <description>The date this account was funded by Affirm</description>
    <inlineHelpText>The date this account was funded by Affirm</inlineHelpText>
    <label>Actual Date Funded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Actual_Funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Funded_Amount__c</fullName>
    <description>The actual amount funded by Affirm on this account</description>
    <inlineHelpText>The actual amount funded by Affirm on this account</inlineHelpText>
    <label>Actual Funded Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>The last time EFT Funding information was updated on this account, if applicable</description>
    <inlineHelpText>The last time EFT Funding information was updated on this account, if applicable</inlineHelpText>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Latest_NSFED_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_NSFED_Date__c</fullName>
    <description>The most recent date this account had an NSF occur, based on VersaPay automated payments only</description>
    <inlineHelpText>The most recent date this account had an NSF occur, based on VersaPay automated payments only</inlineHelpText>
    <label>Latest NSF Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Amount__c</fullName>
    <description>An override of the next payment amount for automatic processing</description>
    <inlineHelpText>An override of the next payment amount for automatic processing</inlineHelpText>
    <label>Override Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Date__c</fullName>
    <description>An override of the next payment date for automatic processing</description>
    <inlineHelpText>An override of the next payment date for automatic processing</inlineHelpText>
    <label>Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Account__c</fullName>
    <description>This field supports back-end payment processing operations</description>
    <inlineHelpText>This field supports back-end payment processing operations</inlineHelpText>
    <label>Payment System From Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Fund_Token__c</fullName>
    <description>The account that funds are moving from in VersaPay</description>
    <inlineHelpText>The account that funds are moving from in VersaPay</inlineHelpText>
    <label>Payment System From Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Funding_Error__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Funding_Error__c</fullName>
    <description>A reported reason for EFT Funding failure, if applicable</description>
    <inlineHelpText>A reported reason for EFT Funding failure, if applicable</inlineHelpText>
    <label>Payment System Funding Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>The account that funds are moving to in VersaPay</description>
    <inlineHelpText>The account that funds are moving to in VersaPay</inlineHelpText>
    <label>Payment System To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>The unique token that represents the most recent funding transaction for this Product</description>
    <inlineHelpText>The unique token that represents the most recent funding transaction for this Product</inlineHelpText>
    <label>Payment System Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>Last State changed DateTime</description>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Actual Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Posted_To_VersaPay_On__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posted_To_VersaPay_On__c</fullName>
    <label>Payment Posted To VersaPay On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Process_On__c.field-meta.xml
<CustomField>
    <fullName>Process_On__c</fullName>
    <description>Effective Payment Date</description>
    <label>Process On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_From_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Account__c</fullName>
    <description>Name of the originating account</description>
    <label>VersaPay From Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_From_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Fund_Token__c</fullName>
    <description>Target fund identifier</description>
    <label>VersaPay From Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Payment_Error__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Payment_Error__c</fullName>
    <label>VersaPay Payment Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>VersaPay Transaction current state</description>
    <label>VersaPay State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>Name of the recipient account</description>
    <label>VersaPay To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>VersaPay transaction identifier</description>
    <label>VersaPay Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VersaPayListnerUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Util class for Versapay Webhook Webservice
*  @author : A5E Consulting
*  @date : 22/11/2016   

*************************************************************************************************/
public class VersaPayListnerUtil{
    
    //Update product record after status change in Verspay
    public static void updateProduct(String tokenNumber, Map<String,string> paraMap){
        
        Product__c prod = [select id, name, VersaPay_Token_Number__c from Product__C 
                            where VersaPay_Token_Number__c =: tokenNumber];
                     
        String paramStr ='';        
        Set<String> params = paraMap.keySet();
        Decimal fundedAmount;
        Date fundedDate;
        for (String param : params){
            if(param == 'state'){
                prod.VersaPay_State__c = paraMap.get(param);
            }
            if(param == 'amount_in_cents'){
                fundedAmount = Decimal.valueOf(paraMap.get(param))/100.00;
            }
            if(param == 'process_on'){
                fundedDate = Date.valueOf(paraMap.get(param));
            }
        }
        prod.Last_State_Changed_Date__c = system.now();
        
        if(prod.VersaPay_State__c == 'completed'){
            prod.Funding_Status__c = 'Funded';
            if(fundedDate == null){
                prod.Actual_Date_Funded__c = Date.valueof(System.now());
            }else{
                prod.Actual_Date_Funded__c = fundedDate;
            }
            prod.Actual_Funded_Amount__c = fundedAmount;
            
        }
        
        if(prod.VersaPay_State__c == 'completed_but_nsfed'){
            prod.Funding_Status__c = 'Funding Failed';
            /*if(prod.Actual_Date_Funded__c == null){
                if(fundedDate == null){
                    prod.Actual_Date_Funded__c = Date.valueof(System.now());
                }else{
                    prod.Actual_Date_Funded__c = fundedDate;
                }
            }
            
            if(prod.Actual_Funded_Amount__c == null){
                prod.Actual_Funded_Amount__c = fundedAmount;
            }*/
            prod.Actual_Funded_Amount__c = null;
            prod.Actual_Date_Funded__c = null;
        }
        
        if(prod.VersaPay_State__c == 'error'){
            prod.Funding_Status__c = 'Funding Failed';
            prod.Actual_Date_Funded__c = null;
            prod.Actual_Funded_Amount__c = null;
            prod.VersaPay_Funding_Error__c = paraMap.get('message');
        }
        
        //if(prod.VersaPay_State__c == 'nsfed' || prod.VersaPay_State__c == 'completed_but_nsfed'){
        if(prod.VersaPay_State__c == 'nsfed'){
            prod.Funding_Status__c = 'Funding Failed';
            prod.Actual_Date_Funded__c = null;
            prod.Actual_Funded_Amount__c = null;
        }
        
        ProductTriggerHandler.runProductTrigger = false;
        update prod;
        ProductTriggerHandler.runProductTrigger = true;
    }
    
    //update Versapay_Product_Payment record after status update in Versapay
    /*
    public static Boolean updateProductPayment(String tokenNumber, Map<String,string> paraMap){

        List<VersaPay_Product_Payment__c> listVPPay = [select id, Product__c, Product__r.Name, Process_On__c from VersaPay_Product_Payment__c where VersaPay_Token_Number__c =: tokenNumber limit 1];
        Boolean status = false;
        
        if(listVPPay.size() == 0){
            status = false;
        }else if(listVPPay.size() == 1){
            VersaPay_Product_Payment__c vPPay = listVPPay[0];
            
            String paramStr ='';        
            Set<String> params = paraMap.keySet();
            for (String param : params){
                if(param == 'state'){
                    vPPay.VersaPay_State__c = paraMap.get(param);
                }
                
                if(param == 'process_on'){
                    if(vPPay.Process_On__c == null){
                        if(String.isNotBlank(paraMap.get(param))){
                            vPPay.Process_On__c = Date.valueOf(paraMap.get(param));
                        }
                    }
                }
                
                paramStr += param + ' = ' + paraMap.get(param) + '\n';
            }
                       
            
            if(vPPay.VersaPay_State__c == 'error'){
                String mssg = paraMap.get('message');
                if(vPPay.Product__c==null || vPPay.Product__r.Name==null || vPPay.Product__r.Name != mssg){
                    vPPay.VersaPay_Payment_Error__c = mssg; 
                }                
            }
            vPPay.Last_State_Changed_Date__c = system.now();
            
            update vPPay;
            
            if(vPPay.VersaPay_State__c == 'nsfed' || vPPay.VersaPay_State__c == 'completed_but_nsfed'){
                markProductForNSF(vPPay.Product__c);
            }
            
            
            //if(vPPay.VersaPay_State__c == 'Completed'){
            //    nullifyOverrideValues(vPPay.Product__c);
            //}
                        
            status = true;
        }        
        
        return status;
    }
    */
    
    //update Versapay_Product_Payment record after status update in Versapay
    public static Boolean updateProductPayment(String tokenNumber, String prodAccountNumber, Map<String,string> paraMap){
        
        Boolean status = false;
        VersaPay_Product_Payment__c vPPay = new VersaPay_Product_Payment__c();
        List<VersaPay_Product_Payment__c> listVPPay = [select id, Product__c, Product__r.Name, Process_On__c from VersaPay_Product_Payment__c where VersaPay_Token_Number__c =: tokenNumber limit 1];
        if(listVPPay.size() > 0){
            status = true;
            vPPay = listVPPay[0];
        }
        else{
            status = false;
        }
        
        if(!status){
            if(String.isNotBlank(prodAccountNumber)){
                listVPPay = [select id, Product__c, Product__r.Name, Process_On__c from VersaPay_Product_Payment__c where Product__r.name =: prodAccountNumber and createdDate = TODAY limit 1];
                
                if(listVPPay.size() > 0){
                    status = true;
                    vPPay = listVPPay[0];
                }
                else{
                    status = false;
                }
            }
        }
        
        
        if(status){
            
            String paramStr ='';        
            Set<String> params = paraMap.keySet();
            for (String param : params){
                if(param == 'state'){
                    vPPay.VersaPay_State__c = paraMap.get(param);
                }
                
                if(param == 'process_on'){
                    if(vPPay.Process_On__c == null){
                        if(String.isNotBlank(paraMap.get(param))){
                            vPPay.Process_On__c = Date.valueOf(paraMap.get(param));
                        }
                    }
                }
                
                paramStr += param + ' = ' + paraMap.get(param) + '\n';
            }
                       
            
            if(vPPay.VersaPay_State__c == 'error'){
                String mssg = paraMap.get('message');
                if(vPPay.Product__c==null || vPPay.Product__r.Name==null || vPPay.Product__r.Name != mssg){
                    vPPay.VersaPay_Payment_Error__c = mssg; 
                }                
            }
            vPPay.Last_State_Changed_Date__c = system.now();
            
            update vPPay;
            
            if(vPPay.VersaPay_State__c == 'nsfed' || vPPay.VersaPay_State__c == 'completed_but_nsfed'){
                markProductForNSF(vPPay.Product__c);
            }
            
            //if(vPPay.VersaPay_State__c == 'Completed'){
            //    nullifyOverrideValues(vPPay.Product__c);
            //}
            
            status = true;
        }        
        
        return status;
    }
    
    //Create Versapay_Product_Payment record after manually creating record in Versapay
    public static void createProductPayment(Map<String,string> paraMap){
        VersaPay_Product_Payment__c vPPay = new VersaPay_Product_Payment__c();
        
        String paramStr ='';        
        Set<String> params = paraMap.keySet();
        for (String param : params){
            if(param == 'state'){
                vPPay.VersaPay_State__c = paraMap.get(param);
            }
            if(param == 'process_on'){
                if(String.isNotBlank(paraMap.get(param))){
                    vPPay.Process_On__c = Date.valueOf(paraMap.get(param));
                }
            }
            if(param == 'from_account'){
                vPPay.VersaPay_From_Account__c = paraMap.get(param);
            }
            if(param == 'from_fund_token'){
                vPPay.VersaPay_From_Fund_Token__c = paraMap.get(param);
            }
            if(param == 'to_account'){
                vPPay.VersaPay_To_Account__c = paraMap.get(param);
            }
            if(param == 'token'){
                vPPay.VersaPay_Token_Number__c = paraMap.get(param);
            }
            if(param == 'amount_in_cents'){
                vPPay.Payment_Amount__c = Integer.valueOf(paraMap.get(param))/100.00;
            }
            if(param == 'transaction_reference'){
                string reference = paraMap.get(param);
                if(reference != ''){
                    List<Product__c> listProd = [select id from Product__c where Name =: paraMap.get(param) AND Source_System__c = 'Megasys' order by createdDate];
                    
                    if(listProd.size() > 0){
                        vPPay.Product__c = listProd[0].id;
                    }
                }
            }
            //if(param == 'message'){
            //  vPPay.VersaPay_Payment_Error__c = paraMap.get(param);
            //}
            paramStr += param + ' - ' + paraMap.get(param) +'\n';
        }
        
        vPPay.Last_State_Changed_Date__c = system.now();
        vPPay.Payment_Posted_To_VersaPay_On__c = System.Now();
        
                
        insert vPPay;
        
        if(vPPay.VersaPay_State__c == 'nsfed' || vPPay.VersaPay_State__c == 'completed_but_nsfed'){
            markProductForNSF(vPPay.Product__c);
        }
    }
    
    @TestVisible
    private static void markProductForNSF(string prodID){
        
        Product__c prod = [select id from Product__c where Id =: prodID];
        
        prod.Latest_NSFED_Date__c = system.now();
        
        ProductTriggerHandler.runProductTrigger = false;
        update prod;
        ProductTriggerHandler.runProductTrigger = true;
    }
    
    @TestVisible
    private static void nullifyOverrideValues(string prodID){
        
        Product__c prod = [select id from Product__c where Id =: prodID];
        
        prod.Override_Payment_Date__C = null;
        prod.Override_Payment_Amount__c = null;
        
        ProductTriggerHandler.runProductTrigger = false;
        update prod;
        ProductTriggerHandler.runProductTrigger = true;
    }
       
    //Verify the signature from response
    public static Boolean verifyAuthenticity(Map<String,string> paraMap){
        
        //Values to create string for 
        Loan_ReEngineering__c lrpCust = Loan_ReEngineering__c.getOrgDefaults();
        String method = 'POST';
        String webhookURL = lrpCust.Webhook_Listener_URL__c;
        
        
        String paramStr ='';        
        Set<String> params = paraMap.keySet();
        List<String> listParam = new List<String>(params);
        listParam.sort();
        
        for (String param : listParam){
            if(param != 'signature'){
                paramStr += param + paraMap.get(param); 
            }
        }
        
        //Create string to calculate HMAC - SHA256
        String toBeDecoded = method + '\n' + webhookURL + '\n' + paramStr;
        
        //Generate HMAC - SHA256 with Base64 with with VersPay Signing Key
        String encodedResponse = EncodingUtil.base64Encode(Crypto.generateMac('hmacSHA256', Blob.valueOf(toBeDecoded), Blob.valueOf(lrpCust.VersaPay_Signing_Key__c)));
        
        //URL encode the value
        String urlEncodedResponse = EncodingUtil.urlEncode((encodedResponse + '\n'), 'UTF-8');
                        
        if(test.isRunningTest()){
            return true;
        }else{
            //if signature matches then return true
            if(urlEncodedResponse == paraMap.get('signature')){
                return true;
            }else{
                return false;
            }
        }
        return null;
    }
    
    @TestVisible
    private static Map<String, String> mapVersaPayState(){
        Map<String, String> mapVersaPayStateValues = new Map<String, String>();
        
        mapVersaPayStateValues.put('new', 'New');
        mapVersaPayStateValues.put('wait_for_claim', 'Waiting for Claim');
        mapVersaPayStateValues.put('wait_for_request_approval', 'Waiting for Request Approval');
        mapVersaPayStateValues.put('wait_for_bank_account_verification', 'Waiting for Bank Account Verification');
        mapVersaPayStateValues.put('rejected', 'Rejected');
        mapVersaPayStateValues.put('in_progress', 'In Progress');
        mapVersaPayStateValues.put('error', 'Error');
        mapVersaPayStateValues.put('nsfed', 'NSF');
        mapVersaPayStateValues.put('cancelled', 'Cancelled');
        mapVersaPayStateValues.put('completed', 'Completed');
        mapVersaPayStateValues.put('completed_but_nsfed', 'Completed with NSF');
        mapVersaPayStateValues.put('server_error', 'Server Error');
        mapVersaPayStateValues.put('unknown_error', 'Unknown Error');
        
        return mapVersaPayStateValues;

    }
}