force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/fields/Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Released_Date__c</fullName>
    <label>Released Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Request_Timeout__c</fullName>
    <description>(milliseconds)</description>
    <label>Request Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key__c</fullName>
    <description>VersaPay Authentication Key</description>
    <label>VersaPay Auth Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key_Credit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key_Credit__c</fullName>
    <description>VersaPay Auth Key Credit</description>
    <label>VersaPay Auth Key Credit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key_Debit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key_Debit__c</fullName>
    <description>VersaPay Auth Key Debit</description>
    <label>VersaPay Auth Key Debit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token__c</fullName>
    <description>VersaPay Authentication Token</description>
    <label>VersaPay Auth Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token_Credit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token_Credit__c</fullName>
    <description>VersaPay Auth Token Credit</description>
    <label>VersaPay Auth Token Credit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token_Debit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token_Debit__c</fullName>
    <description>VersaPay Auth Token Debit</description>
    <label>VersaPay Auth Token Debit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_End_Point__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_End_Point__c</fullName>
    <description>VersaPay End Point for Callouts</description>
    <label>VersaPay End Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Signing_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Signing_Key__c</fullName>
    <description>VersaPay signing key, to verify the authenticity of a webhook notification</description>
    <label>VersaPay Signing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The date this account was closed</description>
    <inlineHelpText>The date this account was closed</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <description>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</description>
    <inlineHelpText>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</inlineHelpText>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Hold_Payments__c.field-meta.xml
<CustomField>
    <fullName>Hold_Payments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</description>
    <inlineHelpText>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</inlineHelpText>
    <label>Hold Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Amount__c</fullName>
    <description>An override of the next payment amount for automatic processing</description>
    <inlineHelpText>An override of the next payment amount for automatic processing</inlineHelpText>
    <label>Override Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Date__c</fullName>
    <description>An override of the next payment date for automatic processing</description>
    <inlineHelpText>An override of the next payment date for automatic processing</inlineHelpText>
    <label>Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Released_Date__c</fullName>
    <description>The date that account funds were delivered to the customer</description>
    <inlineHelpText>The date that account funds were delivered to the customer</inlineHelpText>
    <label>Payment Released Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Setup_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Setup_Status__c</fullName>
    <description>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</description>
    <inlineHelpText>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</inlineHelpText>
    <label>Payment Setup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>Pre-Filing Review</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry Received</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Filing Complete – No Further Action</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPaymentCreateBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : TestPaymentCreateBatch
*  @author : A5E Consulting
*  @date : 28/02/2017   

*************************************************************************************************/
@isTest(seeAllData = false)
public class TestPaymentCreateBatch {
    
    private static Loan_ReEngineering__c loanReCS;
    
    static testMethod void insertTestData(){
        
        //create LRP custom setting records
        createLRPCs();
        
        //create a product record that will be eligible for funding batch
        Product__c prod = createProduct('Automated');
        
        //create a funding batch record
        Funding_Batch__c batch = createFundingBatchRecord();
        
        //update product with Funding Batch record ID
        prod.Funding_Batch__c = batch.Id;
        prod.Override_Payment_Amount__c = 100;
        prod.Override_Payment_Date__c = System.today()+1;
        prod.Closed_Date__c = null;
        prod.Hold_Payments__c = false;
        prod.Funding_Status__c = 'Funded';
        prod.Source_System__c = 'Megasys';
        prod.Payment_Setup_Status__c = 'Automated' ;
        prod.External_Status_Current__c = 'Active';
        prod.Payment_Released_Date__c = System.Today()+2;
        prod.First_Payment_Date__c = System.today() + 2;
        prod.Payment_Amount__c  = 200;
        prod.VersaPay_State__c = 'Completed';
        update prod;
        
        //execute Funding Batch Class
        Database.executeBatch(new PaymentCreateBatch(), 1);
    }
    
    //create LRP custom setting records
    private static void createLRPCs(){
        
        loanReCS = New  Loan_ReEngineering__c();  
        loanReCS.Request_Timeout__c=60000;
        //loanReCS.VersaPay_Auth_Key__c='SjlnsdjKJ';
        //loanReCS.VersaPay_Auth_Token__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_Auth_Key_Credit__c='SjlnsdjKJ';
        loanReCS.VersaPay_Auth_Token_Credit__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_Auth_Key_Debit__c='SjlnsdjKJ';
        loanReCS.VersaPay_Auth_Token_Debit__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_End_Point__c='www.versapytest.com';
        loanReCS.VersaPay_Signing_Key__c='siging Key';
        
        insert loanReCS;
    }
    
      //create a product record that will be eligible for funding batch
    private static Product__c createProduct(string fundType){
        Product__c app = new Product__c();
        
        app.customer__c = createAccount().id;
        app.Product_Status__c = 'New';
        app.Funding_Amount__c = 1000.00;
        app.Loan_Process_Type__c = 'Traditional';
        app.Funding_Type__c = fundType;
        app.Funding_Status__c = 'Funded';
        app.Funding_Date__c = System.Today();
        app.Regular_Payment_Amount__c = 100.00;
        //app.SOR_Account_Number__c = '123456789120';
        //app.SOR_Primary_Account_Number__c = '4534535345345';
        app.PAP_Account_Number__c = '98745632';
        app.PAP_Transit_Code__c = '45';
        app.PAP_Bank_Code__c = '12';
        app.Loan_Type__c = 'Affirm Financial Term Loan';
        app.First_Payment_Date__c = system.today();
        app.Disbursement_Amount__c = 45;
        //app.SOR_External_ID__c = 'SFI123';
        app.Disbursement_Amount__c = 123;
        app.PAP_Bank_Code__c = '004';
        app.PAP_Transit_Code__c = '156';
        app.PAP_Account_Number__c = '123459';
        app.Hold_Payments__c = false;
        app.First_Payment_Date__c = System.today().addDays(1);
        insert app;
        return app; 
    }
    
     //create a funding batch recordcreateFundingBatchRecord
    private static Funding_Batch__c createFundingBatchRecord(){
    
        Funding_Batch__c batch = New Funding_Batch__c();
        batch.Released_Date__c = System.today();
        batch.Status__c = 'Pending';
        batch.Total_Funding_Amount__c = 123;
        batch.Total_Automated_Funding_Amount__c = 123;
        insert batch;
        
        return batch;
    }
    
    //create Account record
    private static Account createAccount(){
        Account p = new Account();
        
        p.Salutation = 'Mr.';
        p.FirstName = 'Asad';
        p.Middle_Name__pc = 'Full';
        p.LastName = 'Person';
        
        p.PersonMailingState = 'ON';
        p.PersonBirthdate = Date.newInstance(1983, 12, 2);
        p.Gender__pc = 'Male';
        p.Marital_Status__pc = 'Single';
        
        p.Employer_Province__pc = 'ON';
        p.Number_of_Dependants__pc = '0';
        p.Home_Owner__pc = 'Own';
        p.PersonMailingState = 'ON';
        
        p.PersonHomePhone = '1235551234';
        p.PersonEmail = 'asad.fullperson@test.com';
        p.SIN__pc = '123456789';
        p.PersonMobilePhone = '5551231234';
        p.Work_Phone__pc = '1112223333';
        
        p.Communication_Preference__pc = 'Email';
        p.Monthly_Home_Expense__pc = 2000;
        p.Monthly_Expense__pc = 500;
        
        p.PersonMailingStreet = '4 Glenora';
        p.PersonMailingCity = 'Brampton';
        p.PersonMailingPostalCode = 'L6Y4K5';
        
        p.Employer_Name__pc = 'Paper Empire';
        p.Employer_Phone__pc = '9991231234';
        p.Employer_Street_Name__pc = 'Brick Lane';
        p.Employer_Street_Number__pc = '4';
        p.Employer_City__pc = 'Brampton';
        p.Employer_Postal_Code__pc = 'L6Y4K4';
        p.Occupation__pc = 'Manager';
        p.Employment_Years__pc = 3;
        p.Employment_Months__pc = 10;
        p.Gross_Monthly_Income__pc = 5000;
        
        insert p;
        
        return p;
    }
    
    //parse direct_credit full response with 200 code
    static testMethod void responseFullDirectDebit(){
       insertTestData();
       Test.startTest();
       Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseFullDirectDebit,200));
       Test.stopTest(); 
    }
    
    //parse direct_credit Error response with 401 code
    static testMethod void responseErrorDirectDebit(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseErrorDirectCrdDbt,410));
        Test.stopTest();
    }

    //parse direct_credit Error response with 201 code
    static testMethod void responseErrorCodeDirectDebit(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseErrorDirectCrdDbt,200));
        Test.stopTest();
    } 
    
    //parse direct_debit Null XML response with 412 code
    static testMethod void responseNullCrdDet(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseNullDirectCrdDbt,412));
        Test.stopTest();
    } 
}