force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/fields/Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Released_Date__c</fullName>
    <label>Released Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Automated_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Automated_Funding_Amount__c</fullName>
    <description>Total Automated Funding Amount</description>
    <inlineHelpText>Total Automated Funding Amount</inlineHelpText>
    <label>Total Automated Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Funding_Amount__c</fullName>
    <description>Total Funding Amount</description>
    <inlineHelpText>Total Funding Amount</inlineHelpText>
    <label>Total Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Request_Timeout__c</fullName>
    <description>(milliseconds)</description>
    <label>Request Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key__c</fullName>
    <description>VersaPay Authentication Key</description>
    <label>VersaPay Auth Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key_Credit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key_Credit__c</fullName>
    <description>VersaPay Auth Key Credit</description>
    <label>VersaPay Auth Key Credit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Key_Debit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Key_Debit__c</fullName>
    <description>VersaPay Auth Key Debit</description>
    <label>VersaPay Auth Key Debit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token__c</fullName>
    <description>VersaPay Authentication Token</description>
    <label>VersaPay Auth Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token_Credit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token_Credit__c</fullName>
    <description>VersaPay Auth Token Credit</description>
    <label>VersaPay Auth Token Credit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Auth_Token_Debit__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Auth_Token_Debit__c</fullName>
    <description>VersaPay Auth Token Debit</description>
    <label>VersaPay Auth Token Debit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_End_Point__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_End_Point__c</fullName>
    <description>VersaPay End Point for Callouts</description>
    <label>VersaPay End Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/fields/VersaPay_Signing_Key__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Signing_Key__c</fullName>
    <description>VersaPay signing key, to verify the authenticity of a webhook notification</description>
    <label>VersaPay Signing Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Process_Type__c</fullName>
    <description>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</description>
    <inlineHelpText>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</inlineHelpText>
    <label>Loan Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Re-write</fullName>
            </value>
            <value>
                <fullName>RBO</fullName>
            </value>
            <value>
                <fullName>Consolidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>The type of credit product this account represents</description>
    <inlineHelpText>The type of credit product this account represents</inlineHelpText>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>Pre-Filing Review</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry Received</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Filing Complete – No Further Action</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestVersaPayFundingBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : VersaPay Funding Batch Test Class
*  @author : A5E Consulting
*  @date : 11/21/2016   

*************************************************************************************************/
@isTest
public class TestVersaPayFundingBatch{
    
    private static Loan_ReEngineering__c loanReCS;
    
    static testMethod void insertTestData(){
        
        //create LRP custom setting records
        createLRPCs();
        
        //create a product record that will be eligible for funding batch
        Product__c prod = createProduct('Automated');
        
        //create a funding batch record
        Funding_Batch__c batch = createFundingBatchRecord();
        
        //update product with Funding Batch record ID
        prod.Funding_Batch__c = batch.Id;
        update prod;
        
        //execute Funding Batch Class
        Database.executeBatch(new VersaPayFundingBatch(batch.Id), 1);
    }
    
    //parse direct_credit full response with 200 code
    static testMethod void responseFullDirectCredit(){
       insertTestData();
       Test.startTest();
       Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseFullDirectCredit,200));
       Test.stopTest(); 
    }
    
    //parse direct_credit Error response with 401 code
    static testMethod void responseErrorDirectCredit(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseErrorDirectCrdDbt,410));
        Test.stopTest();
    }

    //parse direct_credit Error response with 201 code
    static testMethod void responseErrorCodeDirectCredit(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseErrorDirectCrdDbt,200));
        Test.stopTest();
    }    
    
    //parse direct_credit Null XML response with 412 code
    static testMethod void responseNullCrdDet(){
        insertTestData();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new VersaPayWSUtilReqMockTest(VersaPayWSUtilReqMockTest.responseNullDirectCrdDbt,412));
        Test.stopTest();
    } 
    //create LRP custom setting records
    private static void createLRPCs(){
        
        loanReCS = New  Loan_ReEngineering__c();  
        loanReCS.Request_Timeout__c=60000;
        //loanReCS.VersaPay_Auth_Key__c='SjlnsdjKJ';
        //loanReCS.VersaPay_Auth_Token__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_Auth_Key_Credit__c='SjlnsdjKJ';
        loanReCS.VersaPay_Auth_Token_Credit__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_Auth_Key_Debit__c='SjlnsdjKJ';
        loanReCS.VersaPay_Auth_Token_Debit__c='SGHJDKLDLKSL';
        loanReCS.VersaPay_End_Point__c='www.versapytest.com';
        loanReCS.VersaPay_Signing_Key__c='siging Key';
        
        insert loanReCS;
    }
    
    //create Account record
    private static Account createAccount(){
        Account p = new Account();
        
        p.Salutation = 'Mr.';
        p.FirstName = 'Asad';
        p.Middle_Name__pc = 'Full';
        p.LastName = 'Person';
        
        p.PersonMailingState = 'ON';
        p.PersonBirthdate = Date.newInstance(1983, 12, 2);
        p.Gender__pc = 'Male';
        p.Marital_Status__pc = 'Single';
        
        p.Employer_Province__pc = 'ON';
        p.Number_of_Dependants__pc = '0';
        p.Home_Owner__pc = 'Own';
        p.PersonMailingState = 'ON';
        
        p.PersonHomePhone = '1235551234';
        p.PersonEmail = 'asad.fullperson@test.com';
        p.SIN__pc = '123456789';
        p.PersonMobilePhone = '5551231234';
        p.Work_Phone__pc = '1112223333';
        
        p.Communication_Preference__pc = 'Email';
        p.Monthly_Home_Expense__pc = 2000;
        p.Monthly_Expense__pc = 500;
        
        p.PersonMailingStreet = '4 Glenora';
        p.PersonMailingCity = 'Brampton';
        p.PersonMailingPostalCode = 'L6Y4K5';
        
        p.Employer_Name__pc = 'Paper Empire';
        p.Employer_Phone__pc = '9991231234';
        p.Employer_Street_Name__pc = 'Brick Lane';
        p.Employer_Street_Number__pc = '4';
        p.Employer_City__pc = 'Brampton';
        p.Employer_Postal_Code__pc = 'L6Y4K4';
        p.Occupation__pc = 'Manager';
        p.Employment_Years__pc = 3;
        p.Employment_Months__pc = 10;
        p.Gross_Monthly_Income__pc = 5000;
        
        insert p;
        
        return p;
    }
    
    //create a product record that will be eligible for funding batch
    private static Product__c createProduct(string fundType){
        Product__c app = new Product__c();
        
        app.customer__c = createAccount().id;
        app.Product_Status__c = 'New';
        app.Funding_Amount__c = 1000.00;
        app.Loan_Process_Type__c = 'Traditional';
        app.Funding_Type__c = fundType;
        app.Funding_Status__c = 'Pending';
        app.Funding_Date__c = System.Today();
        app.Regular_Payment_Amount__c = 100.00;
        //app.SOR_Account_Number__c = '123456789120';
        //app.SOR_Primary_Account_Number__c = '4534535345345';
        app.PAP_Account_Number__c = '98745632';
        app.PAP_Transit_Code__c = '45';
        app.PAP_Bank_Code__c = '12';
        app.Loan_Type__c = 'Affirm Financial Term Loan';
        app.First_Payment_Date__c = system.today();
        app.Disbursement_Amount__c = 45;
        //app.SOR_External_ID__c = 'SFI123';
        app.Disbursement_Amount__c = 123;
        app.PAP_Bank_Code__c = '004';
        app.PAP_Transit_Code__c = '156';
        app.PAP_Account_Number__c = '123459';
        app.First_Payment_Date__c = System.today();
        insert app;
        return app;
    }
    
    //create a funding batch recordcreateFundingBatchRecord
    private static Funding_Batch__c createFundingBatchRecord(){
    
        Funding_Batch__c batch = New Funding_Batch__c();
        batch.Released_Date__c = System.today();
        batch.Status__c = 'Pending';
        batch.Total_Funding_Amount__c = 123;
        batch.Total_Automated_Funding_Amount__c = 123;
        insert batch;
        
        return batch;
    }
}