force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/fields/Funding_Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch_Number__c</fullName>
    <description>Unique reference number for funding batch</description>
    <displayFormat>B-{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Funding Batch Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Released_Date__c</fullName>
    <label>Released Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Funding_Amount__c</fullName>
    <description>Total Funding Amount</description>
    <inlineHelpText>Total Funding Amount</inlineHelpText>
    <label>Total Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch_Number__c</fullName>
    <description>The batch number that this account was funded through</description>
    <formula>HYPERLINK(&quot;https://cs4.salesforce.com/&quot;+Funding_Batch__r.Id, Funding_Batch__r.Funding_Batch_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The batch number that this account was funded through</inlineHelpText>
    <label>Funding Batch Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSVFundingFileUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This is a utility class to create/read CSV files 
*  @author : A5E Consulting
*  A5E Consulting 08/23/2016     Class created
*************************************************************************************************/
public class CSVFundingFileUtil {
    
    //Header row
    public static final String csvHeader = 'first_name*,middle_name,last_name*,business_name,institution_number*,branch_number*,account_number*,transaction_type*,amount_in_cents*,transaction_reference,memo\n';
    
    public static void createCSVFile(List<Product__c> listProducts, Id fndBtchId, String transactionType){
        
        //Fetch Funding Batch Records
        Funding_Batch__c fndBatch= fetchFundingBatch(fndBtchId);
        System.debug('###'+listProducts);
        //Return String with records
        String finalStr = createStringFile(listProducts, transactionType);
        
        //Create Attchment for Payment and Funding
        if(String.isNotBlank(finalStr)){
            createAttchmentFile(transactionType, finalStr, fndBatch);
        }
    }
    
    //Return String with records
    private static String createStringFile(List<Product__c> listProducts, String transactionType){
        
        String finalStr = '';
        System.debug('###123'+listProducts);
        for(Product__c prod : listProducts){
            
            String recordStr;
            
            try{
                recordStr = replaceComma(prod.customer__r.firstName) +','
                    + replaceComma(prod.customer__r.middle_name__pc) +',' //Middle Name
                    + replaceComma(prod.customer__r.lastName) +','
                    + '' +',' //Business Name
                    + replaceComma(prod.PAP_Bank_Code__c) +','
                    + replaceComma(prod.PAP_Transit_Code__c) +','
                    + replaceComma(prod.PAP_Account_Number__c) +','
                    + creditDebitYN(transactionType) +','
                    + amountInCents(prod, transactionType)/*.)*/ +','
                    + replaceComma(prod.name) +','
                    + 'Affirm Financial TermLoan' +'\n';    
            }
            catch(Exception e){
                recordStr = '';
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,''+'Error while creating CSV file."'));
            }
            
            if(!String.isBlank(recordStr)){
                finalStr = finalStr + recordStr;
            }
        }
        
        if(!String.isBlank(finalStr)){
            finalStr = csvHeader + finalStr;            
        }
        
        return finalStr;
    }
    
    //Amount in Cents
    private static string amountInCents(Product__C prodT, String type){
        
        if(type.EqualsIgnoreCase('Credit')){
            return '' + (prodT.Disbursement_Amount__c *100);
        }else{
            return '' + (prodT.Funding_Amount__c * 100);
        }
    }
    
    //Credit and Debit 
    private static String creditDebitYN(String yn){
        
        if(yn.EqualsIgnoreCase('Credit')){
            //return 'Y';
            return 'direct_credit';
        }
        else{
            //return 'N';
            return 'direct_debit';
        }
    }
    
    //Fetch Funding Batch Records
    private static Funding_Batch__c fetchFundingBatch(String fndBtchId){
        
        return [select Id, Funding_Batch_Number__c, Released_Date__c, Total_Funding_Amount__c
                from Funding_Batch__c where Id =: fndBtchId];
    }
    
    //Create Attchment for Payment and Funding
    private static void createAttchmentFile(String transactionType, String finalStr, Funding_Batch__c fndBch){
        
        Attachment attachment = new Attachment();
        attachment.parentId = fndBch.Id;
        attachment.Body = Blob.valueOf(finalStr);
        if(transactionType == 'Credit'){
            attachment.Name = System.Now() + '- Funding File.csv';
        }
        if(transactionType == 'Debit'){
            attachment.Name = System.Now() + '- Payment File.csv';
        }
        
        try{
            insert attachment;              
        }
        catch(Exception e){
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,''+'Error while creating Attachment record file."'));
        }
    }
    
    //If number is null, return Blank
    @TestVisible
    private static String checkPAPNumber(Integer papNum){
        
        if(papNum == null){
            return '';
        }    
        else{
            return String.valueof(papNum);
        }
    }
    
    //Replace comma from String
    private static String replaceComma(String str){
        
        if(String.isNotBlank(str)){
            return (str.replaceAll(',',' '));
        }
        else{
            return '';
        }
    } 
}