force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Batch__c/fields/Funding_Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch_Number__c</fullName>
    <description>Unique reference number for funding batch</description>
    <displayFormat>B-{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Funding Batch Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Released_Date__c</fullName>
    <label>Released Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Automated_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Automated_Funding_Amount__c</fullName>
    <description>Total Automated Funding Amount</description>
    <inlineHelpText>Total Automated Funding Amount</inlineHelpText>
    <label>Total Automated Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Funding_Amount__c</fullName>
    <description>Total Funding Amount</description>
    <inlineHelpText>Total Funding Amount</inlineHelpText>
    <label>Total Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/fields/Total_Manual_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Manual_Funding_Amount__c</fullName>
    <description>Total Manual Funding Amount</description>
    <inlineHelpText>Total Manual Funding Amount</inlineHelpText>
    <label>Total Manual Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_ReEngineering__c/Loan_ReEngineering__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Re-Engineering</label>
</CustomObject>

force-app/main/default/objects/Loan_ReEngineering__c/fields/Run_Product_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Product_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Product Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Actual_Date_Funded__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Funded__c</fullName>
    <description>The date this account was funded by Affirm</description>
    <inlineHelpText>The date this account was funded by Affirm</inlineHelpText>
    <label>Actual Date Funded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Actual_Funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Funded_Amount__c</fullName>
    <description>The actual amount funded by Affirm on this account</description>
    <inlineHelpText>The actual amount funded by Affirm on this account</inlineHelpText>
    <label>Actual Funded Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch_Number__c</fullName>
    <description>The batch number that this account was funded through</description>
    <formula>HYPERLINK(&quot;https://cs4.salesforce.com/&quot;+Funding_Batch__r.Id, Funding_Batch__r.Funding_Batch_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The batch number that this account was funded through</inlineHelpText>
    <label>Funding Batch Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Process_Type__c</fullName>
    <description>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</description>
    <inlineHelpText>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</inlineHelpText>
    <label>Loan Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Re-write</fullName>
            </value>
            <value>
                <fullName>RBO</fullName>
            </value>
            <value>
                <fullName>Consolidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>The type of credit product this account represents</description>
    <inlineHelpText>The type of credit product this account represents</inlineHelpText>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>For Owner Review</fullName>
            </value>
            <value>
                <fullName>PoC Details Provided</fullName>
            </value>
            <value>
                <fullName>Pre-Filing Review</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry</fullName>
            </value>
            <value>
                <fullName>Owner Inquiry Received</fullName>
            </value>
            <value>
                <fullName>PoC Package Generated</fullName>
            </value>
            <value>
                <fullName>Filing Complete – No Further Action</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundingBatchController.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : This is a controller class to release Funding Batches
*  @author : A5E Consulting
*  @date : 06/22/2016
*
*  Change History:
*
*  Developer       Date          Description
*  ------------------------------------------------------------------------------------------------
*
*  A5E Consulting 06/22/2016     Class created * 
*************************************************************************************************/

public with sharing class FundingBatchController{
    public List<LoanUtility.ProductGroupWrapper> productWrapperGroup{get; set;}
    public List<LoanUtility.ProductListWrapper> listProductWrapper;
    public Boolean readableCheck{get;set;}
    public List<Product__c> listProd;
    public static Boolean saveAsText = false;
    public static Boolean selectAll{get;set;}
    
    //Summary fields
    public Integer noOfAccountsSelected{get;set;}
    public Decimal totalAutomatedFundingAmount{get;set;}
    public Decimal totalManualFundingAmount{get;set;}
    public String batchFundingStatus{get;set;}
    public String fundReleaseDate{get;set;}
    public String bankConfirmationNumber{get;set;}
    Loan_ReEngineering__c loanSettings;
    
    public FundingBatchController(){
        
    }
    
    public FundingBatchController(ApexPages.StandardController controller) {
        
        selectAll = true;
        String fundingBatchId = ApexPages.currentPage().getParameters().get('id');
        loanSettings = Loan_ReEngineering__c.getOrgDefaults();
        if (String.isNotBlank(fundingBatchId)) {
            readableCheck = false;
            
            List<Funding_Batch__c> fundingBatches = [select Id, Status__c, Total_Funding_Amount__c, Released_Date__c
                                                     from Funding_Batch__c where id=:fundingBatchId]; 
            if(!fundingBatches.isEmpty()){
                
                batchFundingStatus = fundingBatches.get(0).Status__c;
                fundReleaseDate = convertDateToString(fundingBatches.get(0).Released_Date__c.date());
                listProd = [select id, name, Product_Status__c, customer__r.name, customer__r.id, Funding_Amount__c, Loan_Process_Type__c,
                            Funding_Type__c, Funding_Status__c, Funding_Date__c, Regular_Payment_Amount__c, createdDate, //SOR_Account_Number__c,
                            Customer__r.LastName, Customer__r.FirstName, Customer__r.Customer_ID__c, Disbursement_Amount__c //, SOR_External_ID__c
                            from Product__c 
                            where Funding_Batch__c=:fundingBatches.get(0).Id 
                            order by Funding_Date__c desc];  
            } 
        }
        
        else{

            
            batchFundingStatus = 'Pending Review';
            readableCheck = true;
            listProd = [select id, name, Product_Status__c, customer__r.name, customer__r.id, Funding_Amount__c, Loan_Process_Type__c,
                        Funding_Type__c, Funding_Status__c, Funding_Date__c, First_Payment_Date__c, //SOR_Account_Number__c,
                        Regular_Payment_Amount__c, PAP_Account_Number__c, PAP_Transit_Code__c, PAP_Bank_Code__c,
                        Customer__r.LastName, Customer__r.FirstName, Customer__r.Middle_Name__pc, Customer__r.Customer_ID__c, Disbursement_Amount__c //, SOR_External_ID__c
                        from Product__c 
                        where Funding_Status__c = 'Pending'
                        and Funding_Batch__c = null
                        //and Funding_Type__c = 'Automated'
                        and Product_Status__c <> null and Funding_Amount__c <> null and Loan_Process_Type__c <> null and 
                        Funding_Type__c <> null and First_Payment_Date__c <> null
                        and Funding_Date__c <> null and Loan_Type__c='Affirm Financial Term Loan' AND Disbursement_Amount__c <> null
                        AND PAP_Account_Number__c <> null AND PAP_Transit_Code__c <> null AND PAP_Bank_Code__c <> null
                        order by Funding_Date__c desc];
            
            //}           
        }
        
        
        listProductWrapper = new List<LoanUtility.ProductListWrapper>();
        
        
        noOfAccountsSelected = 0;
        totalAutomatedFundingAmount = 0;
        totalManualFundingAmount = 0;
        bankConfirmationNumber = '';
        
        
        LoanUtility.ProductListWrapper prod;
        
        for(Product__c p : listprod){
            prod = new LoanUtility.ProductListWrapper();
            prod.product = p;
            listProductWrapper.add(prod);
        }
    }
    
    public PageReference reCalculate(){
        productWrapperGroup = new List<LoanUtility.ProductGroupWrapper>();
        
        LoanUtility.ProductGroupWrapper prodGroup;
        Boolean flag;
        noOfAccountsSelected = 0;
        totalAutomatedFundingAmount = 0;
        totalManualFundingAmount = 0;
        
        for(LoanUtility.ProductListWrapper plw : listProductWrapper){
            flag = false;
            for(LoanUtility.ProductGroupWrapper pgw : productWrapperGroup){
                if(convertDateToString(plw.product.Funding_Date__c) == pgw.groupDate){
                    pgw.productList.add(plw);
                    if(plw.check){
                        pgw.totalFundingAmount += plw.product.Disbursement_Amount__c;
                    }
                    flag = true;
                    break;
                }
            }
            if(!flag){
                prodGroup = new LoanUtility.ProductGroupWrapper();
                prodGroup.groupDate = convertDateToString(plw.product.Funding_Date__c);
                if(plw.check){
                    prodGroup.totalFundingAmount = plw.product.Disbursement_Amount__c;
                }
                prodGroup.productList.add(plw);
                productWrapperGroup.add(prodGroup);
            }
            
            if(plw.check){
                noOfAccountsSelected++;
                if(plw.product.Funding_Type__c == 'Manual'){
                    totalManualFundingAmount += plw.product.Disbursement_Amount__c;
                }else if(plw.product.Funding_Type__c == 'Automated'){
                    totalAutomatedFundingAmount += plw.product.Disbursement_Amount__c;
                }
            }
        }
        
        return null;
    }
    
    private String convertDateToString(DateTime d){
        return datetime.newInstance(d.year(), d.month(),d.day()).format('dd/MM/yyyy');
    }
    
    public PageReference releaseFund(){
        
        try{
            List<LoanUtility.ProductGroupWrapper> testProdWrp = new List<LoanUtility.ProductGroupWrapper>(productWrapperGroup);
            readableCheck = false;
            LoanUtility.ProductGroupWrapper groupProduct;
            productWrapperGroup = new List<LoanUtility.ProductGroupWrapper>();
            
            Funding_Batch__c fndBtch = new Funding_Batch__c();
            fndBtch.name = 'Funding Batch' + convertDateToString(system.now());
            fndBtch.Released_Date__c = system.now();
            fndBtch.Status__c = 'Released';
            
            //Update value on VF Page
            batchFundingStatus = 'Released';
            fundReleaseDate = convertDateToString(system.now());
            
            //Funding Amounts
            fndBtch.Total_Automated_Funding_Amount__c = totalAutomatedFundingAmount;
            fndBtch.Total_Manual_Funding_Amount__c = totalManualFundingAmount;
            fndBtch.Total_Funding_Amount__c = totalAutomatedFundingAmount + totalManualFundingAmount;
            
            insert fndBtch;
            
            system.debug('External Id for funding batch : ' + fndBtch.Funding_Batch_Number__c);
            List<Product__c> listProductToUpdate = new List<Product__c>();
            List<Product__c> listOfAutomatedProduct = new List<Product__c>();
            
            for(LoanUtility.ProductGroupWrapper pgw : testProdWrp){
                groupProduct = new LoanUtility.ProductGroupWrapper();
                listProductWrapper = new List<LoanUtility.ProductListWrapper>();
                for(LoanUtility.ProductListWrapper plw : pgw.productList){
                    if(plw.check == true){
                        listProductWrapper.add(plw);
                        /*if(plw.product.Funding_Type__c == 'Automated'){
                            listOfAutomatedProduct.add(plw.product);
                            plw.product.Funding_Status__c = 'Released Batch';
                        }
                        if(plw.product.Funding_Type__c == 'Manual'){
                            plw.product.Funding_Status__c = 'Funding Failed';
                        }*/
                        plw.product.Funding_Batch__c = fndBtch.id;
                        plw.product.Funding_Status__c = 'Funded';
                        plw.product.Actual_Date_Funded__c = system.today();
                        plw.product.Actual_Funded_Amount__c = plw.product.Disbursement_Amount__c;
                        
                        listProductToUpdate.add(plw.product);
                    }
                }
                groupProduct.groupDate = pgw.groupDate;
                groupProduct.totalFundingAmount = pgw.totalFundingAmount;
                groupProduct.productList = listProductWrapper;
                productWrapperGroup.add(groupProduct);
                
                
            }
            
            loanSettings.Run_Product_Trigger__c = false;
            update loanSettings;
            update listProductToUpdate;
            loanSettings.Run_Product_Trigger__c = true;
            update loanSettings;
            
            //FlatFileUtil.createFlatFile(listProductToUpdate, fndBtch.id, 'Credit');
            //FlatFileUtil.createFlatFile(listProductToUpdate, fndBtch.id, 'Debit');
            
            //Create a Funding CSV File with Attchment
            //CSVFundingFileUtil.createCSVFile(listOfAutomatedProduct, fndBtch.id, 'Credit');
            //Create a Payment CSV File with Attchment
            //CSVFundingFileUtil.createCSVFile(listProductToUpdate, fndBtch.id, 'Debit');            
            
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'Batch Released successfully');
            ApexPages.addMessage(myMsg);
            
            //execute VersaPay Fuding Batch
            DataBase.executeBatch(New VersaPayFundingBatch(fndBtch.id), 1);
            
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Batch Release failed');
            ApexPages.addMessage(myMsg);
        }        
        
        //PageReference retPage = Page.FundingBatchView;
        //retPage.setRedirect(true);      
        return null;
    }
    
    public void selectAll(){
        
        List<LoanUtility.ProductGroupWrapper> testProdWrp = new List<LoanUtility.ProductGroupWrapper>(productWrapperGroup);
        LoanUtility.ProductGroupWrapper groupProduct;
        system.debug('Wrp group : ' + testProdWrp);
        system.debug('Wrp group : ' + productWrapperGroup);
        productWrapperGroup = new List<LoanUtility.ProductGroupWrapper>();
        List<Product__c> listProductToUpdate = new List<Product__c>();
        List<LoanUtility.ProductListWrapper> listProducts = new List<LoanUtility.ProductListWrapper>();
        listProductWrapper = new List<LoanUtility.ProductListWrapper>();
        
        if(selectAll == false){
            
            for(LoanUtility.ProductGroupWrapper pgw : testProdWrp){
                groupProduct = new LoanUtility.ProductGroupWrapper();
                listProducts = new List<LoanUtility.ProductListWrapper>();
                for(LoanUtility.ProductListWrapper plw : pgw.productList){
                    plw.check = false;   
                    listProductWrapper.add(plw);
                    listProducts.add(plw);
                }
                groupProduct.groupDate = pgw.groupDate;
                groupProduct.totalFundingAmount = pgw.totalFundingAmount;
                groupProduct.productList = listProducts;
                productWrapperGroup.add(groupProduct);
            }
        }
        if(selectAll == true){
            
            for(LoanUtility.ProductGroupWrapper pgw : testProdWrp){
                groupProduct = new LoanUtility.ProductGroupWrapper();
                listProducts = new List<LoanUtility.ProductListWrapper>();
                for(LoanUtility.ProductListWrapper plw : pgw.productList){
                    plw.check = true;   
                    listProductWrapper.add(plw);
                    listProducts.add(plw);
                }
                groupProduct.groupDate = pgw.groupDate;
                groupProduct.totalFundingAmount = pgw.totalFundingAmount;
                groupProduct.productList = listProducts;
                productWrapperGroup.add(groupProduct);
            }
            
        }
        system.debug('Wrp group : ' + testProdWrp);
        system.debug('Wrp group : ' + productWrapperGroup);
        reCalculate();
    }
}