force-app/main/default/objects/Collection_Notes__c/Collection_Notes__c.object-meta.xml
<CustomObject>
    <label>Collection Notes</label>
    <nameField>
        <displayFormat>CN-{0000000}</displayFormat>
        <label>Collection Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Notes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Collection Notes</relationshipLabel>
    <relationshipName>Collection_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Notes__c/fields/Type_of_Notes__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Notes__c</fullName>
    <label>Type of Notes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Card_Activated__c.field-meta.xml
<CustomField>
    <fullName>Card_Activated__c</fullName>
    <defaultValue>&quot;FALSE&quot;</defaultValue>
    <description>Whether the card on this account was activated by the customer, for credit card accounts</description>
    <inlineHelpText>Whether the card on this account was activated by the customer, for credit card accounts</inlineHelpText>
    <label>Card Activated</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>The max credit limit for this account</description>
    <inlineHelpText>The max credit limit for this account</inlineHelpText>
    <label>Credit Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance_Effective_Date__c</fullName>
    <description>The date that the current outstanding balance was last calculated</description>
    <inlineHelpText>The date that the current outstanding balance was last calculated</inlineHelpText>
    <label>Current Balance Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Delinquency_Cycles__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Cycles__c</fullName>
    <description>The number of cycles this account is delinquent</description>
    <inlineHelpText>The number of cycles this account is delinquent</inlineHelpText>
    <label>Number of Cycles Delinquent</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Delinquency_Status__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Status__c</fullName>
    <description>Whether this account is currently in delinquency, as per the current balance effective date</description>
    <inlineHelpText>Whether this account is currently in delinquency, as per the current balance effective date</inlineHelpText>
    <label>Delinquency Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate charged on this account</description>
    <inlineHelpText>The interest rate charged on this account</inlineHelpText>
    <label>Interest Rate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Delinquency_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delinquency_Date__c</fullName>
    <description>The date this account last entered delinquency, if available</description>
    <inlineHelpText>The date this account last entered delinquency, if available</inlineHelpText>
    <label>Last Delinquency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PRIN_Number__c.field-meta.xml
<CustomField>
    <fullName>PRIN_Number__c</fullName>
    <description>The credit card PRIN number on this account</description>
    <inlineHelpText>The credit card PRIN number on this account</inlineHelpText>
    <label>PRIN Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTP_Information__c/PTP_Information__c.object-meta.xml
<CustomObject>
    <label>PTP Information</label>
    <nameField>
        <displayFormat>PTP-{000}</displayFormat>
        <label>PTP Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTP Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTP_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PTP Informations</relationshipLabel>
    <relationshipName>PTP_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Amount__c.field-meta.xml
<CustomField>
    <fullName>PTP_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Date__c.field-meta.xml
<CustomField>
    <fullName>PTP_Date__c</fullName>
    <label>Promise Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Mate__c.field-meta.xml
<CustomField>
    <fullName>PTP_Mate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promise Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PTP_Information__c/fields/PTP_Method__c.field-meta.xml
<CustomField>
    <fullName>PTP_Method__c</fullName>
    <label>Method of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>online</fullName>
            </value>
            <value>
                <fullName>branch</fullName>
            </value>
            <value>
                <fullName>cheque</fullName>
            </value>
            <value>
                <fullName>western union</fullName>
            </value>
            <value>
                <fullName>telepay</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCustomerCollectionsController.cls
/**************************************************************************************************
*
*  Class:   TestCustomerCollectionsController
*
*  @Description : This class contains unit tests for validating behavior of CustomerCollectionsController 
*  @Author      : A5E Consulting
*  @Date        : 06/02/2017
*
*************************************************************************************************/
@isTest(seeAllData = false)
private class TestCustomerCollectionsController{    
    static testMethod void testCustomerCollection(){
        
        //Dummy Account
        Account personAcc = new Account(LastName = 'test pesrson account', RecordTypeId =Schema.SObjectType.account.getRecordTypeInfosByName().get('Customer Salesforce').getRecordTypeId() );
        insert personAcc;
        
        //Dummy Product
        Product__c prod = new Product__c(Name = 'test prod',
                                          Source_System__c = 'FDR',
                                          Interest_Rate__c = 38.995, 
                                          Current_Balance__c = 20000, 
                                          Current_Balance_Effective_Date__c = system.today().addDays(-2), 
                                          Credit_Limit__c = 1000, 
                                          Card_Activated__c = 'FALSE', 
                                          Delinquency_Status__c = 'Delin status',
                                          Last_Delinquency_Date__c = system.today().addDays(-1),
                                          Customer__c = personAcc.Id,
                                          Delinquency_Cycles__c = 2,
                                          PRIN_Number__c = 200
                                          );
        insert prod;
        
        //Dummy PTP Information
        PTP_Information__c ptp = new PTP_Information__c(PTP_Date__c = system.Today().addDays(4), PTP_Mate__c = true, PTP_Amount__c = 2000, PTP_Method__c = 'online', Product__c = prod.Id);
        insert ptp;
        
        //Dummy Task with Due Date, Description too long
        task tsk = new task(Subject = 'task', Type_of_Activity__c='Collection', WhatId = personAcc.Id, Method_Of_Contact__c= 'Mobile', Operational_Outcome__c='PTP - Promise to Pay', Legal_Followup__c ='Initial Call', Best_Time_To_Call__c='9', ActivityDate=system.today().addDays(2), Description = 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for  will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose injected humour and the like');
        insert tsk;
        //Dummy Task with Staus completed and has due date
        task tsk1 = new task(Status = 'Completed', Subject = 'task', Type_of_Activity__c='Collection', WhatId = personAcc.Id, Method_Of_Contact__c= 'Mobile', Operational_Outcome__c='PTP - Promise to Pay', Legal_Followup__c ='Initial Call', Best_Time_To_Call__c='9', ActivityDate=system.today().addDays(2), Description = 'test');
        insert tsk1;
        //Dummy Task without due date
        task tsk2 = new task( Subject = 'task', Type_of_Activity__c='Collection', WhatId = personAcc.Id, Method_Of_Contact__c= 'Mobile', Operational_Outcome__c='PTP - Promise to Pay', Legal_Followup__c ='Initial Call', Best_Time_To_Call__c='9');
        insert tsk2;
        
        //Dummy Collection
        Collection_Notes__c coll = new Collection_Notes__c(Title__c = 'test collection', Body__c = 'test body', Type_of_Notes__c = 'Collections', Product__c = prod.Id);
        insert coll;

        
        ApexPages.currentPage().getParameters().put('id', personAcc.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(personAcc);
        CustomerCollectionsController obj = new CustomerCollectionsController(sc);
        obj.editAllNotes();
        obj.editAllCommentsAndNotes();
        obj.saveTaskActivity();
        obj.cancelButton();
        obj.saveDelinquentProducts();
    }
}