force-app/main/default/objects/Collection_Custom_Setting__c/Collection_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings used for Collection piece</description>
    <label>Collection Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Collection_Custom_Setting__c/fields/Collection_Notes_ID_Initial__c.field-meta.xml
<CustomField>
    <fullName>Collection_Notes_ID_Initial__c</fullName>
    <label>Collection Notes ID Initial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Notes__c/Collection_Notes__c.object-meta.xml
<CustomObject>
    <label>Collection Notes</label>
    <nameField>
        <displayFormat>CN-{0000000}</displayFormat>
        <label>Collection Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Notes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Collection Notes</relationshipLabel>
    <relationshipName>Collection_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Notes__c/fields/Type_of_Notes__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Notes__c</fullName>
    <label>Type of Notes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Card_Activated__c.field-meta.xml
<CustomField>
    <fullName>Card_Activated__c</fullName>
    <defaultValue>&quot;FALSE&quot;</defaultValue>
    <description>Whether the card on this account was activated by the customer, for credit card accounts</description>
    <inlineHelpText>Whether the card on this account was activated by the customer, for credit card accounts</inlineHelpText>
    <label>Card Activated</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>The max credit limit for this account</description>
    <inlineHelpText>The max credit limit for this account</inlineHelpText>
    <label>Credit Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance_Effective_Date__c</fullName>
    <description>The date that the current outstanding balance was last calculated</description>
    <inlineHelpText>The date that the current outstanding balance was last calculated</inlineHelpText>
    <label>Current Balance Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Delinquency_Days__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Days__c</fullName>
    <description>The number of days past due this account is, if applicable</description>
    <inlineHelpText>The number of days past due this account is, if applicable</inlineHelpText>
    <label>Number of Days Delinquent</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Delinquency_Status__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Status__c</fullName>
    <description>Whether this account is currently in delinquency, as per the current balance effective date</description>
    <inlineHelpText>Whether this account is currently in delinquency, as per the current balance effective date</inlineHelpText>
    <label>Delinquency Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Delinquency_Status_Formula__c.field-meta.xml
<CustomField>
    <fullName>Delinquency_Status_Formula__c</fullName>
    <description>True if this account is currently delinquent (missed it&apos;s next payment date), false if it is current</description>
    <formula>IF(Payment_Due_Date__c &lt; Today(), True, False)</formula>
    <inlineHelpText>True if this account is currently delinquent (missed it&apos;s next payment date), false if it is current</inlineHelpText>
    <label>Is Delinquent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Effective_Next_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Effective_Next_Payment_Amount__c</fullName>
    <formula>IF( AND(Override_Payment_Amount__c != 0, NOT(ISNULL(Override_Payment_Amount__c))), Override_Payment_Amount__c, 
IF(First_Payment_Date__c == Payment_Due_Date__c, First_Payment_Amount__c, Payment_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Next Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Effective_Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Next_Payment_Date__c</fullName>
    <description>The date that Salesforce will take the next payment on this account.</description>
    <formula>IF( AND(NOT(ISBLANK(Override_Payment_Date__c)), NOT(ISNULL(Override_Payment_Date__c))), Override_Payment_Date__c, 
IF(First_Payment_Date__c == Payment_Due_Date__c, First_Payment_Date__c, Payment_Due_Date__c))</formula>
    <inlineHelpText>The date that Salesforce will take the next payment on this account.</inlineHelpText>
    <label>Effective Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <description>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</description>
    <inlineHelpText>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</inlineHelpText>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Description__c</fullName>
    <description>A description of the External Status code value</description>
    <formula>CASE( External_Status_Current__c, &apos;A&apos;, &apos;Authorization Prohibited&apos;,
&apos;B&apos;, &apos;Bankrupt&apos;,
&apos;C&apos;, &apos;Closed&apos;,
&apos;E&apos;, &apos;Revoked&apos;,
&apos;F&apos;, &apos;Frozen&apos;,
&apos;I&apos;, &apos;Interest Accrual Prohibited&apos;,
&apos;L&apos;, &apos;Lost&apos;,
&apos;U&apos;, &apos;Stolen&apos;,
&apos;Z&apos;, &apos;Charged Off&apos;,
&apos;Normal Status&apos;)</formula>
    <inlineHelpText>A description of the External Status code value</inlineHelpText>
    <label>External Status Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate charged on this account</description>
    <inlineHelpText>The interest rate charged on this account</inlineHelpText>
    <label>Interest Rate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Delinquency_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delinquency_Date__c</fullName>
    <description>The date this account last entered delinquency, if available</description>
    <inlineHelpText>The date this account last entered delinquency, if available</inlineHelpText>
    <label>Last Delinquency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <description>The amount of the most recent previous payment made on this account</description>
    <inlineHelpText>The amount of the most recent previous payment made on this account</inlineHelpText>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <description>The date that the most recent previous payment was made on this account</description>
    <inlineHelpText>The date that the most recent previous payment was made on this account</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PTP1_Amount__c.field-meta.xml
<CustomField>
    <fullName>PTP1_Amount__c</fullName>
    <description>Latest PTP Information -Promised Amount</description>
    <inlineHelpText>Latest PTP Information -Promised Amount</inlineHelpText>
    <label>PTP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PTP1_Date__c.field-meta.xml
<CustomField>
    <fullName>PTP1_Date__c</fullName>
    <description>Latest PTP Information - Promise Date</description>
    <inlineHelpText>Latest PTP Information - Promise Date</inlineHelpText>
    <label>PTP Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PTP1_Method__c.field-meta.xml
<CustomField>
    <fullName>PTP1_Method__c</fullName>
    <description>Latest PTP Information - Payment Method</description>
    <inlineHelpText>Latest PTP Information - Payment Method</inlineHelpText>
    <label>PTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>online</fullName>
            </value>
            <value>
                <fullName>branch</fullName>
            </value>
            <value>
                <fullName>cheque</fullName>
            </value>
            <value>
                <fullName>western union</fullName>
            </value>
            <value>
                <fullName>telepay</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTP_Information__c/PTP_Information__c.object-meta.xml
<CustomObject>
    <label>PTP Information</label>
    <nameField>
        <displayFormat>PTP-{000}</displayFormat>
        <label>PTP Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTP Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTP_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PTP Informations</relationshipLabel>
    <relationshipName>PTP_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerCollectionsController.cls
/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This is a controller class to display Customer Collections Data 
 *  @author : A5E Consulting
 *  @date : 12/27/2016
 *  
 *************************************************************************************************/
public class CustomerCollectionsController {
    
    public static String accntId{get;set;}
    public List<TaskWrapper> wrappedCustTasks {get;set;}
    public List<CollectionNoteWrapper> wrappedCustColctNotes {get;set;}
    public List<ProdWrapper> wrappedProducts {get;set;}
    public String urlForPage{get;set;}
    public String urlForNewActivity{get;set;}
    public static List<ID> listActivitiesRelatedID{get;set;}
    public Integer countActivitiesForThisWeek{get;set;}
    public static Collection_Custom_Setting__c collCustSett{get;set;}
    public List<collectionWrpper> collectionNoteWrapperList{get;set;}
    //testing fields
    Public static String dateFormat{get;set;}
    public static string localeName{get;set;}
    public Boolean showCount{get;set;}
    
    //Constructor
    public CustomerCollectionsController(ApexPages.StandardController controller) {
        
        accntId = ApexPages.currentPage().getParameters().get('id');
        wrappedCustTasks = new List<TaskWrapper>();
        wrappedCustColctNotes = new List<CollectionNoteWrapper>();
        wrappedProducts = new List<ProdWrapper>();
        listActivitiesRelatedID = new List<ID>();
        urlForPage = '';
        urlForNewActivity = '';
        List<ID> listProdID = new List<ID>();
        collCustSett = Collection_Custom_Setting__c.getOrgDefaults();
        collectionNoteWrapperList = new List<collectionWrpper>();
        listActivitiesRelatedID.add(accntId);
        dateFormat = '';
        //Products
        List<Product__c> custProds = [Select Id, Name, 
                                            Source_System__c, Interest_Rate__c, Current_Balance__c, Current_Balance_Effective_Date__c, 
                                            Credit_Limit__c, Card_Activated__c, Delinquency_Status_Formula__c, Delinquency_Status__c,
                                            Last_Delinquency_Date__c, Effective_Next_Payment_Date__c, Effective_Next_Payment_Amount__c, 
                                            Delinquency_Days__c, External_Status_Current__c, External_Status_Description__c,
                                            VersaPay_State__c, Last_Payment_Amount__c, Last_Payment_Date__c
                                            From Product__c 
                                            where Customer__c=:accntId 
                                            and Delinquency_Status_Formula__c = True
                                            ]; 
        system.debug(accntId);
                //system.debug('pp '+[SELECT Customer__c,Delinquency_Status_Formula__c FROM Product__c]);
        if(!custProds.isEmpty()){
            for(Product__c prd: custProds){
                wrappedProducts.add(new ProdWrapper(prd));
                listProdID.add(prd.id);
                listActivitiesRelatedID.add(prd.id);
                
            }
            for(ProdWrapper wrpProd : wrappedProducts){
                for(PTP_Information__c ptpInfo : wrpProd.listPTPInfo){
                    listActivitiesRelatedID.add(ptpInfo.id);
                }
                /*for(CollectionNoteWrapper wrpNte: wrpProd.wrappedCustColctNotes){
                    //wrappedCustColctNotes.add(new CollectionNoteWrapper(nte));
                    listActivitiesRelatedID.add(wrpNte.nte.id);
                }*/
            }
            
        }         
        
        List<Collection_Notes__c> custColctNotes = [Select Id, Title__c, Body__c, Type_of_Notes__c, 
                                                    Product__r.Name, Product__r.id, createdDate, createdBy.Name, 
                                                    lastModifiedDate, lastModifiedBy.Name 
                                                    from Collection_Notes__c
                                                    where Product__r.id in :listProdID
                                                    order by lastModifiedDate desc];
        
        if(!custColctNotes.isEmpty()){
            for(Collection_Notes__c nte: custColctNotes){
                wrappedCustColctNotes.add(new CollectionNoteWrapper(nte));
                listActivitiesRelatedID.add(nte.id);
            }            
        }
        
        // Collection wrapper list
        if(!custProds.isEmpty()){
            for(Product__c prd: custProds){
                List<CollectionNoteWrapper> wrappedCustColNotes = new List<CollectionNoteWrapper>();
                if(!custColctNotes.isEmpty()){
                    for(Collection_Notes__c nte: custColctNotes){
                        if(prd.id == nte.Product__r.id){
                            wrappedCustColNotes.add(new CollectionNoteWrapper(nte));
                            //listActivitiesRelatedID.add(nte.id);
                        }
                    }            
                }
                
                collectionNoteWrapperList.add(new collectionWrpper(prd, wrappedCustColNotes));
            }
        }
        
        //Tasks
        List<Task> custTasks = [Select Id, WhatId, Subject, Owner.Name, status,
                            Method_Of_Contact__c, Operational_Outcome__c, Legal_Followup__c, Best_Time_To_Call__c,
                            Description, LastModifiedBy.Name, LastModifiedBy.Id, LastModifiedDate, ActivityDate,
                            CallClassification1__c
                            /*//PTC Information
                            PTP1_Amount__c, PTP1_Method__c, PTP1_Date__c, PTP1_mate_with__c, 
                            PTP2_Amount__c, PTP2_Method__c, PTP2_Date__c, PTP2_mate_with__c, 
                            PTP3_Amount__c, PTP3_Method__c, PTP3_Date__c, PTP3_mate_with__c*/
                            From Task 
                            where WhatId in :listActivitiesRelatedID and isdeleted=false and 
                            (Type_of_Activity__c = 'Collection' or Subject like '%Collection%' or CallClassification1__c like '%Collection%') order by ActivityDate DESC All Rows];
        
        /******** Task Sorting STARTS added by Rakesh Muppiri**************/
        // Segregate tasks based on values in Due Date field and Status
        List<Task> hasDueDate = new List<Task>();
        List<Task> noDueDate = new List<Task>();
        List<Task> completedTask = new List<Task>();
        
        if(!custTasks.isEmpty()){
            for(Task tsk: custTasks){
                // Store Competed Tasks
                if(tsk.Status =='Completed'){
                    completedTask.add(tsk);
                }
                // Store Tasks where due date is not null
                else if(tsk.ActivityDate != null){
                    hasDueDate.add(tsk);
                }
                // Store Tasks with Due date as null
                else{
                    noDueDate.add(tsk);
                }
                //wrappedCustTasks.add(new TaskWrapper(tsk));     // Commented by Rakesh
            }            
        }
        
        // Add all Tasks the dont have Due date to list to follow the order
        hasDueDate.addAll(noDueDate);
        
        // Process Tasks that is not Completed
        for(Task tsk :hasDueDate){
            wrappedCustTasks.add(new TaskWrapper(tsk));
        }
        
        // Process Tasks whos status is completed
        for(Task tsk :completedTask){
            wrappedCustTasks.add(new TaskWrapper(tsk));
        }
        /******** Task Sorting ENDS added by Rakesh Muppiri**************/
        
        List<Task> countTask = [Select Id From Task where WhatId =: accntId and isdeleted=false and 
                            (Type_of_Activity__c = 'Collection' or Subject like '%Collection%' or CallClassification1__c like '%Collection%') and lastModifiedDate = LAST_n_DAYS:5 All Rows];
        countActivitiesForThisWeek = countTask.size();
        if(countTask.size() > 0){
            showCount = true;
        }else{
            showCount = false;
        }
                            
        //Notes
        /*List<Note> custColctNotes = [Select Id, Title, ParentId, IsPrivate  
                                            From Note
                                            where ParentId=:accntId and Title like '%collection%'];    
        if(!custColctNotes.isEmpty()){
            for(Note nte: custColctNotes){
                wrappedCustColctNotes.add(new NoteWrapper(nte));                                        
            }            
        }*/
        
        viewPageinNewWindow();
        newButton();                                                             
    } 
    
    //Task Wrapper 
    public class TaskWrapper {
        public Task tsk {get; set;}
        public String tskLink {get;set;}
        public String taskBody{get;set;}
    
        public TaskWrapper(Task tsk){
            this.tsk = tsk;
            this.tskLink = URL.getSalesforceBaseUrl().toExternalForm() + '/' + tsk.Id;
            
            if(String.isNotBlank(tsk.Description)){
                if((tsk.Description).length() > 250){
                    this.taskBody = (tsk.Description).subString(0, 250) + '...';
                }else{
                    this.taskBody = tsk.Description;
                }
            }
            /*this.ptp1Date = dateToString(tsk.PTP1_Date__c);
            this.ptp2Date = dateToString(tsk.PTP2_Date__c);
            this.ptp3Date = dateToString(tsk.PTP3_Date__c);*/
        }
    } 
    
    /*//Note Wrapper
    public class NoteWrapper {
        public Note nte {get; set;}
        public String nteLink {get;set;}
        
        public NoteWrapper(Note nte){
            this.nte = nte;
            this.nteLink = URL.getSalesforceBaseUrl().toExternalForm() + '/' + nte.Id;          
        }
    }*/
    
    public class CollectionNoteWrapper{
        public Collection_Notes__c nte{get;set;}
        public string strBody{get;set;}
        public String strLastModifiedDate{get;set;}
        
        public CollectionNoteWrapper(Collection_Notes__c nte){
            this.nte = nte;
            this.strBody ='';
            if(String.isNotBlank(nte.Body__c)){
                if((nte.Body__c).length() > 100){
                    this.strBody = (nte.body__c).subString(0, 100) + '...';
                }else{
                    this.strBody = nte.body__c;
                }
            }
            
            this.strLastModifiedDate = dateToString(nte.lastModifiedDate);
        }
        /* Commented By Rakesh, we have already implemented this function at parent class leve, so below below will never used
        public String newCollectionButton(String prodName, String prodID){
            pageReference pgRef = new pageReference('/' + collCustSett.Collection_Notes_ID_Initial__c + '/e?' + collCustSett.Collection_Product_Field_ID__c + '=' + prodName + '&' + collCustSett.Collection_Product_Field_ID__c + '_lkid=' + prodID + '&retURL=' + accntid);
            pgRef.setRedirect(true);
            return pgRef.getUrl();
        }
        */
    }
    
    //Product Wrapper
    public class ProdWrapper {
        public Product__c prd {get; set;}
        public String prdLink {get;set;}
        public String lastDelDate{get;set;}
        public String nextPaymentDate {get;set;}
        public String curBalEffDate {get;set;}
        public List<PTP_Information__c> listPTPInfo{get;set;}
        //public List<Collection_Notes__c> listCollNotes{get;set;}
        //public List<CollectionNoteWrapper> wrappedCustColctNotes{get;set;}
        public String urlForNewPTP{get;set;}
        
        public ProdWrapper(Product__c prd){
            //wrappedCustColctNotes = new List<CollectionNoteWrapper>();
            
            this.prd = prd;
            this.prdLink = URL.getSalesforceBaseUrl().toExternalForm() + '/' + prd.Id;
            this.lastDelDate = dateToString(prd.Last_Delinquency_Date__c);
            this.nextPaymentDate = dateToString(prd.Effective_Next_Payment_Date__c);
            this.curBalEffDate = dateToString(prd.Current_Balance_Effective_Date__c);
            
            listPTPInfo = [select id, name, PTP_Date__c, PTP_Mate__c, PTP_Amount__c, PTP_Method__C from PTP_Information__c where Product__r.id =: prd.id order by lastModifiedDate desc];
            /*List<Collection_Notes__c> listCollNotes = [Select Id, Title__c, Body__c, Type_of_Notes__c, Product__r.Name, lastModifiedDate, lastModifiedBy.Name from Collection_Notes__c
                                                where Product__r.id =: prd.id];
            
            if(!listCollNotes.isEmpty()){
            for(Collection_Notes__c nte: listCollNotes){
                    wrappedCustColctNotes.add(new CollectionNoteWrapper(nte));
                    //listActivitiesRelatedID.add(nte.id);
                }            
            }*/
            urlForNewPTP = newPTPButton(prd.Name, prd.id);
            //urlForNewCollectionNote = newCollectionButton(prd.Name, prd.id);
        }
        
        public String newPTPButton(String prodName, String prodID){
            //https://cs22.salesforce.com/a19/e?CF00N17000001GApG=21461&CF00N17000001GApG_lkid=a0Dj000000092Ev&retURL=%2Fa0Dj000000092Ev
            pageReference pgRef = new pageReference('/' + collCustSett.PTP_ID_Initials__c +'/e?' + collCustSett.PTP_Product_Field_ID__c + '=' + prodName + '&' + collCustSett.PTP_Product_Field_ID__c + '_lkid=' + prodID + '&retURL=' + accntid);
            pgRef.setRedirect(true);
            return pgRef.getUrl();
        }
        
    }
    
    // Collections wrapper class used to 
    public class collectionWrpper{
        public Product__C prodID{get;set;}
        public list<CollectionNoteWrapper> listColNteWrp{get;set;}
        public String urlForNewCollectionNote{get;set;}
        
        public collectionWrpper(Product__C prdId, list<CollectionNoteWrapper> listNte){
            this.prodId = prdId;
            this.listColNteWrp = New List<CollectionNoteWrapper>(listNte);
            this.urlForNewCollectionNote = newCollectionButton(prdID.name, prdId.id);
        }
        
        public String newCollectionButton(String prodName, String prodID){
            //https://cs22.salesforce.com/a19/e?CF00N17000001GApG=21461&CF00N17000001GApG_lkid=a0Dj000000092Ev&retURL=%2Fa0Dj000000092Ev
            pageReference pgRef = new pageReference('/' + collCustSett.Collection_Notes_ID_Initial__c +'/e?' + collCustSett.Collection_Product_Field_ID__c + '=' + prodName + '&' + collCustSett.PTP_Product_Field_ID__c + '_lkid=' + prodID + '&retURL=' + accntid);
            pgRef.setRedirect(true);
            return pgRef.getUrl();
        }
    }
    
    private static String dateToString(DateTime dt){
        
        Map<String, String> mappedValues = new Map<String, String>();
        mappedValues = CustomerCollectionsController.MapValues(); 
        String user_locale = UserInfo.getLocale();
        String datetime_format = 'M/d/yyyy h:mm a';
        if (mappedValues.containsKey(user_locale)) {
            datetime_format = mappedValues.get(user_locale);
        }
        
        dateFormat = datetime_format;
        localeName = UserInfo.getLocale();
        if(dt !=null){
            //System.debug('Date: '+dt.format('MM/dd/yyyy'));
            //return dt.format('MM/dd/yyyy');
            //Datetime dt = DateTime.newInstance(dt, Time.newInstance(0, 0, 0, 0));
            
            //return DateTime.newInstance(dt.year(), dt.month(),dt.day()).format('MM/dd/yyyy');
            
            //return (dt.month()+ '/' + dt.day() + '/' + dt.year());
            
            return (dt.format(datetime_format));
            
        }
        else{
            return '';
        }    
    }
    
    public pageReference editAllNotes(){
        return null;
    }
    
    public pageReference editAllCommentsAndNotes(){
        return null;
    }
    
    // Updates tasks with the latest values given in the UI
    public pageReference saveTaskActivity(){
        
        List<ID> listTaskID = new List<ID>();
        for(TaskWrapper tskWrp : wrappedCustTasks){
            listTaskID.add(tskWrp.tsk.id);
        }
        
        List<Task> listTsk = [select id, Operational_Outcome__c, Legal_Followup__c, ActivityDate, CallClassification1__c from Task where id in : listTaskID];
        List<Task> listTskUpdate = new List<Task>();
        
        // Preparing wrapper class which is used to display under Tasks & Activity section on Collections page
        for(TaskWrapper tskWrp : wrappedCustTasks){
            for(Task tsk : listTsk){
                if(tsk.id == tskWrp.tsk.id){
                    tsk.Operational_Outcome__c = tskWrp.tsk.Operational_Outcome__c;
                    tsk.Legal_Followup__c = tskWrp.tsk.Legal_Followup__c;
                    tsk.ActivityDate = tskWrp.tsk.ActivityDate;
                    tsk.CallClassification1__c = tskWrp.tsk.CallClassification1__c;
                    listTskUpdate.add(tsk);
                }
            }
        }
        
        update listTskUpdate;
        return null;
    }
    
    // Method updates PTP records with latest data given 
    public pageReference saveDelinquentProducts(){
        
        List<PTP_Information__c> listPTP = new List<PTP_Information__c>();
        
        for(ProdWrapper prdWrp : wrappedProducts){
            for(PTP_Information__c ptpInfo : prdWrp.listPTPInfo){
                listPTP.add(ptpInfo);
            }
            
        }
        
        // Updatin PTP
        update listPTP;
        
        return null;
    }
    
    // Method invokes when user clicks on Cancel
    public pageReference cancelButton(){
        
        // Commented by Rakesh Muppiri
        //pageReference pgRef = new pageReference('/apex/CustomerCollections?id=' + accntId);
        
        // Added by Rakesh Muppiri
        pageReference pgRef = new pageReference('/apex/CustomerCollections?id=' + ApexPages.currentPage().getParameters().get('id'));
        pgRef.setRedirect(true);
        return pgRef;
    }
    
    // Method opens same collection page in a new window
    public void viewPageinNewWindow(){
        pageReference pgRef = new pageReference('/apex/CustomerCollections?id=' + accntId);
        pgRef.setRedirect(true);
        urlForPage = pgRef.getUrl();
        
    }
    
    // Method return a new page to create Task
    public void newButton(){
        //00T/e?who_id=0011700000ixVV3&what_id=0011700000ixVV3&retURL=%2F0011700000ixVV3
        pageReference pgRef = new pageReference('/00T/e?who_id=' + accntId + '&what_id=' + accntid + '&retURL=' + accntid);
        pgRef.setRedirect(true);
        urlForNewActivity = pgRef.getUrl();
    }
    
    private static Map<String, String> MapValues() {
        Map<String, String> locale_map = new Map<String, String>(); //holds the locale to timedate formats
        locale_map.put('ar', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_AE', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_BH', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_JO', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_KW', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_LB', 'dd/MM/yyyy hh:mm a');
        locale_map.put('ar_SA', 'dd/MM/yyyy hh:mm a');
        locale_map.put('bg_BG', 'yyyy-M-d H:mm');
        locale_map.put('ca', 'dd/MM/yyyy HH:mm');
        locale_map.put('ca_ES', 'dd/MM/yyyy HH:mm');
        locale_map.put('ca_ES_EURO', 'dd/MM/yyyy HH:mm');
        locale_map.put('cs', 'd.M.yyyy H:mm');
        locale_map.put('cs_CZ', 'd.M.yyyy H:mm');
        locale_map.put('da', 'dd-MM-yyyy HH:mm');
        locale_map.put('da_DK', 'dd-MM-yyyy HH:mm');
        locale_map.put('de', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_AT', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_AT_EURO', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_CH', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_DE', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_DE_EURO', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_LU', 'dd.MM.yyyy HH:mm');
        locale_map.put('de_LU_EURO', 'dd.MM.yyyy HH:mm');
        locale_map.put('el_GR', 'd/M/yyyy h:mm a');
        locale_map.put('en_AU', 'd/MM/yyyy HH:mm');
        locale_map.put('en_B', 'M/d/yyyy h:mm a');
        locale_map.put('en_BM', 'M/d/yyyy h:mm a');
        locale_map.put('en_CA', 'dd/MM/yyyy h:mm a');
        locale_map.put('en_GB', 'dd/MM/yyyy HH:mm');
        locale_map.put('en_GH', 'M/d/yyyy h:mm a');
        locale_map.put('en_ID', 'M/d/yyyy h:mm a');
        locale_map.put('en_IE', 'dd/MM/yyyy HH:mm');
        locale_map.put('en_IE_EURO', 'dd/MM/yyyy HH:mm');
        locale_map.put('en_NZ', 'd/MM/yyyy HH:mm');
        locale_map.put('en_SG', 'M/d/yyyy h:mm a');
        locale_map.put('en_US', 'M/d/yyyy h:mm a');
        locale_map.put('en_ZA', 'yyyy/MM/dd hh:mm a');
        locale_map.put('es', 'd/MM/yyyy H:mm');
        locale_map.put('es_AR', 'dd/MM/yyyy HH:mm');
        locale_map.put('es_BO', 'dd-MM-yyyy hh:mm a');
        locale_map.put('es_CL', 'dd-MM-yyyy hh:mm a');
        locale_map.put('es_CO', 'd/MM/yyyy hh:mm a');
        locale_map.put('es_CR', 'dd/MM/yyyy hh:mm a');
        locale_map.put('es_EC', 'dd/MM/yyyy hh:mm a');
        locale_map.put('es_ES', 'd/MM/yyyy H:mm');
        locale_map.put('es_ES_EURO', 'd/MM/yyyy H:mm');
        locale_map.put('es_GT', 'd/MM/yyyy hh:mm a');
        locale_map.put('es_HN', 'MM-dd-yyyy hh:mm a');
        locale_map.put('es_MX', 'd/MM/yyyy hh:mm a');
        locale_map.put('es_PE', 'dd/MM/yyyy hh:mm a');
        locale_map.put('es_PR', 'MM-dd-yyyy hh:mm a');
        locale_map.put('es_PY', 'dd/MM/yyyy hh:mm a');
        locale_map.put('es_SV', 'MM-dd-yyyy hh:mm a');
        locale_map.put('es_UY', 'dd/MM/yyyy hh:mm a');
        locale_map.put('es_VE', 'dd/MM/yyyy hh:mm a');
        locale_map.put('et_EE', 'd.MM.yyyy H:mm');
        locale_map.put('fi', 'd.M.yyyy H:mm');
        locale_map.put('fi_FI', 'd.M.yyyy H:mm');
        locale_map.put('fi_FI_EURO', 'd.M.yyyy H:mm');
        locale_map.put('fr', 'dd/MM/yyyy HH:mm');
        locale_map.put('fr_BE', 'd/MM/yyyy H:mm');
        locale_map.put('fr_CA', 'yyyy-MM-dd HH:mm');
        locale_map.put('fr_CH', 'dd.MM.yyyy HH:mm');
        locale_map.put('fr_FR', 'dd/MM/yyyy HH:mm');
        locale_map.put('fr_FR_EURO', 'dd/MM/yyyy HH:mm');
        locale_map.put('fr_LU', 'dd/MM/yyyy HH:mm');
        locale_map.put('fr_MC', 'dd/MM/yyyy HH:mm');
        locale_map.put('hr_HR', 'yyyy.MM.dd HH:mm');
        locale_map.put('hu', 'yyyy.MM.dd. H:mm');
        locale_map.put('hy_AM', 'M/d/yyyy h:mm a');
        locale_map.put('is_IS', 'd.M.yyyy HH:mm');
        locale_map.put('it', 'dd/MM/yyyy H.mm');
        locale_map.put('it_CH', 'dd.MM.yyyy HH:mm');
        locale_map.put('it_IT', 'dd/MM/yyyy H.mm');
        locale_map.put('iw', 'HH:mm dd/MM/yyyy');
        locale_map.put('iw_IL', 'HH:mm dd/MM/yyyy');
        locale_map.put('ja', 'yyyy/MM/dd H:mm');
        locale_map.put('ja_JP', 'yyyy/MM/dd H:mm');
        locale_map.put('kk_KZ', 'M/d/yyyy h:mm a');
        locale_map.put('km_KH', 'M/d/yyyy h:mm a');
        locale_map.put('ko', 'yyyy. M. d a h:mm');
        locale_map.put('ko_KR', 'yyyy. M. d a h:mm');
        locale_map.put('lt_LT', 'yyyy.M.d HH.mm');
        locale_map.put('lv_LV', 'yyyy.d.M HH:mm');
        locale_map.put('ms_MY', 'dd/MM/yyyy h:mm a');
        locale_map.put('nl', 'd-M-yyyy H:mm');
        locale_map.put('nl_BE', 'd/MM/yyyy H:mm');
        locale_map.put('nl_NL', 'd-M-yyyy H:mm');
        locale_map.put('nl_SR', 'd-M-yyyy H:mm');
        locale_map.put('no', 'dd.MM.yyyy HH:mm');
        locale_map.put('no_NO', 'dd.MM.yyyy HH:mm');
        locale_map.put('pl', 'yyyy-MM-dd HH:mm');
        locale_map.put('pt', 'dd-MM-yyyy H:mm');
        locale_map.put('pt_AO', 'dd-MM-yyyy H:mm');
        locale_map.put('pt_BR', 'dd/MM/yyyy HH:mm');
        locale_map.put('pt_PT', 'dd-MM-yyyy H:mm');
        locale_map.put('ro_RO', 'dd.MM.yyyy HH:mm');
        locale_map.put('ru', 'dd.MM.yyyy H:mm');
        locale_map.put('sk_SK', 'd.M.yyyy H:mm');
        locale_map.put('sl_SI', 'd.M.y H:mm');
        locale_map.put('sv', 'yyyy-MM-dd HH:mm');
        locale_map.put('sv_SE', 'yyyy-MM-dd HH:mm');
        locale_map.put('th', 'M/d/yyyy h:mm a');
        locale_map.put('th_TH', 'd/M/yyyy, H:mm ?.');
        locale_map.put('tr', 'dd.MM.yyyy HH:mm');
        locale_map.put('ur_PK', 'M/d/yyyy h:mm a');
        locale_map.put('vi_VN', 'HH:mm dd/MM/yyyy');
        locale_map.put('zh', 'yyyy-M-d ah:mm');
        locale_map.put('zh_CN', 'yyyy-M-d ah:mm');
        locale_map.put('zh_HK', 'yyyy-M-d ah:mm');
        locale_map.put('zh_TW', 'yyyy/M/d a h:mm');
        return locale_map; //return the map
    }
}