force-app/main/default/objects/API_Error__c/API_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Error__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>API_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Batch__c/Funding_Batch__c.object-meta.xml
<CustomObject>
    <label>Funding Batch</label>
    <nameField>
        <label>Funding Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Batch__c.field-meta.xml
<CustomField>
    <fullName>Funding_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The batch name that this account was funded through</description>
    <inlineHelpText>The batch name that this account was funded through</inlineHelpText>
    <label>Funding Batch</label>
    <referenceTo>Funding_Batch__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Posted_To_VersaPay_On__c.field-meta.xml
<CustomField>
    <fullName>Funding_Posted_To_VersaPay_On__c</fullName>
    <label>Funding Posted To Payment System On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Source_Token__c.field-meta.xml
<CustomField>
    <fullName>Funding_Source_Token__c</fullName>
    <description>To Calculate Source Token depend Branch Number</description>
    <formula>CASE( Branch_Number__c , 
null, &apos;BA3RI923U3GF&apos;, 
1, &apos;BA3RI923U3GF&apos;, 
2, &apos;BA7RDF3X3MP3&apos;, 
3, &apos;BA3RI923U3GF&apos;, 
4, &apos;BA7RDF3X3MP3&apos;, 
&apos;BA3RI923U3GF&apos;)</formula>
    <inlineHelpText>To Calculate Source Token depend Branch Number</inlineHelpText>
    <label>Funding Source Token</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>The last time EFT Funding information was updated on this account, if applicable</description>
    <inlineHelpText>The last time EFT Funding information was updated on this account, if applicable</inlineHelpText>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Account__c</fullName>
    <description>This field supports back-end payment processing operations</description>
    <inlineHelpText>This field supports back-end payment processing operations</inlineHelpText>
    <label>Payment System From Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Fund_Token__c</fullName>
    <description>The account that funds are moving from in VersaPay</description>
    <inlineHelpText>The account that funds are moving from in VersaPay</inlineHelpText>
    <label>Payment System From Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Funding_Error__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Funding_Error__c</fullName>
    <description>A reported reason for EFT Funding failure, if applicable</description>
    <inlineHelpText>A reported reason for EFT Funding failure, if applicable</inlineHelpText>
    <label>Payment System Funding Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>The account that funds are moving to in VersaPay</description>
    <inlineHelpText>The account that funds are moving to in VersaPay</inlineHelpText>
    <label>Payment System To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Fund_Token__c</fullName>
    <description>Source fund identifier</description>
    <label>Payment System To Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>The unique token that represents the most recent funding transaction for this Product</description>
    <inlineHelpText>The unique token that represents the most recent funding transaction for this Product</inlineHelpText>
    <label>Payment System Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VersaPayFundingBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Batch class that will process direct_credit transactions
*  @author : A5E Consulting
*  @date : 14/11/2016   

*************************************************************************************************/
global class VersaPayFundingBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
   // this class 
    public final String fundingBatchId;
    
    //constructor that pass funding batch record Id
    public VersaPayFundingBatch(String fundingBatchId){
        this.fundingBatchId = fundingBatchId;
    }
    
    //Query all the product records for Funding Batch record passed.
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        system.debug('Start Time :' + system.now());
        return Database.getQueryLocator([Select id, name, Disbursement_Amount__c, 
                                        Customer__r.PersonEmail, Customer__r.FirstName, Customer__r.LastName,
                                        PAP_Bank_Code__c, PAP_Transit_Code__c, PAP_Account_Number__c, First_Payment_Date__c, 
                                        Funding_Date__c, Funding_Source_Token__c 
                                        from Product__c
                                        WHERE Funding_Batch__c =: fundingBatchId 
                                        and Funding_Type__c = 'Automated'
                                        and Funding_Posted_To_VersaPay_On__c=null
                                         limit 50]);
    }
    
    //Use VersaPayWSUtil to send the request xml to VersaPay and update the Product record as per VersaPayResponse.
    global void execute(Database.BatchableContext BC, List<Product__c> prodList){
        System.debug('==='+prodList.size());
        system.debug('Batch Start Time :' + system.now());
        List<Product__c> productList = New List<Product__c>();
        List<API_Error__c> apiErrorList = New List<API_Error__c>();
        
        for(Product__c prod : prodList){
            
            API_Error__c apiError = New API_Error__c();
            
            //method that create direct_credit xml, parse reponse from the VersaPay    
            VersaPayWSUtil.VersaPayResponse resp = VersaPayWSUtil.createCreditRequest(prod, apiError);
            System.debug('resp ==='+resp );
            
            if(resp != null){
                
                if(String.isBlank(resp.errorMessage)){
                
                    if(String.isNotBlank(resp.versaPayTokenNumber)){
                        prod.VersaPay_Token_Number__c = resp.versaPayTokenNumber;
                    }
                    
                    if(String.isNotBlank(resp.versaPayFromFundToken)){
                        prod.VersaPay_From_Fund_Token__c = resp.versaPayFromFundToken;
                    }
                                        
                    if(String.isNotBlank(resp.versaPayToFundToken)){
                        prod.VersaPay_To_Fund_Token__c = resp.versaPayToFundToken;
                    }
                    
                    if(String.isNotBlank(resp.versaPayFromAccount)){
                        prod.VersaPay_From_Account__c = resp.versaPayFromAccount;
                    }
                    
                    if(String.isNotBlank(resp.versaPayToAccount)){
                        prod.VersaPay_To_Account__c = resp.versaPayToAccount;
                    }
                }   
            
                if(String.isNotBlank(resp.versaPayState)){
                    prod.VersaPay_State__c = resp.versaPayState;
                    
                    if(prod.VersaPay_State__c.equalsIgnoreCase('server_error') || prod.VersaPay_State__c.equalsIgnoreCase('unknown_error')){
                        prod.Funding_Status__c = 'Funding Failed';
                    }
                    
                    //if(String.isNotBlank(resp.errorDescription)){
                    prod.VersaPay_Funding_Error__c = resp.errorDescription;
                    //}
                }
                    
                prod.Last_State_Changed_Date__c = System.Now();
                prod.Funding_Posted_To_VersaPay_On__c = System.Now();
                
                productList.add(prod);
            }
            
            System.debug('apiError-Funding--'+apiError);
            if(apiError.Product__c != null){//apiError != null  
                System.debug('apiError Funding In: '+apiError);
                apiErrorList.add(apiError);
            }
        }
        
        //Update Product Records With VersaPay Responce
        if(productList.size() > 0){
            ProductTriggerHandler.runProductTrigger = false;
            update productList;  
            ProductTriggerHandler.runProductTrigger = true;
        }
        
        if(apiErrorList.size() >0){
            insert apiErrorList;
        }
        
        system.debug('Batch End Time :' + system.now());
    }
 
    
    global void finish(Database.BatchableContext BC){
        
        system.debug('End Time :' + system.now());
        
        List <Product__c> remaingCount = [Select id, name,Disbursement_Amount__c, 
                                        Customer__r.PersonEmail, Customer__r.FirstName, 
                                        Customer__r.LastName,PAP_Bank_Code__c, PAP_Transit_Code__c, 
                                        PAP_Account_Number__c, First_Payment_Date__c, 
                                        Funding_Date__c from Product__c
                                        WHERE Funding_Batch__c =: fundingBatchId 
                                        and Funding_Type__c = 'Automated' 
                                        and Funding_Posted_To_VersaPay_On__c=null];
       
        if(remaingCount!=null && remaingCount.size()>0){
            DateTime now  = DateTime.now();
            DateTime nextRunTime = now.addMinutes(2);
            String cronString = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + nextRunTime.month() + ' ? ' + nextRunTime.year(); 
            System.schedule(VersaPayFundingSchedule.class.getName() + '-' + now.format(), cronString, new VersaPayFundingSchedule(fundingBatchId) );         //new VersaPayFundingSchedule(fundingBatchId)  
        }                            
    }
   
}