force-app/main/default/objects/API_Error__c/API_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Error__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>API_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Error__c/fields/VersaPay_Product_Payment__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Product_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VersaPay Product Payment</label>
    <referenceTo>VersaPay_Product_Payment__c</referenceTo>
    <relationshipName>API_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Source_Token__c.field-meta.xml
<CustomField>
    <fullName>Funding_Source_Token__c</fullName>
    <description>To Calculate Source Token depend Branch Number</description>
    <formula>CASE( Branch_Number__c , 
null, &apos;BA3RI923U3GF&apos;, 
1, &apos;BA3RI923U3GF&apos;, 
2, &apos;BA7RDF3X3MP3&apos;, 
3, &apos;BA3RI923U3GF&apos;, 
4, &apos;BA7RDF3X3MP3&apos;, 
&apos;BA3RI923U3GF&apos;)</formula>
    <inlineHelpText>To Calculate Source Token depend Branch Number</inlineHelpText>
    <label>Funding Source Token</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>The last time EFT Funding information was updated on this account, if applicable</description>
    <inlineHelpText>The last time EFT Funding information was updated on this account, if applicable</inlineHelpText>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Amount__c</fullName>
    <description>An override of the next payment amount for automatic processing</description>
    <inlineHelpText>An override of the next payment amount for automatic processing</inlineHelpText>
    <label>Override Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Date__c</fullName>
    <description>An override of the next payment date for automatic processing</description>
    <inlineHelpText>An override of the next payment date for automatic processing</inlineHelpText>
    <label>Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Released_Date__c</fullName>
    <description>The date that account funds were delivered to the customer</description>
    <inlineHelpText>The date that account funds were delivered to the customer</inlineHelpText>
    <label>Payment Released Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Account__c</fullName>
    <description>This field supports back-end payment processing operations</description>
    <inlineHelpText>This field supports back-end payment processing operations</inlineHelpText>
    <label>Payment System From Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_From_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Fund_Token__c</fullName>
    <description>The account that funds are moving from in VersaPay</description>
    <inlineHelpText>The account that funds are moving from in VersaPay</inlineHelpText>
    <label>Payment System From Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>The account that funds are moving to in VersaPay</description>
    <inlineHelpText>The account that funds are moving to in VersaPay</inlineHelpText>
    <label>Payment System To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Fund_Token__c</fullName>
    <description>Source fund identifier</description>
    <label>Payment System To Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>The unique token that represents the most recent funding transaction for this Product</description>
    <inlineHelpText>The unique token that represents the most recent funding transaction for this Product</inlineHelpText>
    <label>Payment System Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>Last State changed DateTime</description>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Actual Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Posted_To_VersaPay_On__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posted_To_VersaPay_On__c</fullName>
    <label>Payment Posted To VersaPay On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Process_On__c.field-meta.xml
<CustomField>
    <fullName>Process_On__c</fullName>
    <description>Effective Payment Date</description>
    <label>Process On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_From_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Account__c</fullName>
    <description>Name of the originating account</description>
    <label>VersaPay From Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_From_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_From_Fund_Token__c</fullName>
    <description>Target fund identifier</description>
    <label>VersaPay From Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Payment_Error__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Payment_Error__c</fullName>
    <label>VersaPay Payment Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>VersaPay Transaction current state</description>
    <label>VersaPay State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>Name of the recipient account</description>
    <label>VersaPay To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_To_Fund_Token__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Fund_Token__c</fullName>
    <description>VersaPay To Fund Token</description>
    <label>VersaPay To Fund Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_Token_Number__c</fullName>
    <description>VersaPay transaction identifier</description>
    <label>VersaPay Token Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentProcessingBatch.cls
/**************************************************************************************************
*
*  Class    :  PaymentProcessingBatch 
*
*  @description : Batch class that will process direct_debit transactions
*  author : A5E Consulting
*
*  @date : 28/02/2017   

*************************************************************************************************/

global class PaymentProcessingBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    //Query all the product records for Payment Setup Batch record passed.
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([SELECT Id,
                                                Name,
                                                Product__r.Name, 
                                                Product__r.Customer__r.PersonEmail, 
                                                Product__r.Funding_Source_Token__c,
                                                Product__r.Customer__r.LastName, 
                                                Product__r.PAP_Bank_Code__c, 
                                                Product__r.PAP_Transit_Code__c, 
                                                Product__r.PAP_Account_Number__c,
                                                Product__r.Customer__r.FirstName, 
                                                //VersaPay_Token_Number__c, 
                                                VersaPay_From_Fund_Token__c, 
                                                VersaPay_To_Fund_Token__c, 
                                                VersaPay_From_Account__c, 
                                                VersaPay_To_Account__c, 
                                                Process_On__c, 
                                                Payment_Amount__c, 
                                                Last_State_Changed_Date__c, 
                                                Payment_Posted_To_VersaPay_On__c, 
                                                VersaPay_State__c, 
                                                VersaPay_Payment_Error__c, 
                                                Product__c 
                                                FROM VersaPay_Product_Payment__c                                                  
                                                WHERE Createddate = Today 
                                                AND Payment_Posted_To_VersaPay_On__c=null 
                                                AND Process_On__c!=null  
                                                limit 5]);
    }
    
     //Use VersaPayWSUtil to send the request xml to VersaPay and Create n requests for n Term.
    global void execute(Database.BatchableContext BC, List<VersaPay_Product_Payment__c> prodPayList){
        
        List<Id> prodPayIds = new List<Id>(); // Stores all versa pay record Ids
        
        for(VersaPay_Product_Payment__c prodPay : prodPayList){
            prodPayIds.add(prodPay.Product__c);
        }
        
        // Get corresponding product of Versa Payment records
        List<Product__c> prodMap = [Select id,Name, Override_Payment_Amount__c, Override_Payment_Date__c, Payment_Released_Date__c
                                        from Product__c 
                                        WHERE Hold_Payments__c = false
                                        AND Id IN : prodPayIds];
                                        
        // Map is used to return product while processing VersaPay records
        Map<Id, Product__c> prodIdMap = new Map<Id, Product__c>(); 
        for(Product__c p : prodMap){
            prodIdMap.put(p.Id, p);
        }
        
        // Used to store Versa Payment records that needs to be update
        List<VersaPay_Product_Payment__c> prodPayListUpdate = New List<VersaPay_Product_Payment__c>();
        List<Product__c> prodUpdateList = New List<Product__c>();
        List<API_Error__c> apiErrorList = New List<API_Error__c>();
        
        
        for(VersaPay_Product_Payment__c prodPay: prodPayList){
            system.debug('prodPay ==='+prodPay);
            // Get corresponding product of this Versa payment record
            Product__c prod = prodIdMap.get(prodPay.Product__c);
            
            API_Error__c apiError = New API_Error__c();
            
            // Create debit request for versa payment
            VersaPayWSUtil.VersaPayResponse resp = VersaPayWSUtil.createDebitRequestWithPayments(prodPay, apiError);
            if(resp != null ){                
                
                if(String.isBlank(resp.errorMessage)){
                    
                    if(String.isNotBlank(resp.versaPayTokenNumber)){
                        prodPay.VersaPay_Token_Number__c = resp.versaPayTokenNumber;
                    }
                    
                    if(String.isNotBlank(resp.versaPayFromFundToken)){
                        prodPay.VersaPay_From_Fund_Token__c = resp.versaPayFromFundToken;
                    }
                                        
                    if(String.isNotBlank(resp.versaPayToFundToken)){
                        prodPay.VersaPay_To_Fund_Token__c = resp.versaPayToFundToken;
                    }
                    
                    if(String.isNotBlank(resp.versaPayFromAccount)){
                        prodPay.VersaPay_From_Account__c = resp.versaPayFromAccount;
                    }
                    
                    if(String.isNotBlank(resp.versaPayToAccount)){
                        prodPay.VersaPay_To_Account__c = resp.versaPayToAccount;
                    }
                }
                
                prodPay.Last_State_Changed_Date__c = System.Now();
                prodPay.Payment_Posted_To_VersaPay_On__c = System.Now();
                prodPay.VersaPay_State__c = resp.versaPayState;
                
                //Update if any error on creating debit request
                prodPay.VersaPay_Payment_Error__c = resp.errorDescription;
                prodPayListUpdate.add(prodPay);
            }
            
            if(apiError != null && String.isNotBlank(apiError.Response__c)){
                apiErrorList.add(apiError);
            }
            
            // Ameya - Please confirm is this update should happen here or in payment create batch class 
            //prod.Payment_Released_Date__c = (system.now()).date();
            //prodUpdateList.add(prod);
        }
        
        // Update VeraPayment
        if(prodPayListUpdate.size() >0){
            update prodPayListUpdate;
        }
        
        // Update product with Payment_Released_Date__c as TODAY -- confirm based on line 127
        if(prodUpdateList.size() >0){
            ProductTriggerHandler.runProductTrigger = false;
            update prodUpdateList;
            ProductTriggerHandler.runProductTrigger = true;
        }       
        
        for(API_Error__c api : apiErrorList){
            for(VersaPay_Product_Payment__c proPayset : prodPayList){
                System.debug('ID: '+api.Product__c +'='+ proPayset.Product__c);
                if(api.Product__c == proPayset.Product__c){
                    api.VersaPay_Product_Payment__c = proPayset.ID;
                }
            }
        }
        
        if(apiErrorList.size() >0){
            insert apiErrorList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
        system.debug('End Time :' + system.now());
        Integer remainingCount = [SELECT COUNT() FROM VersaPay_Product_Payment__c WHERE Createddate = Today AND Payment_Posted_To_VersaPay_On__c =null AND Process_On__c!=null];
       
        if(remainingCount >0){
            DateTime now  = DateTime.now();
            DateTime nextRunTime = now.addMinutes(1);
            String cronString = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + nextRunTime.month() + ' ? ' + nextRunTime.year(); 
            System.schedule(PaymentProcessingSchedule.class.getName() + '-' + now.format(), cronString, new PaymentProcessingSchedule());           
        }                            
    }
}