force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit_Amount__c</fullName>
    <description>The amount of credit currently available to the customer</description>
    <inlineHelpText>The amount of credit currently available to the customer</inlineHelpText>
    <label>Available Credit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Average_Daily_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Average_Daily_Balance__c</fullName>
    <description>The average daily balance of this account, for revolving accounts</description>
    <inlineHelpText>The average daily balance of this account, for revolving accounts</inlineHelpText>
    <label>Current Average Daily Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <description>The amount of the most recent previous payment made on this account</description>
    <inlineHelpText>The amount of the most recent previous payment made on this account</inlineHelpText>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Statement_Credit_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Credit_Interest_Amount__c</fullName>
    <description>The interest amount as shown on the account&apos;s most recent statement issued</description>
    <inlineHelpText>The interest amount as shown on the account&apos;s most recent statement issued</inlineHelpText>
    <label>Last Statement Credit Interest Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Process_Type__c</fullName>
    <description>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</description>
    <inlineHelpText>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</inlineHelpText>
    <label>Loan Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Re-write</fullName>
            </value>
            <value>
                <fullName>RBO</fullName>
            </value>
            <value>
                <fullName>Consolidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/Product_Cycle_History__c.object-meta.xml
<CustomObject>
    <description>Product Sanpshot</description>
    <label>Product Cycle History</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Cycle History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cycle_History__c/fields/Available_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit_Amount__c</fullName>
    <label>Available Credit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Current_Average_Daily_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Average_Daily_Balance__c</fullName>
    <label>Current Average Daily Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Iteration_Number__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Number__c</fullName>
    <label>Iteration Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Statement_Credit_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Credit_Interest_Amount__c</fullName>
    <label>Last Statement  Credit Interest  Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Product_Sanpshot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Snapshot_Settings__c/Product_Snapshot_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product Snapshot Settings</description>
    <label>Product Snapshot Settings</label>
</CustomObject>

force-app/main/default/objects/Product_Snapshot_Settings__c/fields/Iteration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Limit__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Iteration Limit</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Snapshot_Settings__c/fields/Next_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Next_Iteration__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Next Iteration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDeleteProductSnapshotBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Test Class for DeleteProductSnapshotBatch    
*  @author : A5E Consulting
*  @date : 02/03/2017   

*************************************************************************************************/
@isTest
public class TestDeleteProductSnapshotBatch{

    public Static testMethod void delPrdSnapBatch(){
    
        //create Product Snapshot Custom Setting Record    
        createProductSnapCS();
        
        //create Product record
        createProduct();
        
        //create Product Cycle History record
        createPrdCycHis();
       
        //execute DeleteProductSnapshotBatch
        Database.executeBatch(New DeleteProductSnapshotBatch(), 200);
    }
    
    //create Product Cycle History record
    public static void createPrdCycHis(){
        
        Product_Cycle_History__c prdSnap = New Product_Cycle_History__c();
        prdSnap.Available_Credit_Amount__c = 100;
        prdSnap.Current_Average_Daily_Balance__c = 100;
        prdSnap.Current_Balance__c = 100;
        prdSnap.Last_Payment_Amount__c = 100;
        prdSnap.Last_Statement_Credit_Interest_Amount__c = 100;
        prdSnap.Product__c = createProduct().Id;
        prdSnap.Iteration_Number__c = 2;
        insert prdSnap;
    }
    
    //create Product records
    public static Product__c createProduct(){
        
        Product__c app = new Product__c();
        app.customer__c = createAccount().id;
        app.Product_Status__c = 'New';
        app.Funding_Amount__c = 1000.00;
        app.Loan_Process_Type__c = 'Traditional';
        app.Funding_Status__c = 'Pending';
        app.Funding_Date__c = System.Today();
        app.Regular_Payment_Amount__c = 100.00;
        //app.SOR_Primary_Account_Number__c = '12345678912';
        app.PAP_Account_Number__c = '98745632';
        app.PAP_Transit_Code__c = '456';
        app.PAP_Bank_Code__c = '12';
        
        insert app;
        
        return app;
    }

    //create Product Snapshot Custom Setting Record
    public static Product_Snapshot_Settings__c createProductSnapCS(){
        
        Product_Snapshot_Settings__c prdSnap = New Product_Snapshot_Settings__c();
        prdSnap.Iteration_Limit__c = 1;
        prdSnap.Next_Iteration__c = 2;
        
        insert prdSnap;
        
        return prdSnap;
    }
    
    //create Customer
    private static Account createAccount(){
        Account acc = new Account();
        
        acc.Salutation = 'Mr.';
        acc.FirstName = 'Asad';
        acc.Middle_Name__pc = 'Full';
        acc.LastName = 'Person';
        
        acc.PersonMailingState = 'ON';
        acc.PersonBirthdate = Date.newInstance(1983, 12, 2);
        acc.Gender__pc = 'Male';
        acc.Marital_Status__pc = 'Single';
        
        acc.Employer_Province__pc = 'ON';
        acc.Number_of_Dependants__pc = '0';
        acc.Home_Owner__pc = 'Own';
        acc.PersonMailingState = 'ON';
        
        acc.PersonHomePhone = '1235551234';
        acc.PersonEmail = 'asad.fullperson@test.com';
        acc.SIN__pc = '123456789';
        acc.PersonMobilePhone = '5551231234';
        acc.Work_Phone__pc = '1112223333';
        
        acc.Communication_Preference__pc = 'Email';
        acc.Monthly_Home_Expense__pc = 2000;
        acc.Monthly_Expense__pc = 500;
        
        acc.PersonMailingStreet = '4 Glenora';
        acc.PersonMailingCity = 'Brampton';
        acc.PersonMailingPostalCode = 'L6Y4K5';
        
        acc.Employer_Name__pc = 'Paper Empire';
        acc.Employer_Phone__pc = '9991231234';
        acc.Employer_Street_Name__pc = 'Brick Lane';
        acc.Employer_Street_Number__pc = '4';
        acc.Employer_City__pc = 'Brampton';
        acc.Employer_Postal_Code__pc = 'L6Y4K4';
        acc.Occupation__pc = 'Manager';
        acc.Employment_Years__pc = 3;
        acc.Employment_Months__pc = 10;
        acc.Gross_Monthly_Income__pc = 5000;
        
        insert acc;
        
        return acc;
    }
}