force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <description>Whether this account was funded through manual or automated processes</description>
    <inlineHelpText>Whether this account was funded through manual or automated processes</inlineHelpText>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>The last time EFT Funding information was updated on this account, if applicable</description>
    <inlineHelpText>The last time EFT Funding information was updated on this account, if applicable</inlineHelpText>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Process_Type__c</fullName>
    <description>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</description>
    <inlineHelpText>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</inlineHelpText>
    <label>Loan Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Re-write</fullName>
            </value>
            <value>
                <fullName>RBO</fullName>
            </value>
            <value>
                <fullName>Consolidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>The type of credit product this account represents</description>
    <inlineHelpText>The type of credit product this account represents</inlineHelpText>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affirm Financial MasterCard</fullName>
            </value>
            <value>
                <fullName>Affirm Financial Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>The funding state of this product in VersaPay</description>
    <inlineHelpText>The funding state of this product in VersaPay</inlineHelpText>
    <label>Payment System State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>wait_for_sending_approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>The account that funds are moving to in VersaPay</description>
    <inlineHelpText>The account that funds are moving to in VersaPay</inlineHelpText>
    <label>Payment System To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Last_State_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_Changed_Date__c</fullName>
    <description>Last State changed DateTime</description>
    <label>Last State Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/MegaSys_Export_Date__c.field-meta.xml
<CustomField>
    <fullName>MegaSys_Export_Date__c</fullName>
    <label>MegaSys Export Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Actual Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Posted_To_VersaPay_On__c.field-meta.xml
<CustomField>
    <fullName>Payment_Posted_To_VersaPay_On__c</fullName>
    <label>Payment Posted To VersaPay On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Posted_To_MegaSys__c.field-meta.xml
<CustomField>
    <fullName>Posted_To_MegaSys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Posted To MegaSys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Process_On__c.field-meta.xml
<CustomField>
    <fullName>Process_On__c</fullName>
    <description>Effective Payment Date</description>
    <label>Process On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_State__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_State__c</fullName>
    <description>VersaPay Transaction current state</description>
    <label>VersaPay State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>wait_for_claim</fullName>
            </value>
            <value>
                <fullName>wait_for_request_approval</fullName>
            </value>
            <value>
                <fullName>wait_for_bank_account_verification</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>completed_but_nsfed</fullName>
            </value>
            <value>
                <fullName>server_error</fullName>
            </value>
            <value>
                <fullName>unknown_error</fullName>
            </value>
            <value>
                <fullName>nsfed</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/VersaPay_To_Account__c.field-meta.xml
<CustomField>
    <fullName>VersaPay_To_Account__c</fullName>
    <description>Name of the recipient account</description>
    <label>VersaPay To Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMegasysPaymentCSVUtil.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : TestMegasysPaymentCSVUtil.
*  @author : A5E Consulting
*  @date : 11/23/2016   

*************************************************************************************************/
@isTest
public class TestMegasysPaymentCSVUtil{
    
    static testMethod void testMegaSysPaymentCsvUtil(){
         //create Vesapay Product records
        Product__c prod = createVersapayProduct();
        
        //create VersaPay Payment Setup Records
        createVersapayPaySet(prod);
        
        //fetch All Eligible Versapay Product Payment Records for MegaSys
        MegasysPaymentCSVUtil.fecthVersaPayProdPayment();
        
        //fetch All Eligible Versapay Product Payment Records
        String versaPayCSV = MegasysPaymentCSVUtil.createVersaPayCSV();
        
        //Create MegaSys Payment Update Record
        MegasysPaymentCSVUtil.createMegaSysPaymentRecord(versaPayCSV);
        
        //update Versapay Payment Setup records
        MegasysPaymentCSVUtil.updateVersaPayListRecords();
        
       //check null 
       MegasysPaymentCSVUtil.convertDateToString(null);
    }
    
     //create Account record
    private static Account createAccount(){
        Account p = new Account();
        
        p.Salutation = 'Mr.';
        p.FirstName = 'Asad';
        p.Middle_Name__pc = 'Full';
        p.LastName = 'Person';
        
        p.PersonMailingState = 'ON';
        p.PersonBirthdate = Date.newInstance(1983, 12, 2);
        p.Gender__pc = 'Male';
        p.Marital_Status__pc = 'Single';
        
        p.Employer_Province__pc = 'ON';
        p.Number_of_Dependants__pc = '0';
        p.Home_Owner__pc = 'Own';
        p.PersonMailingState = 'ON';
        
        p.PersonHomePhone = '1235551234';
        p.PersonEmail = 'asad.fullperson@test.com';
        p.SIN__pc = '123456789';
        p.PersonMobilePhone = '5551231234';
        p.Work_Phone__pc = '1112223333';
        
        p.Communication_Preference__pc = 'Email';
        p.Monthly_Home_Expense__pc = 2000;
        p.Monthly_Expense__pc = 500;
        
        p.PersonMailingStreet = '4 Glenora';
        p.PersonMailingCity = 'Brampton';
        p.PersonMailingPostalCode = 'L6Y4K5';
        
        p.Employer_Name__pc = 'Paper Empire';
        p.Employer_Phone__pc = '9991231234';
        p.Employer_Street_Name__pc = 'Brick Lane';
        p.Employer_Street_Number__pc = '4';
        p.Employer_City__pc = 'Brampton';
        p.Employer_Postal_Code__pc = 'L6Y4K4';
        p.Occupation__pc = 'Manager';
        p.Employment_Years__pc = 3;
        p.Employment_Months__pc = 10;
        p.Gross_Monthly_Income__pc = 5000;
        
        insert p;
        
        return p;
    }
    //create Vesapay Product records
    private static Product__c createVersapayProduct(){
        
        Product__c app = new Product__c();
        
        app.customer__c = createAccount().id;
        app.Product_Status__c = 'New';
        app.Funding_Amount__c = 1000.00;
        app.Loan_Process_Type__c = 'Traditional';
        app.Funding_Type__c = 'Automated';
        app.Funding_Status__c = 'Pending';
        app.Funding_Date__c = System.Today();
        app.Regular_Payment_Amount__c = 100.00;
        //app.SOR_Account_Number__c = '123456789120';
        //app.SOR_Primary_Account_Number__c = '4534535345345';
        app.PAP_Account_Number__c = '98745632';
        app.PAP_Transit_Code__c = '45';
        app.PAP_Bank_Code__c = '12';
        app.Loan_Type__c = 'Affirm Financial Term Loan';
        app.First_Payment_Date__c = system.today();
        app.Disbursement_Amount__c = 45;
        
        insert app;
        return app;
    }
    
    //create VersaPay Payment Setup Records
    private static void createVersapayPaySet(Product__c prod){
        
        VersaPay_Product_Payment__c vpp = New VersaPay_Product_Payment__c();
        vpp.Payment_Amount__c = 1000;
        vpp.Last_State_Changed_Date__c = System.Now();
        vpp.MegaSys_Export_Date__c = System.today();
        vpp.Payment_Posted_To_VersaPay_On__c = System.today();
        vpp.Posted_To_MegaSys__c = false;
        vpp.Product__c = prod.Id;
        vpp.VersaPay_State__c = 'Completed';
        vpp.VersaPay_To_Account__c = 'FKJHKJSHEOH';
        vpp.Process_On__c = System.Today();
        vpp.VersaPay_Token_Number__c = '454446';
        insert vpp;
    }
}