force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit_Amount__c</fullName>
    <description>The amount of credit currently available to the customer</description>
    <inlineHelpText>The amount of credit currently available to the customer</inlineHelpText>
    <label>Available Credit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Card_Used_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Card_Used_This_Month__c</fullName>
    <defaultValue>&quot;FALSE&quot;</defaultValue>
    <description>Whether the account was used by the customer this month, for revolving accounts</description>
    <inlineHelpText>Whether the account was used by the customer this month, for revolving accounts</inlineHelpText>
    <label>Card Used This Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>The max credit limit for this account</description>
    <inlineHelpText>The max credit limit for this account</inlineHelpText>
    <label>Credit Limit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Credit_Limit_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Last_Changed_Date__c</fullName>
    <description>The last time the credit limit changed on this account</description>
    <inlineHelpText>The last time the credit limit changed on this account</inlineHelpText>
    <label>Credit Limit Last Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Average_Daily_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Average_Daily_Balance__c</fullName>
    <description>The average daily balance of this account, for revolving accounts</description>
    <inlineHelpText>The average daily balance of this account, for revolving accounts</inlineHelpText>
    <label>Current Average Daily Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Current_Balance_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance_Effective_Date__c</fullName>
    <description>The date that the current outstanding balance was last calculated</description>
    <inlineHelpText>The date that the current outstanding balance was last calculated</inlineHelpText>
    <label>Current Balance Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <description>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</description>
    <inlineHelpText>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</inlineHelpText>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>FDR:  The Internal Status code of this account
Megasys: The InternalStatus of the loan account</description>
    <inlineHelpText>FDR:  The Internal Status code of this account
Megasys: The InternalStatus of the loan account</inlineHelpText>
    <label>Internal Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Delinquency_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delinquency_Date__c</fullName>
    <description>The date this account last entered delinquency, if available</description>
    <inlineHelpText>The date this account last entered delinquency, if available</inlineHelpText>
    <label>Last Delinquency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <description>The amount of the most recent previous payment made on this account</description>
    <inlineHelpText>The amount of the most recent previous payment made on this account</inlineHelpText>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <description>The date that the most recent previous payment was made on this account</description>
    <inlineHelpText>The date that the most recent previous payment was made on this account</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Statement_Balance__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Balance__c</fullName>
    <description>The balance as shown on the account&apos;s most recent statement issued</description>
    <inlineHelpText>The balance as shown on the account&apos;s most recent statement issued</inlineHelpText>
    <label>Last Statement Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Statement_Credit_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Credit_Interest_Amount__c</fullName>
    <description>The interest amount as shown on the account&apos;s most recent statement issued</description>
    <inlineHelpText>The interest amount as shown on the account&apos;s most recent statement issued</inlineHelpText>
    <label>Last Statement Credit Interest Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Last_Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Date__c</fullName>
    <description>The date the most recent statement was issued on this account</description>
    <inlineHelpText>The date the most recent statement was issued on this account</inlineHelpText>
    <label>Last Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Late_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee_Amount_Outstanding__c</fullName>
    <description>The total amount of late-payment fees outstanding on this account</description>
    <inlineHelpText>The total amount of late-payment fees outstanding on this account</inlineHelpText>
    <label>Late Fee Amount Outstanding</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Latest_NSFED_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_NSFED_Date__c</fullName>
    <description>The most recent date this account had an NSF occur, based on VersaPay automated payments only</description>
    <inlineHelpText>The most recent date this account had an NSF occur, based on VersaPay automated payments only</inlineHelpText>
    <label>Latest NSF Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/NSF_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>NSF_Fee_Amount_Outstanding__c</fullName>
    <description>The total amount of NSF fees still unpaid, is applicable</description>
    <inlineHelpText>The total amount of NSF fees still unpaid, is applicable</inlineHelpText>
    <label>NSF Fee Amount Outstanding</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Other_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Other_Fee_Amount_Outstanding__c</fullName>
    <description>The total amount of Other Fees outstanding on this account, if applicable</description>
    <inlineHelpText>The total amount of Other Fees outstanding on this account, if applicable</inlineHelpText>
    <label>Other Fee Amount Outstanding</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/Product_Cycle_History__c.object-meta.xml
<CustomObject>
    <description>Product Sanpshot</description>
    <label>Product Cycle History</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Cycle History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cycle_History__c/fields/Available_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit_Amount__c</fullName>
    <label>Available Credit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Card_Used_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Card_Used_This_Month__c</fullName>
    <label>Card Used This Month</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Credit_Limit_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Last_Changed_Date__c</fullName>
    <label>Credit Limit Last Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Current_Average_Daily_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Average_Daily_Balance__c</fullName>
    <label>Current Average Daily Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Current_Balance_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance_Effective_Date__c</fullName>
    <label>Current Balance Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <label>Internal Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Delinquency_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delinquency_Date__c</fullName>
    <label>Last Delinquency Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <label>Last Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <label>Last Payment  Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Statement_Balance__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Balance__c</fullName>
    <label>Last Statement  Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Statement_Credit_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Credit_Interest_Amount__c</fullName>
    <label>Last Statement  Credit Interest  Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Last_Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Statement_Date__c</fullName>
    <label>Last Statement  Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Late_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee_Amount_Outstanding__c</fullName>
    <label>Late Fee  Amount  Outstanding</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/NSF_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>NSF_Fee_Amount_Outstanding__c</fullName>
    <label>NSF Fee  Amount  Outstanding</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Other_Fee_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Other_Fee_Amount_Outstanding__c</fullName>
    <label>Other Fee  Amount  Outstanding</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Cycle_History__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Next Payment  Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreateProductSnapshotBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Class that fetch eligible Product and create Product Snapshot Records    
*  @author : A5E Consulting
*  @date : 01/30/2017   

*************************************************************************************************/
global Class CreateProductSnapshotBatch implements Database.Batchable<sObject>{
    
    public Product_Snapshot_Settings__c prodSnapSettings;
    
    //constructor
    public CreateProductSnapshotBatch(){
    
        //fetch Product Snapshot Settings record
        prodSnapSettings = Product_Snapshot_Settings__c.getOrgDefaults();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select Id, Name, Available_Credit_Amount__c, Last_Statement_Balance__c, Last_Statement_Credit_Interest_Amount__c, Card_Used_This_Month__c, 
                                        Late_Fee_Amount_Outstanding__c,NSF_Fee_Amount_Outstanding__c, Credit_Limit__c, Current_Average_Daily_Balance__c, Current_Balance__c, Payment_Amount__c, 
                                        Other_Fee_Amount_Outstanding__c, Last_Payment_Amount__c, External_Status_Current__c, Internal_Status__c,Last_Delinquency_Date__c, 
                                        Current_Balance_Effective_Date__c, Last_Payment_Date__c, Credit_Limit_Last_Changed_Date__c, Last_Statement_Date__c, Latest_NSFED_Date__c, 
                                        Payment_Due_Date__c, Delinquency_Cycles__c, Delinquency_Days__c, Product_Status__c, Source_System__c, Times_NSF__c,  
                                        LastModifiedById, LastModifiedDate, Credit_Limit_Last_Changed_Amount__c
                                        //From Product__c WHERE (Source_System__c ='FDR' OR Source_System__c = 'Megasys') AND Charged_Off_Date__c = null AND Closed_Date__c = null
                                        //From Product__c WHERE (Source_System__c ='FDR' and External_Status_Current__c = null and Closed_Date__c = null) or (Source_System__c = 'Megasys' and Internal_Status__c='Active' and Closed_Date__c = null)
                                        //From Product__c WHERE External_Status_Current__c !='Z' and (Source_System__c ='FDR' or Source_System__c = 'Megasys')
                                        From Product__c WHERE (Source_System__c ='FDR' and External_Status_Current__c !='Z' and Current_Balance__c != 0) or (Source_System__c = 'Megasys' and Internal_Status__c='Active' and Closed_Date__c = null)
                                        ]);
    }
    
    //create Product Snapshots Records
    global void execute(Database.BatchableContext BC, List<Product__c> prodList){
    
        List<Product_Cycle_History__c> prdSnapList = New List<Product_Cycle_History__c>();
        
        for(Product__c prd : prodList){
            
            Product_Cycle_History__c prdSnap = New Product_Cycle_History__c();
            
            prdSnap.Available_Credit_Amount__c = prd.Available_Credit_Amount__c;
            prdSnap.Card_Used_This_Month__c = prd.Card_Used_This_Month__c;
            prdSnap.Current_Average_Daily_Balance__c = prd.Current_Average_Daily_Balance__c;
            prdSnap.Current_Balance__c = prd.Current_Balance__c;
            prdSnap.Last_Payment_Amount__c = prd.Last_Payment_Amount__c;
            prdSnap.Last_Statement_Credit_Interest_Amount__c = prd.Last_Statement_Credit_Interest_Amount__c;
            prdSnap.Payment_Amount__c = prd.Payment_Amount__c;
            prdSnap.NSF_Fee_Amount_Outstanding__c = prd.NSF_Fee_Amount_Outstanding__c;
            prdSnap.Last_Statement_Balance__c = prd.Last_Statement_Balance__c;
            prdSnap.Late_Fee_Amount_Outstanding__c = prd.Late_Fee_Amount_Outstanding__c;
            prdSnap.Other_Fee_Amount_Outstanding__c = prd.Other_Fee_Amount_Outstanding__c;
            prdSnap.Payment_Amount__c = prd.Payment_Amount__c;
            prdSnap.Credit_Limit__c = prd.Credit_Limit__c;
            prdSnap.Credit_Limit_Last_Changed_Amount__c = prd.Credit_Limit_Last_Changed_Amount__c;
            prdSnap.Times_NSF__c = prd.Times_NSF__c;    
            
            prdSnap.External_Status_Current__c = prd.External_Status_Current__c;
            prdSnap.Internal_Status__c = prd.Internal_Status__c;
            //prdSnap.Last_Payment_Status__c = prd.Last_Payment_Status__c;
            prdSnap.Delinquency_Cycles__c = prd.Delinquency_Cycles__c;
            prdSnap.Delinquency_Days__c = prd.Delinquency_Days__c;
            prdSnap.Product_Status__c = prd.Product_Status__c;
            prdSnap.Source_System__c = prd.Source_System__c;
            
            prdSnap.Product_Last_Modified_By__c = prd.LastModifiedById;
            prdSnap.Product_Last_Modified_Date__c = prd.LastModifiedDate;
            prdSnap.Last_Statement_Date__c = prd.Last_Statement_Date__c;
            prdSnap.Latest_NSFED_Date__c = prd.Latest_NSFED_Date__c;
            prdSnap.Payment_Due_Date__c = prd.Payment_Due_Date__c;
            prdSnap.Last_Payment_Date__c = prd.Last_Payment_Date__c;
            prdSnap.Last_Delinquency_Date__c = prd.Last_Delinquency_Date__c;
            prdSnap.Credit_Limit_Last_Changed_Date__c = prd.Credit_Limit_Last_Changed_Date__c;
            prdSnap.Current_Balance_Effective_Date__c = prd.Current_Balance_Effective_Date__c;
            
            prdSnap.Product__c = prd.Id;
            prdSnap.Iteration_Number__c = prodSnapSettings.Next_Iteration__c;
             
            prdSnapList.add(prdSnap);
        }
        
        //insert Product Snapshot List records
        insert prdSnapList;
    }
    
    //Update the Product Snapshot Custom Setting Record
    global void finish(Database.BatchableContext BC){
        
        Decimal num ;
        if(prodSnapSettings.Iteration_Limit__c == prodSnapSettings.Next_Iteration__c){
            num = 1;
        }
        else{
            num = prodSnapSettings.Next_Iteration__c + 1;
        }
        prodSnapSettings.Next_Iteration__c = num;
        
        update prodSnapSettings; 
        
    }
}