force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>The current balance outstanding on this account</description>
    <inlineHelpText>The current balance outstanding on this account</inlineHelpText>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>The primary account holder&apos;s first name</description>
    <inlineHelpText>The primary account holder&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Minimum_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Payment_Amount__c</fullName>
    <description>The minimum monthly payment amount due, if applicable</description>
    <inlineHelpText>The minimum monthly payment amount due, if applicable</inlineHelpText>
    <label>Minimum Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PreviewProductEmailCntrl.cls
/***************************************************
* Author         : A5E Consultancy
* Last Modified  : 13 Apr 2017
* Description    : Provided user to preview & print email templates with product merge fields
*
***************************************************/
public class PreviewProductEmailCntrl{

    // To render HTML in vf page 
    public String htmlBody { get; set; }
    
    // To define how the page should display
    public String renderedAs{set;get;}
    Product__c prod;
    String templateName;
    
    // Constructor to read product through SOQL
    public PreviewProductEmailCntrl(){
        Id prodId = ApexPages.currentPage().getParameters().get('Id');
        templateName = ApexPages.currentPage().getParameters().get('TemplateName');
        renderedAs = ApexPages.currentPage().getParameters().get('renderedAs');
        
        // Queries product record and values
        prod = [SELECT First_Name__c, Minimum_Payment_Amount__c, Current_Balance__c, Name FROM Product__c WHERE Id =: prodId];
        
        // Queries Email template that selected by user
        htmlBody = [Select id,HtmlValue from EmailTemplate where Name =: TemplateName ].HTMLValue;
        
        // Mapping merge field to replace in HTML body
        Map<String, String> mapBodyParams = new Map<String, String>{
                                             '{!Product__c.First_Name__c}' => prod.First_Name__c,
                                             '{!Product__c.Minimum_Payment_Amount__c}' => '$'+String.valueOF(prod.Minimum_Payment_Amount__c),
                                             '{!Product__c.Current_Balance__c}' => '$'+String.valueOf(prod.Current_Balance__c),
                                             '{!Product__c.Name}' => prod.Name
                                             };
        // Replacing mere fields with product data
        for(String key : mapBodyParams.keySet()){
            htmlBody = htmlBody.replace(key, (mapBodyParams .get(key) == null) ? '' : mapBodyParams .get(key));
        }
    }
    
    // Creating Activity
    public void createActivity(){
        if(renderedAs != 'pdf' && templateName != null && templateName != ''){
        Task activity = new Task( Subject = 'Print Email - '+templateName,
                WhatId = prod.Id,
                OwnerId = UserInfo.getUserId(),
                Status='Completed');
        insert activity;
        }
    }
}