force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The date this account was closed</description>
    <inlineHelpText>The date this account was closed</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Disbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount__c</fullName>
    <description>The actual amount disbursed to the customer on this account</description>
    <inlineHelpText>The actual amount disbursed to the customer on this account</inlineHelpText>
    <label>Disbursement Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/External_Status_Current__c.field-meta.xml
<CustomField>
    <fullName>External_Status_Current__c</fullName>
    <description>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</description>
    <inlineHelpText>FDR:  The External Status of this account
Megasys: The AdminStatus of the loan account</inlineHelpText>
    <label>External Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Amount__c</fullName>
    <description>The amount that the customer was required to pay as the first payment on this account</description>
    <inlineHelpText>The amount that the customer was required to pay as the first payment on this account</inlineHelpText>
    <label>First Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>The date that the first payment was due for this account</description>
    <inlineHelpText>The date that the first payment was due for this account</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Source_Token__c.field-meta.xml
<CustomField>
    <fullName>Funding_Source_Token__c</fullName>
    <description>To Calculate Source Token depend Branch Number</description>
    <formula>CASE( Branch_Number__c , 
null, &apos;BA3RI923U3GF&apos;, 
1, &apos;BA3RI923U3GF&apos;, 
2, &apos;BA7RDF3X3MP3&apos;, 
3, &apos;BA3RI923U3GF&apos;, 
4, &apos;BA7RDF3X3MP3&apos;, 
&apos;BA3RI923U3GF&apos;)</formula>
    <inlineHelpText>To Calculate Source Token depend Branch Number</inlineHelpText>
    <label>Funding Source Token</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Hold_Payments__c.field-meta.xml
<CustomField>
    <fullName>Hold_Payments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</description>
    <inlineHelpText>Indicates whether or not this account should have it&apos;s automatic payment processing be suspended</inlineHelpText>
    <label>Hold Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Amount__c</fullName>
    <description>An override of the next payment amount for automatic processing</description>
    <inlineHelpText>An override of the next payment amount for automatic processing</inlineHelpText>
    <label>Override Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Payment_Date__c</fullName>
    <description>An override of the next payment date for automatic processing</description>
    <inlineHelpText>An override of the next payment date for automatic processing</inlineHelpText>
    <label>Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>The next payment amount due</description>
    <inlineHelpText>The next payment amount due</inlineHelpText>
    <label>Next Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <description>The date that the next payment is due</description>
    <inlineHelpText>The date that the next payment is due</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Released_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Released_Date__c</fullName>
    <description>The date that account funds were delivered to the customer</description>
    <inlineHelpText>The date that account funds were delivered to the customer</inlineHelpText>
    <label>Payment Released Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Payment_Setup_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Setup_Status__c</fullName>
    <description>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</description>
    <inlineHelpText>Indicates whether the account is currently having payments deducted from the customer automatically, manually, or N/A</inlineHelpText>
    <label>Payment Setup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/SP_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>SP_First_Payment_Date__c</fullName>
    <description>Scheduled Payment Date - First Payment Date</description>
    <formula>First_Payment_Date__c - 1</formula>
    <inlineHelpText>Scheduled Payment Date - First Payment Date</inlineHelpText>
    <label>SP First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/SP_Next_Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>SP_Next_Payment_Due_Date__c</fullName>
    <description>Scheduled Payment Date - Next Payment Date</description>
    <formula>Payment_Due_Date__c - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Scheduled Payment Date - Next Payment Date</inlineHelpText>
    <label>SP Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/SP_Override_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>SP_Override_Payment_Date__c</fullName>
    <description>Scheduled Payment Date - Override Payment Date</description>
    <formula>Override_Payment_Date__c - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Scheduled Payment Date - Override Payment Date</inlineHelpText>
    <label>SP Override Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/VersaPay_Product_Payment__c.object-meta.xml
<CustomObject>
    <description>Product Payment</description>
    <label>Product Payment</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>VersaPay Product Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Actual Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Process_On__c.field-meta.xml
<CustomField>
    <fullName>Process_On__c</fullName>
    <description>Effective Payment Date</description>
    <label>Process On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VersaPay_Product_Payment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>VersaPay_Product_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentCreateBatch.cls
/**************************************************************************************************
*
*  Class:  PaymentCreateBatch 
*
*  @description : Batch class that will process direct_debit transactions
*  author : A5E Consulting
*
*  @date : 27/02/2017   
*************************************************************************************************/

global class PaymentCreateBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    //Query all the product records for Payment Setup Batch record passed.
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select id, name, /*SOR_External_ID__c,*/ Disbursement_Amount__c, 
                                        Customer__r.PersonEmail, Customer__r.FirstName, Customer__r.LastName,
                                        PAP_Bank_Code__c, PAP_Transit_Code__c, PAP_Account_Number__c, 
                                        Override_Payment_Date__c, First_Payment_Date__c, //Next_Payment_Date__c, 
                                        Override_Payment_Amount__c, First_Payment_Amount__c,//Next_Payment_Amount__c,
                                        SP_Override_Payment_Date__c, SP_Next_Payment_Due_Date__c, SP_First_Payment_Date__c,
                                        Payment_Amount__c, Payment_Due_Date__c,
                                        Funding_Source_Token__c 
                                        from Product__c 
                                        WHERE Hold_Payments__c = false
                                        AND (Funding_Status__c = 'Funded' OR Funding_Status__c = 'Manually Funded')
                                        AND Payment_Setup_Status__c = 'Automated' 
                                        //AND External_Status_Current__c = 'Active'
                                        AND Closed_Date__c = null
                                        AND Payment_Released_Date__c != TODAY 
                                        AND (Override_Payment_Amount__c != null OR Payment_Amount__c != null OR First_Payment_Amount__c != null)
                                        AND ((SP_Override_Payment_Date__c != null AND SP_Override_Payment_Date__c = TODAY)
                                            OR (SP_Override_Payment_Date__c = null AND SP_Next_Payment_Due_Date__c = TODAY)
                                            OR (SP_Override_Payment_Date__c = null AND SP_Next_Payment_Due_Date__c = null AND SP_First_Payment_Date__c = TODAY))]);
    }
    
    //Create PAyment Records in Salesforce
    global void execute(Database.BatchableContext BC, List<Product__c> prodList){
        
        // Used to store new VersaPayment records
        List<VersaPay_Product_Payment__c> prodPayList = New List<VersaPay_Product_Payment__c>();    
        
        // Used to update product with Payment_Released_Date__c
        List<Product__c> prdList = New List<Product__c>();    

        for(Product__c prod : prodList){
            
            //Create VersaPay Payment record
            VersaPay_Product_Payment__c prodPay = New VersaPay_Product_Payment__c();
            prodPay.Product__c = prod.Id;
            
            //Payment amount
            Decimal amountInCents = VersaPayWSUtil.countAmountInCentsDebit(prod.Override_Payment_Amount__c, prod.Payment_Amount__c, prod.First_Payment_Amount__c, prod.SP_First_Payment_Date__c);
            if(amountInCents != null){
                prodPay.Payment_Amount__c = amountInCents/100; 
            }
            
            //Get effective payment date
            prodPay.Process_On__c = VersaPayWSUtil.effectiveDateForPayment(prod);
            
            prodPayList.add(prodPay);
            
            //Update Product record 
            prod.Payment_Released_Date__c = (system.now()).date();
            prod.Override_Payment_Amount__c = null;
            prod.Override_Payment_Date__c = null;                    
                    
            prdList.add(prod);         
        }
        
        //Insert Payment Records
        if(prodPayList.size() >0){
            insert prodPayList;
            system.debug('New prodPay = '+prodPayList);
        }
        
        //Update Products - Ameya please confirm this update should happen here or in Payment Batch
        if(prdList.size() >0){
            ProductTriggerHandler.runProductTrigger = false;
            update prdList;
            ProductTriggerHandler.runProductTrigger = true;
        }  
    }
        
    global void finish(Database.BatchableContext BC){
        
        //Initiate Payment Processing batch
        Database.executeBatch(New PaymentProcessingBatch(), 1);                                  
    }       
}