force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Charged_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Charged_Off_Date__c</fullName>
    <description>The date that this account charged off, if applicable</description>
    <inlineHelpText>The date that this account charged off, if applicable</inlineHelpText>
    <label>Charge Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The date this account was closed</description>
    <inlineHelpText>The date this account was closed</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer record this account links to in Salesforce</description>
    <inlineHelpText>The customer record this account links to in Salesforce</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <description>The requested amount to be funded on this account</description>
    <inlineHelpText>The requested amount to be funded on this account</inlineHelpText>
    <label>Requested Funding Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Date__c.field-meta.xml
<CustomField>
    <fullName>Funding_Date__c</fullName>
    <description>The requested date this account was funded by Affirm</description>
    <inlineHelpText>The requested date this account was funded by Affirm</inlineHelpText>
    <label>Requested Funding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Funding_Status__c.field-meta.xml
<CustomField>
    <fullName>Funding_Status__c</fullName>
    <description>The current status of this account&apos;s funding process</description>
    <inlineHelpText>The current status of this account&apos;s funding process</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Manually Funded</fullName>
            </value>
            <value>
                <fullName>Funding Failed</fullName>
            </value>
            <value>
                <fullName>Released Batch</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Process_Type__c</fullName>
    <description>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</description>
    <inlineHelpText>Determines EFT Processing based on the selected loan type (Traditional, RBO, Rewrite, etc)</inlineHelpText>
    <label>Loan Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Re-write</fullName>
            </value>
            <value>
                <fullName>RBO</fullName>
            </value>
            <value>
                <fullName>Consolidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>PAP_Account_Number__c</fullName>
    <description>The current Pre-Authorized Payment Account Number</description>
    <inlineHelpText>The current Pre-Authorized Payment Account Number</inlineHelpText>
    <label>PAP Account Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Bank_Code__c</fullName>
    <description>The current Pre-Authorized Payment Bank Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Bank Code</inlineHelpText>
    <label>PAP Bank Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PAP_Transit_Code__c.field-meta.xml
<CustomField>
    <fullName>PAP_Transit_Code__c</fullName>
    <description>The current Pre-Authorized Payment Transit/Branch Code</description>
    <inlineHelpText>The current Pre-Authorized Payment Transit/Branch Code</inlineHelpText>
    <label>PAP Transit Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>The status of this product (Active, closed, charged-off, etc)</description>
    <inlineHelpText>The status of this product (Active, closed, charged-off, etc)</inlineHelpText>
    <label>Product Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Regular_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Regular_Payment_Amount__c</fullName>
    <description>The regular payment amount for this account, if applicable</description>
    <inlineHelpText>The regular payment amount for this account, if applicable</inlineHelpText>
    <label>Regular Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The System of Record this account is found in (FDR, DebtNext, etc)</description>
    <inlineHelpText>The System of Record this account is found in (FDR, DebtNext, etc)</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DebtNext</fullName>
            </value>
            <value>
                <fullName>FDR</fullName>
            </value>
            <value>
                <fullName>Megasys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Snapshot_Settings__c/Product_Snapshot_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product Snapshot Settings</description>
    <label>Product Snapshot Settings</label>
</CustomObject>

force-app/main/default/objects/Product_Snapshot_Settings__c/fields/Iteration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Limit__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Iteration Limit</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Snapshot_Settings__c/fields/Next_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Next_Iteration__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Next Iteration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestCreateProductSnapshotBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Test Class for CreateProductSnapshotBatch      
*  @author : A5E Consulting
*  @date : 02/03/2017   

*************************************************************************************************/
@isTest
public class TestCreateProductSnapshotBatch{

    public Static testMethod void createPrdSnapBatch(){
        
        //create Product Snapshot Custom Setting Record    
        createProductSnapCS();
        
        //create Product record
        createProduct();
        
        //execute DeleteProductSnapshotBatch
        Database.executeBatch(New CreateProductSnapshotBatch(), 200);
    }
    
     //create Product records
    public static Product__c createProduct(){
        
        Product__c prd = new Product__c();
        prd.customer__c = createAccount().id;
        prd.Product_Status__c = 'New';
        prd.Funding_Amount__c = 1000.00;
        prd.Loan_Process_Type__c = 'Traditional';
        prd.Funding_Status__c = 'Pending';
        prd.Funding_Date__c = System.Today();
        prd.Regular_Payment_Amount__c = 100.00;
        //prd.SOR_Primary_Account_Number__c = '12345678912';
        prd.PAP_Account_Number__c = '98745632';
        prd.PAP_Transit_Code__c = '456';
        prd.PAP_Bank_Code__c = '12';
        prd.Source_System__c = 'FDR';
        prd.Charged_Off_Date__c = null; 
        prd.Closed_Date__c = null;
        insert prd;
        
        return prd;
    }

    //create Product Snapshot Custom Setting Record
    public static Product_Snapshot_Settings__c createProductSnapCS(){
        
        Product_Snapshot_Settings__c prdSnap = New Product_Snapshot_Settings__c();
        prdSnap.Iteration_Limit__c = 2;
        prdSnap.Next_Iteration__c = 1;
        
        insert prdSnap;
        
        return prdSnap;
    }
    
    //create Customer
    private static Account createAccount(){
        Account acc = new Account();
        
        acc.Salutation = 'Mr.';
        acc.FirstName = 'Asad';
        acc.Middle_Name__pc = 'Full';
        acc.LastName = 'Person';
        
        acc.PersonMailingState = 'ON';
        acc.PersonBirthdate = Date.newInstance(1983, 12, 2);
        acc.Gender__pc = 'Male';
        acc.Marital_Status__pc = 'Single';
        
        acc.Employer_Province__pc = 'ON';
        acc.Number_of_Dependants__pc = '0';
        acc.Home_Owner__pc = 'Own';
        acc.PersonMailingState = 'ON';
        
        acc.PersonHomePhone = '1235551234';
        acc.PersonEmail = 'asad.fullperson@test.com';
        acc.SIN__pc = '123456789';
        acc.PersonMobilePhone = '5551231234';
        acc.Work_Phone__pc = '1112223333';
        
        acc.Communication_Preference__pc = 'Email';
        acc.Monthly_Home_Expense__pc = 2000;
        acc.Monthly_Expense__pc = 500;
        
        acc.PersonMailingStreet = '4 Glenora';
        acc.PersonMailingCity = 'Brampton';
        acc.PersonMailingPostalCode = 'L6Y4K5';
        
        acc.Employer_Name__pc = 'Paper Empire';
        acc.Employer_Phone__pc = '9991231234';
        acc.Employer_Street_Name__pc = 'Brick Lane';
        acc.Employer_Street_Number__pc = '4';
        acc.Employer_City__pc = 'Brampton';
        acc.Employer_Postal_Code__pc = 'L6Y4K4';
        acc.Occupation__pc = 'Manager';
        acc.Employment_Years__pc = 3;
        acc.Employment_Months__pc = 10;
        acc.Gross_Monthly_Income__pc = 5000;
        
        insert acc;
        
        return acc;
    }
}