force-app/main/default/objects/Product_Cycle_History__c/Product_Cycle_History__c.object-meta.xml
<CustomObject>
    <description>Product Sanpshot</description>
    <label>Product Cycle History</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Cycle History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cycle_History__c/fields/Iteration_Number__c.field-meta.xml
<CustomField>
    <fullName>Iteration_Number__c</fullName>
    <label>Iteration Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Snapshot_Settings__c/Product_Snapshot_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product Snapshot Settings</description>
    <label>Product Snapshot Settings</label>
</CustomObject>

force-app/main/default/objects/Product_Snapshot_Settings__c/fields/Next_Iteration__c.field-meta.xml
<CustomField>
    <fullName>Next_Iteration__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Next Iteration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeleteProductSnapshotBatch.cls
/**************************************************************************************************
*
*  Class:   
*
*  @description : Apex Class that delete Product Cycle History Records based on Iteration number     
*  @author : A5E Consulting
*  @date : 01/30/2017   

*************************************************************************************************/
global Class DeleteProductSnapshotBatch implements Database.Batchable<sObject>{
    
    public Product_Snapshot_Settings__c prodSnapSettings;
    
    //constructor
    public DeleteProductSnapshotBatch(){
        
        //fetch Product Snapshot Settings record
        prodSnapSettings = Product_Snapshot_Settings__c.getOrgDefaults();
    }
    
    //fetch eligible Product Snapshots records
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select Id, Name FROM Product_Cycle_History__c WHERE Iteration_Number__c =: prodSnapSettings.Next_Iteration__c ]);
    }
    
    //delete all the records returned by the query.
    global void execute(Database.BatchableContext BC, List<Product_Cycle_History__c> prodList){
    
        if(prodList.size() != 0){
            delete prodList;
        }
    }
    
    //initiate the CreateProductSnapshotBatch Job
    global void finish(Database.BatchableContext BC){
        
        Database.executeBatch(New CreateProductSnapshotBatch(), 200);
    }
}